### ISSUE TITLE
IDE project files under source control

### ISSUE THREAD

**Issue by topr** [CodeNarc/CodeNarc#100]
I've noticed that Eclipse and IDEA project files are in the Git repo. Is it by purpose?

It's rather not the best approach to commit such files. They usually contain local env related, developer specific stuff.

It's enough to open project under IDE to get such files changed. Some additional effort is required to avoid committing such changes. They are easy to commit by accident as well. Then somebody does checkout and gets own project configuration broken in a result.

Don't you think it would be better to remove and add to .gitignore following files:
- .classpath
- .project
- CodeNarc.iml
- CodeNarc.ipr

I'm not 100% sure about any reason for keeping Eclipse files as I'm not using it, but listed two IDEA's file cause some pain while working with repo codebase under IDE.

EDIT:
Oh, issue nr. 100, time to celebrate? :cake: :cocktail: :tada: :wink:

**Comment by chrismair** [comment]
I am fine removing the Eclipse files.

Re: IDEA, I was going off of this and similar references:
https://intellij-support.jetbrains.com/entries/23393067-How-to-manage-projects-under-Version-Control-Systems
which indicate to save the .ipr and .iml files.

Though this seems to discuss the pain you mention:
http://stackoverflow.com/questions/7060727/how-to-deal-with-intellij-idea-project-files-under-git-source-control-constantly

What do you think?

**Comment by erdi** [comment]
IMHO, a good idea is to use Gradle's idea plugin which allows you to generate these files. This allows for everybody having a consistent IDE config and not having to deal with issues related to absolute paths ending up in these files, them randomly changing and causing conflicts. Basic setup is dead simple but you can customise things to a great level if you need or want to, like [Geb does](https://github.com/geb/geb/blob/master/gradle/idea.gradle).

**Comment by topr** [comment]
@chrismair 
Thanks for considering this matter.

The links you posted address mostly how to share IDE's project files under VCS.
The valid question is: why to do so? What's the benefit (and effort) of keeping them checked in?
Any group of devs needs to answer those questions on its own. Is there anything specific within those checked in IDEA project files, anything which can't be maintained with build.gradle file (and pom.xml in master for the time being) given that IDEA is able to open both, gradle and maven project filles, straight away with no hassle?

I have found in my experience that even in a team within the same organization it is just much easier not to share IDE's project files. Especially if there is strongly unified work environment enforced by employer (then you won't meet a good devs in such place anyway). Developers in the OS community are not really unified in terms of work environment setup, are they? :neckbeard: 
I might be missing something here though, there I shall listen.

@erdi: Yup, I agree IDEA Gradle plugin might be helpful. I've been using it for some time when IDEA's Gradle support was still buggy. There is Eclipse plugin as well.

**Comment by chrismair** [comment]
I have removed the IDEA files from source control and added the IDEA plugin. Great suggestion. Thanks.
