### ISSUE TITLE
enums should not trigger check for SerialVersionUID

### ISSUE THREAD

**Issue by tedder** [CodeNarc/CodeNarc#117]
This is mentioned as number 10 in #105 and is declared fixed, but I'm on codenarc v0.24 and it fails. Here's a sample violation; I've scrubbed my project class names and called it Foo. I've left "Channels" in place for sanity.

    Violation: Rule=SerializableClassMustDefineSerialVersionUID P=1 Line=22 Msg=[The class Foo$Channels implements Serializable but does not define a serialVersionUID] Src=[enum Channels { one, two, three, four }]

**Comment by chrismair** [comment]
I have not been able to reproduce so far, for code like this:

            class MyClass {
                enum Channels { one, two, three, four }
            }
or for top-level enum class.

What version of Java and Groovy are you using? I have tried a few different combinations.

**Comment by tedder** [comment]
I'm on Java7, Groovy 2.4, Grails 2.5. I'll try to get a sample project together in the coming days.

**Comment by tedder** [comment]
update- I've been working on this for a couple hours. I have something that is reproducable. I'm trying to pare down the variables involved, but right now it's looking like some rules that are conflicting.

**Comment by tedder** [comment]
okay, here's my sample project: https://github.com/tedder/tedder-grails-example-project-catpics-v2

The only rule included is the `EnumCustomSerializationIgnored`.

To run, do this:

    ./grailsw compile
    ./grailsw codenarc -plain-output -non-interactive

The final lines of the output should be this:

    ..Running CodeNarc (file:grails-app/conf/CodeNarcRules.groovy) ...
    .FAILED -- Exceeded maximum number of priority 2 violations: (p1=0; p2=4; p3=0)

**Comment by chrismair** [comment]
Thanks very much for the isolated sample project. That was helpful. I am able to reproduce your results, but only without the `grails compile`. Running `grails clean` and then `grails codenarc` produces the violations, but running `grails compile` in between results in no violations. Weird.

**Comment by tedder** [comment]
Yeah, some oddity. I see your commit- I hope that helps! The AST walking is somewhat voodoo to me, so I can only hope.

**Comment by chrismair** [comment]
I released CodeNarc v0.24.1 and also Grails CodeNarc Plugin v0.24.1, containing this fix. I verified that it no longer produced the incorrect violation in your sample project (at least for me).

By the way, that release also contains the fix so that `excludeBaseline = ''` is no longer necesarry in `BuildConfig.groovy`.

**Comment by tedder** [comment]
I put 0.24.1 in my non-sample project and removed all of the "suppress" annotations for enums (probably ~15). I also removed `excludeBaseline`. It's all good now. Thanks!
