### ISSUE TITLE
BracesForIfElse with curly braces inside GString

### ISSUE THREAD

**Issue by Myllyenko** [CodeNarc/CodeNarc#119]
CodeNarc 0.24.1 mistakenly marks statements of the following form as BracesForIfElse (sameLine = false) violation:
<code>if (someContainer."${SomeClass.SOME_CONSTANT}" != null)</code>

**Comment by Myllyenko** [comment]
The same pseudo-violation detected in case of "if (someCollection.any { someClosure } )"

**Comment by chrismair** [comment]
Fixed by #130

**Comment by Myllyenko** [comment]
Could you please make a Codenarc realease in which this issue is fixed?

**Comment by chrismair** [comment]
I'll try to get a release out within a few weeks.
