### ISSUE TITLE
Use of 'print' in a Spock mock triggers println violation

### ISSUE THREAD

**Issue by influenza** [CodeNarc/CodeNarc#120]
Given code such as:

``` groovy
        ServletOutputStream mockOutputStream = Mock(ServletOutputStream) {
            print(_) >> { String str -> responseText.append(str) }
            1 * flush()
        }
```

CodeNarc will incorrectly emit the following P1 violation:

```
File: test/unit/redacted.groovy
    Violation: Rule=Println P=1 Line=38 Msg=[println should be replaced with something more robust] Src=[print(_) >> { String str -> responseText.append(str) }]

```

**Comment by tedder** [comment]
The same rule applies to `print` as to `println`: https://github.com/CodeNarc/CodeNarc/blob/master/src/main/groovy/org/codenarc/rule/logging/PrintlnRule.groovy#L45

It should, right?

**Comment by influenza** [comment]
I suppose `print` could be changed to `write`. I was surprised the violation occurred within the definition of a mock

**Comment by chrismair** [comment]
You can also turn off the rule for all Spock files, e.g. using the
doNotApplyToClassNames or doNotApplyToFileNames property on the rule.

http://codenarc.sourceforge.net/codenarc-configuring-rules.html#Standard_Properties_for_Configuring_Rules

**Comment by chrismair** [comment]
So far, I do not see a way to make the rule smart enough to solve this issue in a generalized way. Using `@SuppressWarnings('Println')` or turning off the rule as mentioned above is still probably the way to go.

**Comment by jlstrater** [comment]
@influenza I agree with @chrismair that this is not something we can solve and the annotation should be used instead. Can we close this issue as `won't do`?

**Comment by chrismair** [comment]
Closing. Feel free to reopen if appropriate.
