### ISSUE TITLE
Compilation failed errors

### ISSUE THREAD

**Issue by JasonKDarby** [CodeNarc/CodeNarc#123]
I just added codenarc to a Gradle project and am getting this error for every file in my sourceSet.  
`Compilation failed for [CustomCompilerPhaseSourceDecorator[SourceFile[SomeFile.groovy]]].`
I saw the post about specifying a groovy version on the codenarc dependency and did that but I get the same error.  I tried using different versions of codenarc and (after removing incompatible rules) get the same problem.  I'm using Groovy 2.4.5, I tried using 2.3.10 as well.  Any ideas?

**Comment by chrismair** [comment]
I assume you are using the Gradle CodeNarc plugin.

I would start with just the "basic" ruleset, and see if you still get the error.

I expect that error is coming from the rules in the "enhanced" ruleset, so remove those rules from your ruleset:
http://codenarc.sourceforge.net/codenarc-rules-enhanced.html

**Comment by EarthCitizen** [comment]
@chrismair When these errors are present, will it cause any differences in reporting? For example, will it cause any violations that are not in the enhanced set to not get reported.

**Comment by chrismair** [comment]
There should be no effect on the other rules and their violations. The "regular" rules use a separate compilation and the default compiler phase.

**Comment by darxriggs** [comment]
Just for reference: With change #192 in CodeNarc which can be used since Gradle 4.2 the `compilationClasspath` can be set for a [CodeNarc task](https://docs.gradle.org/4.2/javadoc/org/gradle/api/plugins/quality/CodeNarc.html). That's the way to provide dependencies for the "enhanced" rules.

**Comment by rmorrise** [comment]
The following code snippet helped me fix this issue for my Spring Boot project:
https://stackoverflow.com/a/64590968/166850
