### ISSUE TITLE
AssignmentInConditional rule is not catching all cases

### ISSUE THREAD

**Issue by taras80** [CodeNarc/CodeNarc#125]
It catches this case:

if ((value = true)) {
    }

But not this one:
if (value = true) {
    }

**Comment by ychulovskyy** [comment]
@taras80 @chrismair 
```
if (value = true) {
}
```
is not a valid Groovy statement. It causes compilation error.
Does it make sense to close the issue as "won't fix"?

**Comment by taras80** [comment]
Exactly, so AssignmentInConditional rule should be catching it as error.

**Comment by ychulovskyy** [comment]
@taras80 If you update AssignmentInConditionalRuleTest.testIfStatement() accordingly and run the it will fail at AbstractRuleTestCase.groovy:287:
```
assert sourceCode.valid
```
IMHO, it's correct. Rule should not validate code that cannot be compiled.
E.g. Checkstyle has the same approach. There is no sense to validate code quality if you cannot compile the code.
Anyway, it's up to @chrismair to decide.

**Comment by chrismair** [comment]
I agree that because it is not valid Groovy, the rule does not need to handle it. We have a general principle of not handling illegal code. Thanks for the discussion and assistance.
