### ISSUE TITLE
EmptyClass rule: also ignore abstract classes

### ISSUE THREAD

**Issue by chrismair** [CodeNarc/CodeNarc#143]
There are some situations where an abstract class may be provided that is empty.

**Comment by chrismair** [comment]
Fixed for CodeNarc 0.25

**Comment by mkordas** [comment]
@chrismair can you provide some example when abstract class must be empty?

**Comment by chrismair** [comment]
Yeah, this one is a little bit controversial. We had some teams that implemented abstract superclasses along with framework classes. In one case the abstract superclass was just an empty placeholder. That superclass may end up accumulating fields/behavior, or maybe not. But they wanted the hierarchy in place when the (potentially many) subclasses are created. And it may not be the same folks creating/owning the subclasses.

Any thoughts or objections?
