### ISSUE TITLE
Setting doNotApplyToFilesMatching for one rule affects the whole rule set

### ISSUE THREAD

**Issue by Myllyenko** [CodeNarc/CodeNarc#146]
I have a custom ruleset in which all rules are declared one by one in the following manner:
```
<rule class='org.codenarc.rule.naming.ClassNameRule'/>
<rule class='org.codenarc.rule.naming.ClassNameSameAsFilenameRule'/>
<rule class='org.codenarc.rule.naming.ClassNameSameAsSuperclassRule'/>
```

If I don't use ```doNotApplyToFilesMatching``` at all, CodeNarc finds 15 violations of four rules (it is expected behaviour). But if I enable this property only for one rule:
```
<rule class='org.codenarc.rule.naming.MethodNameRule'>
  <property name='doNotApplyToFilesMatching' value='*/test/groovy/*'/>
</rule>
```
CodeNarc doesn't find any violations and produces the following log output:
```
Compilation failed for [CustomCompilerPhaseSourceDecorator[SourceFile[C:\workspaces\delta\ru.deltasolutions.rules\src\test\groovy\ru\deltasolutions\rules\UliAnalysisRuleSpecification.groovy]]].
Error from [org.codenarc.rule.naming.MethodNameRule] processing source file [C:/workspaces/delta/ru.deltasolutions.rules/src/test/groovy/ru/deltasolutions/rules/UliAnalysisRuleSpecification.groovy]
```

**Comment by chrismair** [comment]
The _CustomCompilerPhaseSourceDecorator_ error indicates that it is using at least one of the "enhanced" rules that requires all of the classes on the classpath when running  CodeNarc. I assume that you have some "enhanced" rules in your ruleset. But I think those errors might be there in any case, and that may not be the problem.

The _doNotApplyToFilesMatching_ property expects a regular expression, and the value you are supplying is not a valid regex, so it will cause errors trying to evaluate that against every source file. Try using _doNotApplyToFileNames_ instead.

**Comment by Myllyenko** [comment]
Thanks! My problem is solved.
I think it would be useful to add some validation for the ```doNotApplyToFilesMatching``` value in order to detect such errors in configuration.

**Comment by chrismair** [comment]
Added validation for those regex fields for CodeNarc 0.25.
