### ISSUE TITLE
BracesForIfElseRule can't process enum files

### ISSUE THREAD

**Issue by admxiii** [CodeNarc/CodeNarc#150]
I am getting an error for every standalone enum since 0.25/0.25.1, 0.24 worked fine.

[ERROR] [org.codenarc.rule.AbstractRule] Error from [org.codenarc.r
ule.formatting.BracesForIfElseRule] processing source file [.../SomeEnum.
groovy]

Example file that fails -

package com.mycompany.enums

enum Season {
	SUMMER, WINTER
}

**Comment by crazy4groovy** [comment]
Same issue I am having:

`Error from [org.codenarc.rule.formatting.BracesForIfElseRule] processing source file [C:/dev/projects/.../ActionNameEnum.groovy]`

There is no if/else anywhere in my enum.

**Comment by chrismair** [comment]
I am able to reproduce the issue, getting an error such as this for the enum class:
```
ERROR - Error from [org.codenarc.rule.formatting.BracesForIfElseRule] processing source file [...]
java.lang.ArrayIndexOutOfBoundsException: -2
```

**Comment by crazy4groovy** [comment]
TY! <3
