### ISSUE TITLE
Codenarc tries to compile classes even if no enhanced rules are configured to be used

### ISSUE THREAD

**Issue by erdi** [CodeNarc/CodeNarc#153]
In https://github.com/CodeNarc/CodeNarc/issues/152#issuecomment-201496853 @chrismair seems to suggest that if you have no rules from the enhanced classpath ruleset configured to be used then Codenarc should not try to compile your classes. Contrary to this, if my ruleset file contains:
```
ruleset {
    Println
}
```
then I'm still seeing this when running Codenarc
`Compilation failed for [SourceFile[/Users/erdi/workspace/(***)/ValidationSpec.groovy]].`

If I use an empty ruleset, i.e. 
```
ruleset {
}
```
then these errors do not show up which makes me sure that my ruleset configuration file is being used.

**Comment by chrismair** [comment]
I did not mean to imply that CodeNarc would not compile your classes, but rather that the error message containing "CustomCompilerPhaseSourceDecorator" implies that it is an enhanced rule throwing the compilation error.

**Comment by erdi** [comment]
Your comment made me think about it a bit more and have a closer look at the classes that were causing the warnings and I've noticed that they all are traits. After upgrading groovy version used by codenarc (I'm using gradle which isolates codenarc classpath and uses the groovy version declared in codenarc's pom when running it which is different to the one we use to run our application) to 2.3.0 which is the version in which traits have been introduced the warnings went away.

Sorry for the noise.
