### ISSUE TITLE
Error: Could not find or load main class org.codenarc.CodeNarc

### ISSUE THREAD

**Issue by lexicalunit** [CodeNarc/CodeNarc#159]
I've downloaded the dependency jars and put them all in a single directory. When I attempt to run CodeNarc I simply get the error `Error: Could not find or load main class org.codenarc.CodeNarc`. Let me know if there are any other details I can add to help resolve this issue. I have provided the jar md5sums just in case, the version of Java I have installed, and the command I am attempting to execute. I am on OS X and extrapolated the command I should run based on the Windows example found here: http://codenarc.sourceforge.net/codenarc-command-line.html

```
$ md5sum *
59c452aabca068fbbc2b4c59485f1a14  CodeNarc-0.25.2.jar
6e5ccee6c126ae6a920f496ec8d72dc6  groovy-all-2.4.6.jar
8218714e41ee0c6509dcfeafa2e1f53f  log4j-1.2.17.tar.gz

$ java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

$ java -classpath "groovy-all-2.4.6.jar;CodeNarc-0.25.2.jar;log4j-1.2.17.tar.gz" org.codenarc.CodeNarc
Error: Could not find or load main class org.codenarc.CodeNarc
```

**Comment by lexicalunit** [comment]
The issue was that on OS X, the classpath delimiter should be `:`, rather than `;`.

However, I am still having this same issue when running CodeNarc via binary installed by [jpm4j](https://jpm4j.org/#!/p/org.codenarc/CodeNarc). When I tried to initially install it I got this error:

```
$ sudo jpm install -fn codenarc org.codenarc:CodeNarc
Error
  0. No main class found. Please specify
```

So I specified the entry point manually, like so:

```
$ sudo jpm install -fn codenarc -m org.codenarc.CodeNarc org.codenarc:CodeNarc
```

This allowed me to install a `codenarc` binary that should point to the correct entry point. However when I run it I get the familiar error:

```
$ /usr/local/bin/codenarc
Error: Could not find or load main class org.codenarc.CodeNarc
```

**Comment by chrismair** [comment]
I have not used **jpm4j** myself. The fact that you can run CodeNarc directly using Java makes me wonder whether it is a jpm4j issue, or perhaps a jpm4j CodeNarc package-specific issue.

**Comment by romani** [comment]
the same problem on Linux
```
$ java -classpath "groovy-all-2.4.3.jar;CodeNarc-0.26.0.jar;log4j-1.2.14.jar" org.codenarc.CodeNarc -basedir=my-groovy -rulesetfiles=StarterRuleSet-AllRulesByCategory.groovy.txt -report=console
Error: Could not find or load main class org.codenarc.CodeNarc

```

**Comment by chrismair** [comment]
On Linux the classpath delimiter should be ":" not ";".

**Comment by romani** [comment]
@chrismair , thanks pointing, sorry it was my mistake, after several attempts to make it work from CLI, still no luck.
Here is new issue #187 .

**Comment by jlstrater** [comment]
Since there is a new issue isn't this a duplicate that should be closed?

**Comment by lexicalunit** [comment]
🤷‍♀️

**Comment by chrismair** [comment]
Thanks. Closing
