### ISSUE TITLE
Spock tests trigger JUnitPublicNonTestMethod and MethodName violations

### ISSUE THREAD

**Issue by wcraigtrader** [CodeNarc/CodeNarc#161]
We've got both Spock specifications and JUnit tests in our codebase. When running CodeNarc v0.24.1 against our Spock specifications, we're seeing `JUnitPublicNonTestMethod` and `MethodName` violations for specs that are defined as follows:
```
def "descriptive specification name"() { 
    ... 
}
```
These methods should be public, and should not be marked with the `@Test` annotation. I don't want to disable these rules because we've got lots of JUnit tests that should be checked.

**Comment by chrismair** [comment]
Do you have a naming convention for the Spock tests, so that you could use the _doNotApplyToClassNames_ or _doNotApplyToFileNames_ property of those rules?

**Comment by wcraigtrader** [comment]
Unfortunately, no consistent naming conventions.  Many of the JUnit tests are written with Groovy.  The only clear distinction is that the Spock tests all inherit from `Specification` while the JUnit tests use `@Test` annotations.

**Comment by wcraigtrader** [comment]
I gave up and renamed the Specifications.
