### ISSUE TITLE
UnnecessaryGetter false positive

### ISSUE THREAD

**Issue by mkordas** [CodeNarc/CodeNarc#165]
For the following code
```groovy
class Spec extends Specification {

    private final field = 'field'

    def test() {
        expect:
        field == 'field'
        getField() == 'getField'
    }

    private static String getField() {
        'getField'
    }
}
```
Codenarc says
```
[UnnecessaryGetter] Violation in class Spec. getField() can probably be rewritten as field 
```

It is false positive, as changing `getField()` invocation to `field` changes behavior of code (and test does not pass anymore).

**Comment by chrismair** [comment]
Interesting. Yeah, I guess the special case here is that there is an instance field with the same name as the static _property_.
