### ISSUE TITLE
Idea for a new rule: Gstring without ${}

### ISSUE THREAD

**Issue by msaladin** [CodeNarc/CodeNarc#171]
It seems to be good practice to use single-quotes when you don't have any interpolation, and double-quotes when you have interpolation. Like this:
`def stringWithoutInter = 'This is my dummy string'`
`def stringWithInter = "This is my ${dummy.name}"`

But would it be nice only to have double-quotes in the source when there is really an interpolation, and otherwise use only single quotes. So this would be a violation:
`def stringWithoutInter="This is another dummy string with no interpolation. A violation, because single quotes would suffice"`

Would such a rule make sense?
It would at least be a good-practice pattern, maybe it would even make the execution slightly faster because the Groovy interpreter then does not need to handle GStrings when not necessary?

**Comment by erdi** [comment]
There already is a rule that fulfils your requirements, it's called `UnnecessaryGString`.

As a side note, groovy compiler is smart enough not to create `GString`s when it processes a double-quoted strings that do not contain any interpolated variables and creates `String` instances in that case. So it's all about style and not performance.
