### ISSUE TITLE
No such rule named [NoTabCharacter]

### ISSUE THREAD

**Issue by twcrone** [CodeNarc/CodeNarc#173]
I'm getting this error when I try to include NoTabCharacter using 0.25.2

No sure if it is technically an "issue" but would love to know where to post or ask.

Thanks!

**Comment by twcrone** [comment]
Perhaps related [TrailingComma] also seems to be unavailable

**Comment by chrismair** [comment]
Can you show your ruleset and also the error message you are getting?

**Comment by chrismair** [comment]
If this remains an issue, please reopen
