### ISSUE TITLE
DuplicateNumberLiteral - groovy enum

### ISSUE THREAD

**Issue by borcherspm** [CodeNarc/CodeNarc#174]
I have an enum that keeps failing for the DuplicateNumberLiteral and I'm not sure why.  

line 22 fails for DuplicateNumberLiteral.  src=AP(15L) msg=Duplicate Number Literal: 15

```groovy
package com.nyiso.irs.common.enums

enum BasicEnum{
	AA(318L),
	AB(319L),
	AC(320L),

	AD(321L),
	AE(322L),
	AF(323L),

	AG(324L),
	AH(325L),
	AI(326L),
	AJ(327L),
	AK(328L),
	AL(329L),
	AM(330L),
	AN(331L),
	AO(332L),

	AP(15L)

	final Long id

	private BasicEnum(Long id) {
		this.id = id
	}
}
```

**Comment by chrismair** [comment]
I was able to reproduce this problem. I suspect it may have something to do with the Enum and generated classes. I'll take a look.
