### ISSUE TITLE
UnusedPrivateMethodRule to skip method with @PostConstruct annotation

### ISSUE THREAD

**Issue by ychulovskyy** [CodeNarc/CodeNarc#179]
The problem is that we have test with Spring context.
We use methods like:
````
@PostConstruct
private void init() {
    myService.init()
}
````
to init some values before tests.
It causes violation since CodeNarc doesn't know about Spring annotations.

Is it possible to ignore methods with @PostConstruct annotations?
Or add property to the rule to ignore methods with a name or with an annotation?

Please respond what implementation is OK with you.
I can implement it.

**Comment by chrismair** [comment]
I would be fine with a `boolean ignoreMethodsWithAnnotations` property, that caused the rule to ignore all private methods with any annotations.

OR, if you prefer, a `String ignoreMethodsWithAnnotationNames` property, where you could specify one or more annotation names with wildcards (like UnusedPrivateField _ignoreFieldNames_).

Thanks.

**Comment by ychulovskyy** [comment]
Resolved and merged into master. Milestone 0.27.0.
