### ISSUE TITLE
UnusedVariable rule does not work correctly for cucumber

### ISSUE THREAD

**Issue by modestukasai** [CodeNarc/CodeNarc#182]
Hi,
Below code does not work with UnusedVariable rule. It shows that myVar is unused.
Codenarc version v0.26.0

> [SRC]@Field String myVar
[MSG]The variable [myVar] in class com.xxxx.None is not used

` 
import cucumber.api.groovy.EN
import groovy.transform.Field

import static cucumber.api.groovy.Hooks.Before

metaClass.mixin(EN)

@Field String myVar

Before {
    doStuff()
}

private void doStuff() {
    myVar = '50'
}
`

**Comment by chrismair** [comment]
Fixed for CodeNarc 0.27.

**UnusedVariableRule** now ignores variables in Scripts annotated with @Field.
