### ISSUE TITLE
VariableName rule should only check static final fields for all caps

### ISSUE THREAD

**Issue by dchesterman** [CodeNarc/CodeNarc#190]
I believe Java conventions state that constants are defined as static final fields.  I don't see anything defined separate that that for Groovy.  Final fields are best practice in concurrent programming as well as defining immutable objects.  These fields are certainly not constants and would look quite ridiculous in all caps I'm sure :)  Can we change VariableName to only apply the contants name format to static final fields?

**Comment by chrismair** [comment]
The **VariableName** rule is for variables, not field names. The **FieldName** rule covers field names, and does not specify all caps for non-static final field names.
