### ISSUE TITLE
Nodef should not apply to comments

### ISSUE THREAD

**Issue by jlstrater** [CodeNarc/CodeNarc#195]
It appears the nodef rule still applies even if the code is commented out. :( See attached screenshot

<img width="683" alt="screen shot 2017-03-24 at 8 11 33 pm" src="https://cloud.githubusercontent.com/assets/4601577/24309935/1fa4db7a-10ce-11e7-9882-3f297337d899.png">

**Comment by chrismair** [comment]
Fixed by #205
