### ISSUE TITLE
Consider switching from log4j to slf4j

### ISSUE THREAD

**Issue by mkobit** [CodeNarc/CodeNarc#203]
CodeNarc has a dependency on [`log4j:log4j:1.2.14`](https://github.com/CodeNarc/CodeNarc/blob/master/build.gradle#L25). This forces library consumers to take on a logging implementation themselves when they may want to provide their own.

It would be useful for consumers to swap out the current usage of log4j and replace it with slf4j.

**Comment by erdi** [comment]
While there is a point in your suggestion this would be a breaking change and a lot of work for relatively little benefit (it's "just logging" in the end).

There is a simple workaround for you as a consumer though, so if you feel really strongly about it I would suggest you use [`log4j-over-slf4j`](https://www.slf4j.org/legacy.html#log4j-over-slf4j).

**Comment by mkobit** [comment]
Thanks for the quick response! Good suggestion with using `log4j-over-slf4j`, that will probably be what I move to do.

I agree that it is a breaking change that does not offer much benefit (in the near term at least) and would almost certainly introduce a bunch of problems for existing consumers.

Going to close this since I think the workaround you provided is a good approach. This may be a change to consider somewhere down the line, but not worth pursuing right now due to the reasons you brought up.

**Comment by chrismair** [comment]
Other issues have been opened re: CodeNarc and Log4J 1.x: #211 and #214 .

I understand that the dependency on Log4J 1.x gets more problematic, or at least annoying, as we get farther and farther beyond its end-of-life. I am open to upgrading to either Log4J 2.x or to [SLF4J](https://www.slf4j.org/).

I am leaning toward SLF4J. Any other considerations or strong opinions?

**Comment by erdi** [comment]
I'm in favour of going with SLF4J because with it you write your logging code against a simple, clearly defined API and let your consumers plug in logging implementation of their choice.

**Comment by M-r-A** [comment]
Hmm... If SLF4J allow me to plug in LOG4J 2.x, why not?
And i want the same thing with GMetrics, like in https://github.com/thetric/gmetrics by @thetric. 
Also, it is possible to recheck and update other dependencies in both projects in process of upgrade.
Can you, @chrismair?

**Comment by chrismair** [comment]
I have added a GMetrics issue to switch to SLF4J:
https://sourceforge.net/p/gmetrics/feature-requests/34/

Are there specific other dependencies you think need to be updated?

**Comment by Fedos86** [comment]
It's very good idea to use SLF4J.

**Comment by M-r-A** [comment]
@chrismair
Gradle 4.0 -> 4.0.2
Groovy version 2.1.8 -> 2.4.12

**Comment by mkobit** [comment]
I don't want to piggyback on this too much, but in regards to the GMetrics dependency upgrades it would nice to remove the dynamic version ranges.

When using Gradle at least, the easiest way to leverage CodeNarc is by using the `codenarc` plugin. But, getting it to use the same Groovy version you are developing with your code requires a little bit of extra work.

You see something like:

```
codenarc - The CodeNarc libraries to be used for this project.
\--- org.codenarc:CodeNarc:0.27.0
     +--- org.gmetrics:GMetrics:0.7
     |    +--- org.codehaus.groovy:groovy:[2.1.0,) -> 2.5.0-beta-1
     |    +--- org.codehaus.groovy:groovy-xml:[2.1.0,) -> 2.5.0-beta-1
     |    |    \--- org.codehaus.groovy:groovy:2.5.0-beta-1
     |    \--- org.codehaus.groovy:groovy-ant:[2.1.0,) -> 2.5.0-beta-1
     |         +--- org.codehaus.groovy:groovy:2.5.0-beta-1
     |         +--- org.codehaus.groovy:groovy-groovydoc:2.5.0-beta-1
     |         |    +--- org.codehaus.groovy:groovy:2.5.0-beta-1
     |         |    \--- org.codehaus.groovy:groovy-templates:2.5.0-beta-1
     |         |         +--- org.codehaus.groovy:groovy:2.5.0-beta-1
     |         |         \--- org.codehaus.groovy:groovy-xml:2.5.0-beta-1 (*)
     |         +--- org.apache.ant:ant-junit:1.9.9
     |         \--- org.apache.ant:ant-antlr:1.9.9
     +--- junit:junit:4.8.1
     +--- org.codehaus.groovy:groovy-ant:2.1.8 -> 2.5.0-beta-1 (*)
     +--- org.codehaus.groovy:groovy-xml:2.1.8 -> 2.5.0-beta-1 (*)
     \--- org.codehaus.groovy:groovy:2.1.8 -> 2.5.0-beta-1
```

`2.5.0-beta-1` was when I wrote that gist, but the problem still exists. 
I wrote up https://gist.github.com/mkobit/6ff2aee426c895c8d8b926d936941dcb because I kept forgetting how to do it.

It would be useful if that dependency was pinned as well.

**Comment by chrismair** [comment]
@mkobit 
Okay, I can remove the dynamic version ranges in GMetrics. I'm planning to convert that to Gradle.

@M-r-A 
I do not understand the importance of those minor version upgrades? If you want to use a later version of those, can't you just specify those yourself, and override what is configured for CodeNarc?

**Comment by M-r-A** [comment]
Listed them FYI, because i want the next version of CodeNarc with up-to-date libs :)

**Comment by chrismair** [comment]
I have migrated the GMetrics code from Sourceforge to GitHub, and switched from Log4J to SLF4J. You can see the new dependencies in the *build.gradle* at:
https://github.com/dx42/gmetrics

**Comment by chrismair** [comment]
CodeNarc has switched from Log4J to SLF4J in v1.0.
