### ISSUE TITLE
ParameterCount should ignore methods with @Override annotation

### ISSUE THREAD

**Issue by ychulovskyy** [CodeNarc/CodeNarc#207]
Problem:
Sometimes we have to use 3rd party library that has method with many parameters.
We don't want to increase maxParameters and don't want to ignore the rule in many classes.

Possible solution:
add ignoreOverriddenMethods parameter to ignore methods with @Override annotation?

Checkstyle already has such feature http://checkstyle.sourceforge.net/config_sizes.html#ParameterNumber
I can prepare pull request if you approve the feature.

**Comment by chrismair** [comment]
I like that. Sounds good.

**Comment by ychulovskyy** [comment]
@chrismair shall we close the issue?

**Comment by chrismair** [comment]
yes, thanks.
