### ISSUE TITLE
Running CodeNarc is not compatible with Log4j 2

### ISSUE THREAD

**Issue by Fedos86** [CodeNarc/CodeNarc#214]
I tried to run _CodeNarc_ with latest _Log4j_ and received the following exception:
`java.lang.NoClassDefFoundError: org/apache/log4j/Logger
        at org.codenarc.report.AbstractReportWriter.<clinit>(AbstractReportWriter.groovy:43)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        ....   `
This is due to the big differences between _Log4j 1.x_ and  _Log4j 2.x_. `org.apache.log4j`  was renamed to `org.apache.logging.log4j`. Here is [a way to migrate](https://logging.apache.org/log4j/2.0/manual/migration.html). With old versions everything is fine. 
The issue was found in conjunction with @M-r-A

**Comment by chrismair** [comment]
Please see the discussion in #203, and contribute to that discussion.

**Comment by chrismair** [comment]
CodeNarc 1.0 switches to SLF4J instead of Log4J
