### ISSUE TITLE
New rule: UnnecessarySetter

### ISSUE THREAD

**Issue by ychulovskyy** [CodeNarc/CodeNarc#215]
There is http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryGetter rule.
What about adding UnnecessarySetter?
What is more readable in the following example, setter or assigning?
````
        SimpleDateFormat sdf = new SimpleDateFormat()
        sdf.setTimeZone(TimeZone.getTimeZone("GMT"))
        sdf.timeZone = TimeZone.getTimeZone("GMT")
````
Requirement can be the same as for UnnecessaryGetter but contain "set" instead of "get".
I can implement the rule.
Please let me know if you approve the new rule.

**Comment by chrismair** [comment]
Yes, that sounds reasonable and consistent.

**Comment by ychulovskyy** [comment]
Closed as implemented https://github.com/CodeNarc/CodeNarc/pull/220
