### ISSUE TITLE
Move test infrastructure under src/test/groovy

### ISSUE THREAD

**Issue by chrismair** [CodeNarc/CodeNarc#216]
Move the test infrastructure under **src/test/groovy**. Then make JUnit jar a *testCompile* dependency. This is a breaking change if consumers rely on `AbstractRuleTestCase` or `AbstractTestCase`.

**Comment by erdi** [comment]
Can we please reconsider and make sure that `AbstractRuleTestCase` is still available to consumers of CodeNarc? It's a life saver when testing custom rules that one does not want to contribute back to the tool as they are not generic enough for others to benefit from.

Also note, that these classes [were purposely moved from test source set to where they currently are to make them available to custom CodeNarc rule authors](https://github.com/CodeNarc/CodeNarc/commit/c9c16d51e97330abe3505f0e6fcd2e93350cd94c).

If the goal is to get rid of dependency on JUnit from core (which has my utmost support) I would suggest creating a new module, `CodeNarc-test`, and publishing it on Maven Central. I'm more than happy to contribute a PR with the necessary changes that would enable it. It would still be a slight breaking change but a small price to pay for a cleaner classpath.

**Comment by chrismair** [comment]
Yeah, I was conflicted about this. And yes, my main motivation was to clean up the dependencies.

I am open to leaving that in the jar. I guess one other option is to declare the JUnit dependency as *compileOnly* and then just document that it is required if you use the test framework. That would be simpler, from an implementation and maintenance perspective. Are you okay with that?

**Comment by erdi** [comment]
I'm totally fine with JUnit becoming a compile only dependency. Whatever
prevents me from having to reinvent the wheel, I mean reimplement
AbstractRuleTestCase, is fine by me.

**Comment by chrismair** [comment]
Opened #222 to cover changing JUnit jar to a *compileOnly* dependency.
