### ISSUE TITLE
UnnecessaryPublicModifier not working with generics in Groovy

### ISSUE THREAD

**Issue by travismcchesney** [CodeNarc/CodeNarc#221]
I hope I'm not overlooking something here, but I have a method in Groovy that contains generic declarations, and it's being flagged by the `UnnecessaryPublicModifier`, even though that rule explicitly states that is excludes those declarations that include generics.

```
[SRC]public <T> T readValue(String value, Class<T> valueType) {
[MSG]The public keyword is unnecessary for methods
```

Does this seem right? Is there any additional information I can provide to help understand why this might have been flagged?

**Comment by erdi** [comment]
That rule ignores generic methods for me. Which CodeNarc version are you on?

**Comment by travismcchesney** [comment]
@erdi I'm just using it as a Gradle plugin (`id 'codenarc'`), as outlined here: https://docs.gradle.org/3.3/userguide/codenarc_plugin.html

I confess, I don't know what version that brings in. Is there a way to specify a version while using that plugin syntax?

**Comment by erdi** [comment]
Yes, there is:

    codenarc {
        toolVersion = "0.27.0"
    }

**Comment by travismcchesney** [comment]
:boom: That did it, @erdi ! Thanks so much for the quick responses.
