### ISSUE TITLE
Remove deprecated classes and methods

### ISSUE THREAD

**Issue by chrismair** [CodeNarc/CodeNarc#227]
Remove deprecated classes and methods, including: 
      * The **AbcComplexity** rule (use the **AbcMetric** rule instead) 
      * The **GrailsSessionReference** rule 
      * `DirectorySourceAnalyzer`
      * `AbstractAstVisitor.addViolation(ASTNode)`
      * `AbstractRule.createViolation(Integer)`
      * `AbstractRule.createViolation(Integer, String)`
      * `AbstractRule.createViolation(SourceCode, ASTNode)`
      * `AbstractRule.createViolationForImport(SourceCode, ImportNode)`
      * CodeNarc Ant Task - \<report\> element: *toFile* and *title* attributes (remove *title* and *toFile* properties from the `org.codenarc.ant.Report` class)

**Comment by chrismair** [comment]
Implemented for CodeNarc 1.0

**Comment by agoodspeed** [comment]
You might be interested to know that removing AbstractRule.createViolation(SourceCode, ASTNode) broke your MyStaticFieldRule example at http://codenarc.sourceforge.net/codenarc-creating-rule.html. That had me running around in circles for a while.

**Comment by chrismair** [comment]
Ooops. Sorry about that. I'll make a note to fix that doc. Thanks.

**Comment by chrismair** [comment]
FYI, I have fixed the online docs to remove references to obsolete createViolation() and addViolation() methods. #277.
