### ISSUE TITLE
UnnecessaryGetter false positive

### ISSUE THREAD

**Issue by boris-petrov** [CodeNarc/CodeNarc#235]
I'm using Spock for tests and it has the ability to Mock stuff like so:

```groovy
def someMock = Mock(MyType) {
    getSomeData() >> 'some-data'
}
```

This will return an object which when you call `getSomeData` on, it will return you `some-data`. This causes CodeNarc to output a `UnnecessaryGetter` warning, however it should not - as writing `someData >> 'some-data'` is invalid syntax.

**Comment by chrismair** [comment]
Spock's cool syntax does cause some challenges for CodeNarc analysis of the Groovy AST. Unfortunately, as we've found in some other CodeNarc rules, there is no easy/consistent way to disable or skip rules for Spock classes by name because they do not follow a standard naming convention. But if your Spock classes do follow a naming convention, then you can use the `doNotApplyToClassNames` rule property as a workaround.

**Comment by boris-petrov** [comment]
I see. Isn't it possible to somehow ignore this specific rule for the `Mock` and `Stub` classes of Spock? Not sure even if my question makes sense. :) Unfortunately I cannot use your workaround. So I'll leave the check off until you (hopefully soon) figure it out. :) Thanks for the great tool!

**Comment by chrismair** [comment]
Interesting idea. That may be technically possible. I'm wondering if it is worth the "tax" (added complexity on that rule + performance impact, however small, on *everyone* from that extra logic and record-keeping), for a Spock-specific edge case. I'd be interested to hear if there are others encountering this and how widespread.

**Comment by boris-petrov** [comment]
Well, I would guess that around 74% of the people that use Groovy use it with Spock, so the performance impact should not be considered as a show-stopper. :)

By the way, another connected issue with this one is the following code:

```groovy
	private stubSomeClass() {
		Stub(SomeClass) {
			equals(_) >> { other -> this.is(other) }
		}
	}
```

This gives a `ExplicitCallToEqualsMethod` warning. :)

**Comment by chrismair** [comment]
Split off separate #338 issue for *ExplicitCallToEqualsMethod: Incorrect violation if within Spock Stub/Mock* .

Closing this issue, since the original problem has been resolved.
