### ISSUE TITLE
CLI not finding rulesetfiles

### ISSUE THREAD

**Issue by edupo** [CodeNarc/CodeNarc#237]
I'm creating a Docker container for codenarc:
https://hub.docker.com/r/edupo/codenarc/
https://github.com/edupo/docker-codenarc

I embed the starter ruleset file in the container:
```
RUN cd /opt/CodeNarc-$CODENARC_VERSION; \
    wget http://codenarc.sourceforge.net/StarterRuleSet-AllRulesByCategory.groovy.txt \
    -O all.groovy
```

But when I run it using that ruleset is telling me is not able to find it.
```
docker run --rm -v `pwd`/test:/ws -u `id -u`:`id -g` edupo/codenarc -rulesetfiles=all.groovy
[main] INFO org.codenarc.ruleregistry.PropertiesFileRuleRegistry - Loaded properties file in 33ms; 348 rules
[main] INFO org.codenarc.ruleset.GroovyDslRuleSet - Loading ruleset from [all.groovy]
ERROR: File [all.groovy] does not exist or is not accessible
java.io.FileNotFoundException: File [all.groovy] does not exist or is not accessible
...
```
I've already tried to put the file on a `rulesets` folder. And checked the permissions and no problem with them.

CodeNarc reference sais about the `-rulesetfile`:

> The path to the Groovy or XML RuleSet definition files,  relative to the classpath. This can be a single file path, or multiple  paths separated by commas. Defaults to "rulesets/basic.xml".

But still is not clear for me where that groovy file should exist.

Another question: Is it possible to use a ruleset file from the working directory? As in other similar tools that is useful to define a ruleset per project.

**Comment by chrismair** [comment]
You can also specify a relative or absolute filesystem path if prefixed with “file:”, e.g. 
```
-rulesetfiles=file:all.groovy
```
I will update the online doc to add info about that.

**Comment by edupo** [comment]
Noted in container readme. Closing issue.

Great project, thanks!
