### ISSUE TITLE
JUnit* rules are not compatible with JUnit5

### ISSUE THREAD

**Issue by ychulovskyy** [CodeNarc/CodeNarc#244]
JUnit rules shows a lot of false positives for JUnit 5 because annotation names are different.
1. Rule=JUnitPublicNonTestMethod has false positive "Violation in class <class name>. The method setup is public but not a test method" because there is @BeforeEach annotation above a method instead of @Before
2. Rule=JUnitSetUpCallsSuper has false positive "Violation in class <class name>. The method setUp() does not call super.setUp()" because there is @BeforeEach annotation above a method instead of @Before

Those are just examples.
We can use http://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4-tips as reference.
I can work on this if you approve the change.

**Comment by chrismair** [comment]
Sounds good, assuming you can keep those rules backward-compatible with JUnit 4. Thanks.

**Comment by chrismair** [comment]
I may start working on this unless someone else is intending to...

**Comment by ychulovskyy** [comment]
@chrismair I plan to work o it next week, if you don't mind

**Comment by chrismair** [comment]
Excellent. Thanks.

**Comment by ychulovskyy** [comment]
Closing as resolved
