### ISSUE TITLE
JdbcResultSetReference suppression seems not working

### ISSUE THREAD

**Issue by t-izbassar** [CodeNarc/CodeNarc#245]
I'v asked question on [StackOverflow](https://stackoverflow.com/questions/46948726/codenarc-supress-jdbcresultsetreference-seems-not-working)

Don't sure, maybe it is a bug. Thanks!

**Comment by chrismair** [comment]
I have answered the stackoverflow question as follows:

Unfortunately those rules look at import statements, and the @SuppressWarnings does not work on those.

One option is to disable that rule for your Mapper classes:
e.g. in your `codenarc.properties`:

        JdbcResultSetReference.doNotApplyToClassNames = *Mapper

or set that same property on the rule in your ruleset file.

**Comment by t-izbassar** [comment]
Yes, I've done exclusions. So there is no way to suppress import statements checks?

**Comment by chrismair** [comment]
Not currently, no.

**Comment by chrismair** [comment]
FYI... #268 enables @SuppressWarnings on imports. That will be available in CodeNarc 1.1.
