### ISSUE TITLE
Command line interface assumes that ReportWriter has title property

### ISSUE THREAD

**Issue by Codo3** [CodeNarc/CodeNarc#246]
The command line interface in org.codenarc.CodeNarc unconditionally sets a "title" property in a ReportWriter, but the interface does not contain such a property. This is done in the execute method.

Either change the method so it works as documented with any implementation of the ReportWriter interface, or extend the interface with a setTitle() method.

**Comment by chrismair** [comment]
Fixed for the next version of CodeNarc (1.1).

#246: CodeNarc command-line runner: Only set *title* property on *ReportWriters* that support it.

Thanks for the feedback.
