### ISSUE TITLE
TrailingComma regression in 1.0

### ISSUE THREAD

**Issue by M-r-A** [CodeNarc/CodeNarc#252]
There is a regression in TrailingComma rule.

Test.groovy:
```
this.testMethod param1: 1,
    param2: 2

void testMethod(Map<String, Object> map) {
    println(map)
}

```
Codenarc v.0.27: TrailingComma on line 1.
Codenarc v.1.0: nothing.

**Comment by chrismair** [comment]
That rule is intended to check for List and Map literals, not method parameters. Perhaps that is a subtle distinction.

The CodeNarc 1.0 release included #198, which "fix false positive for trailing comma when sending method parameters by name" which is what changed or fixed that behavior (depending on your preference).
