### ISSUE TITLE
Add enhanced mode for JUnitPublicField rule

### ISSUE THREAD

**Issue by erdi** [CodeNarc/CodeNarc#256]
So that it does not report violations for code like:

    @org.junit.Rule
    public RestoreSystemProperties restoreSystemProperties = new RestoreSystemProperties()

**Comment by chrismair** [comment]
The support for skipping fields with `@Rule` and `@ClassRule` annotations was already in there (see #354).

I added support for fully-qualified `@org.junit.Rule` and `@org.junit.ClassRule`.

Note: This did not require adding enhanced mode support.
