### ISSUE TITLE
Add enhanced mode for AbstractClassWithoutAbstractMethod rule

### ISSUE THREAD

**Issue by erdi** [CodeNarc/CodeNarc#257]
So that it does not report violations when creating an abstract class which extends from other abstract class but does not add any new abstract methods.

**Comment by chrismair** [comment]
Available for CodeNarc 1.5.

Added *enhanced* mode for **AbstractClassWithoutAbstractMethod** rule. No violation if abstract class extends abstract superclass, when run in *enhanced* mode.
