### ISSUE TITLE
Rule for checking indentation

### ISSUE THREAD

**Issue by nre-ableton** [CodeNarc/CodeNarc#271]
I am really surprised that CodeNarc lacks support for checking indentation. It really makes this tool *much* less useful for verifying Groovy code on CI.

See also: https://sourceforge.net/p/codenarc/feature-requests/418/

**Comment by chrismair** [comment]
Comprehensive and consistent checking of indentation is not as simple as it may seem at first, though of course it is technically possible. Pull requests are welcome! :)

**Comment by chrismair** [comment]
When I have considered this before, it seemed like it would be necessary to develop almost a full Groovy language parser, to get comprehensive checking, including edge cases. Not only would that be challenging (a lot of work), but then it would be necessary to keep that in sync with Groovy syntax and language constructs.

I wonder if there would be sufficient value in producing a *partial* solution that could take advantage of the existing Groovy AST, and check indentation for class declarations, method declarations and fields, and perhaps some other pieces. The AST definitely has some limitations and quirks, and of course that ignores comments, so they would not be covered at all. Hmmmm.

**Comment by nre-ableton** [comment]
Thanks for the clarification! I understand that this is not the most trivial feature to implement, however even basic indentation checks would be nice to have. I've done a fair bit of googling trying to find a tool that can check formatting of Groovy code, and as far as I know there isn't one (but please correct me if I'm wrong).

If it's possible to do basic indentation checks (such as enforcing 4-spaces, braces on same line, etc), then that would be very cool to have in CodeNarc. But if it's too difficult to implement this, I would suggest closing this issue as wontfix but then documenting it accordingly in CodeNarc to be clear about the limitations and scope of the tool.

**Comment by chrismair** [comment]
CodeNarc does include rules that check for braces on the same line, e.g. the **BracesForClass** rule:
http://codenarc.sourceforge.net/codenarc-rules-formatting.html

**Comment by chrismair** [comment]
I have checked in a new **Indentation** rule. It is somewhat limited, but does basic checking for class/method/field declarations and statements within methods (1st line only). And it only supports spaces (not tabs). It is by no means comprehensive, but I think what is there provides a decent amount of value. I will be using it on my own projects at work.

Available with **CodeNarc** v1.1 release.

**Comment by nre-ableton** [comment]
@chrismair That's wonderful, thanks! I'm looking forward to giving it a spin in 1.1.
