### ISSUE TITLE
[Feature request] Unneeded toString call

### ISSUE THREAD

**Issue by boris-petrov** [CodeNarc/CodeNarc#273]
```groovy
Object object = 1
def string = 'some string' + object.toString()
```

There is no need for the `toString` call. It would be nice to have such a check.

**Comment by boris-petrov** [comment]
Another case that must be handled is in string interpolation:

```groovy
Object object = 1
def string = "some string${object.toString()}"
```

**Comment by chrismair** [comment]
Fixed for both scenarios above. There are still some limitations  with less obvious cases. For instance, it will not catch 

 `def string = 'some string' + somethingElse + object.toString()`
OR
`def string = "processing: ${object1 + object2.toString()}"`
