### ISSUE TITLE
New WhitespaceOnlyLine rule

### ISSUE THREAD

**Issue by chrismair** [CodeNarc/CodeNarc#274]
Create a new **WhitespaceOnlyLine** rule that checks for source lines that contain only whitespace (spaces, tabs) before the newline.

**Comment by erdi** [comment]
You might want to know that lines like that will already be caught by `TrailingWhitespace` rule.

**Comment by chrismair** [comment]
Ahhh, yes, I should have known that!

I enabled that rule in CodeNarc and cleaned up the project source files. And then I spent a couple hours trying to figure out why that wasn't catching all the files with extra trailing spaces for my code at work. WTF!? Then I realized that it was the Windows line endings for my work stuff. I have fixed that rule to also support Windows line endings. #279.
