### ISSUE TITLE
Use generics (GenericAbstractRuleTestCase) in all Rule tests

### ISSUE THREAD

**Issue by chrismair** [CodeNarc/CodeNarc#280]
Use generics (`GenericAbstractRuleTestCase`) in all Rule tests for better type-safety, self-documentation and IDE completion.

Perhaps collapse `GenericAbstractRuleTestCase` back into `AbstractRuleTestCase`.

**Comment by erdi** [comment]
FYI, I'm picking this up.

**Comment by chrismair** [comment]
Excellent. Thanks.

**Comment by chrismair** [comment]
Oh, please include updating **templates/Test.groovy** as appropiate.

**Comment by chrismair** [comment]
Available with CodeNarc 1.1
