### ISSUE TITLE
Add support for `ignore` list

### ISSUE THREAD

**Issue by tmysik** [CodeNarc/CodeNarc#282]
For existing project, if one wants to start using CodeNarc, it is quite difficult because usually, there is a lot of existing violations against the rule sets and it is not easily possible to fix them first (about ~50k violations of all priorities in our case). So, in such a case, it would be very useful to be able to add these existing violations to some ignore list and report only **new** violations. The steps then would be quite simple:

* run ConeNarc for the 1st time with XML report
* save this report as our initial ignore list
* run CodeNarc again with our ignore list (e.g. `-ignorefile=<the-original-xml-report>`)

-> only new violations would be reported.

Thanks!

**Comment by erdi** [comment]
Isn't http://codenarc.sourceforge.net/codenarc-BaselineXmlReportWriter.html what you're looking for?

**Comment by tmysik** [comment]
I see, thanks! Yes, this seems to be like what I wanted but - this cannot be used from command line directly, right? Only with Ant? Or am I missing something? Thanks a lot.

**Comment by chrismair** [comment]
Correct, that is currently only supported on the Ant task.

**Comment by tmysik** [comment]
Thank you. So, I will leave this ticket open, I can imagine that it would be useful also for the CLI interface.

**Comment by chrismair** [comment]
That seems reasonable.

**Comment by tmysik** [comment]
One note to the *baseline* functionality: I generated baseline file for our project (about 16 MB ;) but if I use it later for a test run, I still get some violations even if there should be none. I needed to disable 2 specific rules [1] to be able to pass the test. I know that it is beta quality now but still - should I report it?

Thank you.
[1]
```properties
DuplicateStringLiteral.enabled=false
UnnecessaryGString.enabled=false
```

**Comment by chrismair** [comment]
Yes, please do create an issue for that. But we'll probably need more details. That facility uses some heuristics to try to match up original violations with new ones, and that may not always be sophisticated enough, and may produce some _false negatives_ or _false positives_.

Did the code change between the original generation of that baseline file and the new CodeNarc run, especially for the file(s) where the unexpected violations occurred?

**Comment by tmysik** [comment]
@chrismair No, the source code did not change. Reported as issue #303, hope it helps.

Thanks!

**Comment by chrismair** [comment]
#303 was fixed and closed.

**Comment by UlrichEckhardt** [comment]
Just as an estimate, is it difficult to implement the CLI for the baselining? We're running CodeNarc from a Docker container, not from Ant, so that would be convenient for us. If it isn't too complex, I would give it a shot myself, though I'm a Groovy beginner myself.

**Comment by chrismair** [comment]
Okay, I'll take a look. Thanks.

**Comment by UlrichEckhardt** [comment]
I think this can now be closed, can't it?
