### ISSUE TITLE
New rules to enforce specifying type for fields, method return types, parameters and variables

### ISSUE THREAD

**Issue by chrismair** [CodeNarc/CodeNarc#290]
New rules to enforce specifying type for fields, method return types, parameters and variables. Checks for omitted type or use of def placeholder.

Proposed rule names:
 * FieldTypeRequired
 * MethodReturnTypeRequired
 * MethodParameterTypeRequired
 * VariableTypeRequired

**Comment by erdi** [comment]
Would you like me to adjust #289 and #286 to be in line with your proposed naming?

**Comment by chrismair** [comment]
Wow! This is quite a coincidence. I did not see your issues/pull-requests when I created the above. Sorry for the overlap.

I do prefer my names (above), but it is not a strong preference. Do you have a strong opinion? In any case, thanks for offering.

**Comment by erdi** [comment]
Indeed, it's massive a coincidence. I had these rules implemented in my project for some time now and I'm just lifting them as a contribution.

I will go with your names as they seem better. I'll update my PR branches and force push after I'm done with the PR for `BlockEndsWithBlankLine` I'm currently working on.

**Comment by erdi** [comment]
I've updated rule names in #289 and #286.

**Comment by chrismair** [comment]
Marcin (erdi) has implemented MethodReturnTypeRequired (#286) and MethodParameterTypeRequired (#289).

I am still planning to implement these new rules:
 * FieldTypeRequired
 * VariableTypeRequired
