### ISSUE TITLE
MethodName regex/ignoreMethodNames cannot be used for Spock method names

### ISSUE THREAD

**Issue by tmysik** [CodeNarc/CodeNarc#302]
Maybe I am doing it wrong, but I am not able to configure [`MethodName`](http://codenarc.sourceforge.net/codenarc-rules-naming.html#MethodName) rule properly; I want to check 2 types of method names:

* common methods, like `doSomething()`
* Spock methods, like `'Should pass'` or `"Should fail"` (please note the quotes and apostrophes)

I tried 2 configurations in `codenarc.properties`, none of them seems to work:

1. `MethodName.ignoreMethodNames="*",'*'`
1. `MethodName.regex=[a-z]w*|["'].+["']`

The problem seems to be that the quotes/apostrophes are not part of the method names so there is no (easy) way to define a rule for them.

BTW, there is a typo in the `regex` documentation - extra space (` `) in the default value. Also, the `/` characters used in regex-es are quite confusing - should they be present in the `codenarc.properties` file or not? From the documentation, I would guess so but they should not, right?

Thank you.

**Comment by chrismair** [comment]
The quotes or double-quotes are not part of the method names in the Groovy AST, so those characters will not be part of the regular expression. Just ignore them when building your regex.

I'll make a note to fix the documentation for that rule. I can see your point that the / character is confusing. I'll remove those. And the extra space in the `regex` is because the forward slash did not show up. It should be `/[a-z]\w*/`. I should be able to fix that as well.

**Comment by tmysik** [comment]
Thanks for the info. Unfortunately, in such a case, `MethodName` rule is not usable if one uses Spock. Perhaps some Spock-specific rules could help here, not sure.

Feel free to close this issue, thank you.

**Comment by erdi** [comment]
Tomáš, why don’t you disable the rule for file names ending with Spec
(assuming you’re using the conventional class suffix for specifications) or
change the regexp to match any methods with a space in it?

**Comment by tmysik** [comment]
@erdi 

Unfortunately, we use `*Test` suffix and we have not only Spock tests but also JUnit tests (historical reasons). Also, adding just a space is not enough - the method name can be e.g. "Should pass for #number" etc.

Thanks.

**Comment by erdi** [comment]
So what exactly is stopping you from crafting a more sophisticated regular
expression that would much something like "Should pass for #number"?

**Comment by tmysik** [comment]
@erdi 

I am not sure I understand what you mean - can you advice? Because I do not see any possibility how to distinguish normal method (the default regex) and basically anything [1] (method names in tests).

Thank you.
[1] Some examples of our test method names:
`predictTranslationForSegments() call without RoboTranslator engine`
`proper exception for #status`
`Should read priceList from file`
`operation #number1 >= #number2`

**Comment by erdi** [comment]
What I meant is basically using a regular expression like:

`[a-z]\w*|.*[ #].*`

It seems to match all of the examples you've given: https://regex101.com/r/ziW186/1/tests

**Comment by tmysik** [comment]
@erdi I see now, thanks a lot!

**Comment by tmysik** [comment]
BTW I guess we can close this issue now.
