### ISSUE TITLE
Baseline XML file not formatted

### ISSUE THREAD

**Issue by tmysik** [CodeNarc/CodeNarc#305]
Did not test it myself but I believe that if the Baseline XML report file was formatted then any future change in this file would be much more friendly to SCM. In our case, this XML file has around 6 MB but has only 563 lines; if we need to regenerate it (because of some newly added code which causes previously ignored violations are reported again) then the diff/patch will be much bigger than necessary. If the file was (maybe somehow specifically) formatted, only a few lines could be changed.

What do you think? Thank you.

**Comment by tmysik** [comment]
BTW one more possible use case - merge conflicts are now much more likely than it would be if the file was formatted.

Thanks.

**Comment by chrismair** [comment]
Yes, that seems like a reasonable feature to implement.

**Comment by chrismair** [comment]
Implemented for CodeNarc v1.1

**Comment by tmysik** [comment]
Great, thanks a lot!
