### ISSUE TITLE
Indentation rule has incorrect level when outer class is None

### ISSUE THREAD

**Issue by nre-ableton** [CodeNarc/CodeNarc#310]
When checking a Groovy code that is not within a class (such as a `Jenkinsfile`), CodeNarc mistakenly reports that the indentation level of everything in the file as being off by a level of one. For example:

```
[MSG]The statement on line 178 in class None is at the incorrect indent level: Expected column 5 but was 3
```

Basically, when the outer class is `None`, the indent level shouldn't be raised. BTW, thanks for adding this check!

**Comment by chrismair** [comment]
Fixed for CodeNarc v1.2

**Comment by nre-ableton** [comment]
@chrismair I think that this issue must be re-opened. I just tried out CodeNarc 1.2 and encountered the same error when running it on a groovy script (actually a `Jenkinsfile`, but same thing):

```
[MSG]The statement on line 101 in class None is at the incorrect indent level: Expected column 3 but was 1
```

Sorry, I should have tried to reproduce this error after the fix was committed to master, but I didn't get around this since I was busy with other things. If someone has time to help investigate this bug, I would be happy to help resolve it in v1.3.

**Comment by chrismair** [comment]
Okay, I was able to reproduce with this example code from #352:
```
job('job') {
    label('label')
}
```
If you have a different brief example of code that causes an incorrect violation, I can add that to the test suite as well.

**Comment by nre-ableton** [comment]
@chrismair yep, that's pretty much the exact type of code which triggers this violation. I so far haven't encountered anything else; it's just the initial indent level which is problematic. Also, 👍 to adding a test for this.

**Comment by chrismair** [comment]
I have fixed handling of indent level within scripts.

This **Indentation** rule was not intended to be a fully comprehensive check for all indentation, but rather a way to use the AST-provided information to catch the "low-hanging fruit" for a relatively easy subset of indentation checks. But it is proving to be a "slippery slope"; there are lots of variations and dark corners. And fixing one thing can expose other issues or break other scenarios. I'm sure this won't be the last issue that pops up.

**Comment by nre-ableton** [comment]
I just made a build from the `master` branch and can confirm that the fix works. Thanks @chrismair!
