### ISSUE TITLE
NestClasses declared within a condition report incorrect indentation

### ISSUE THREAD

**Issue by mahesh-subramanian** [CodeNarc/CodeNarc#313]
Hi,

I've a situation where I've to declare a nested class within a condition. However, codenarc reports an incorrect indentation error for nested methods within the inner class. For example:

```groovy
class MyClass {
    private void nestedClassUnderCondition() {
        if (true) {
            def runnable = new Runnable() {
                @Override
                void run() { }
            }
        }
    }
}
```

should not report a violation. However, codenarc reports a violation. I think this is because [IndentationRule](https://github.com/CodeNarc/CodeNarc/blob/master/src/main/groovy/org/codenarc/rule/formatting/IndentationRule.groovy#L168-L176) only checks for enclosing class and enclosing method but does not consider enclosing conditions

**Comment by chrismair** [comment]
Fixed for CodeNarc v1.2
