### ISSUE TITLE
Configuration options for VariableTypeRequired rule

### ISSUE THREAD

**Issue by nre-ableton** [CodeNarc/CodeNarc#314]
It would be nice if the VariableTypeRequired rule could be ignored either for certain class types and/or variable names. For instance, variables named `_` where the type is not known (or cared about).

**Comment by chrismair** [comment]
I have made these changes for CodeNarc v1.2:
 - VariableTypeRequired rule: Add ignoreVariableNames property
 - FieldTypeRequiredRule rule: Add ignoreFieldNames property.
