### ISSUE TITLE
codenarcMain and codenarcTest tasks fails in JAVA 9

### ISSUE THREAD

**Issue by modestukasai** [CodeNarc/CodeNarc#316]
Hi,
I get bellow error. Please see [git repository](https://github.com/modestukasai/groovy-codenarc-java-9)

I am executing `.gradlew codenarcMain` or `.gradlew codenarcTest` with java 9 compiler.

`Execution failed for task ':codenarcMain'.`
`java.lang.NoClassDefFoundError: Unable to load class groovy.xml.jaxb.JaxbGroovyMethods due to missing dependency javax/xml/bind/JAXBContext`

**Comment by chrismair** [comment]
I do not yet have a working Java 9 environment to test in, but it looks like you are using the [Gradle CodeNarc Plugin](https://docs.gradle.org/current/userguide/codenarc_plugin.html). CodeNarc does not use JAXB, so my first guess is that the issue may be associated with the plugin.

**Comment by modestukasai** [comment]
Ok,
I have added issue to [gradle team](https://github.com/gradle/gradle/issues/4219)
Let's see what they can tell.

**Comment by modestukasai** [comment]
You can --add-modules according to this post, or use following workaround:
```
dependencies {
    compile 'org.springframework.boot:spring-boot-starter'
    compile 'org.codehaus.groovy:groovy'

    testCompile "org.spockframework:spock-core:$spockVersion"
    testCompile "org.spockframework:spock-spring:$spockVersion"
    testCompile 'org.springframework.boot:spring-boot-starter-test'

    codenarc 'javax.xml.bind:jaxb-api:2.3.0', 'org.codenarc:CodeNarc:1.1' <- add this line
}
```

**Comment by chrismair** [comment]
Closing as requested.
