### ISSUE TITLE
License for site content information

### ISSUE THREAD

**Issue by fedor-chemashkin** [CodeNarc/CodeNarc#319]
What license is used for site content (images, text, examples and etc.)? Can I use content to be placed on slides at conferences or meetups?

**Comment by chrismair** [comment]
All CodeNarc content is under the Apache v2.0 license.

I am unsure about the legal restriction and copyright issues involved, and a quick Google search was little help. I have no objection to you using site content on conference slides or meetup pages.

**Comment by Fedos86** [comment]
It's great! Thank you.
