### ISSUE TITLE
Inconsistent number of errors

### ISSUE THREAD

**Issue by tmysik** [CodeNarc/CodeNarc#320]
When I run CodeNarc (or generate baseline) several times in a row (without any changes in the code base, of course), the number of errors is not consistent. Here is the output (please note that the number of `p3` errors is `29545` or `29576`):

```bash
| Environment set to development....
Generating new baseline file
 [codenarc] CodeNarc completed: (p1=0; p2=6669; p3=29545) 80787ms
| Environment set to development....
Generating new baseline file
 [codenarc] CodeNarc completed: (p1=0; p2=6669; p3=29576) 88097ms
| Environment set to development....
Generating new baseline file
 [codenarc] CodeNarc completed: (p1=0; p2=6669; p3=29576) 80107ms
| Environment set to development....
Generating new baseline file
 [codenarc] CodeNarc completed: (p1=0; p2=6669; p3=29545) 82953ms
```

The problematic rule - in our case - seems to be the `UnnecessaryPackageReference` one. The error message is `Specifying the package name is not necessary for java.lang.annotation$Annotation` which is incorrect I believe (the source file is our own annotation).

BTW I also noticed - perhaps similar - inconsistencies caused by the `MissingOverrideAnnotation` rule but a bit different - they are never part of generated baseline but reliably reported if CodeNarc is run. Also, its error message is not consistent either (please note that error message sometimes contains `.` and sometimes `$`):

```patch
---        <Message>Method 'toString' is overriding a method in 'java.lang.Enum' but is not annotated with @Override.</Message>
+++        <Message>Method 'toString' is overriding a method in 'java.lang$Enum' but is not annotated with @Override.</Message>
 ```

Please, let me know if there is something I can do to provide more information about this issue.

Thank you.

**Comment by chrismair** [comment]
Please open a separate issue for the `MissingOverrideAnnotation` problem.

**Comment by tmysik** [comment]
@chrismair 

> Please open a separate issue for the MissingOverrideAnnotation problem.

Reported as issue #321.

Thank you.

**Comment by chrismair** [comment]
This issue is puzzling. Can you provide an example of the full violation information and the source code it is complaining about (or at least an excerpt indicating line numbers). Thanks.

**Comment by tmysik** [comment]
Sorry, it is quite a long time ago. Will report it if it happens again. Thank you.
