### ISSUE TITLE
MissingOverrideAnnotation violations not part of Baseline file

### ISSUE THREAD

**Issue by tmysik** [CodeNarc/CodeNarc#321]
_Described originally in issue #320:_

There are inconsistencies caused by the `MissingOverrideAnnotation` rule - they are never part of generated baseline but reliably reported if CodeNarc is run. Also, its error message is not consistent either (please note that the error message sometimes contains `.` and sometimes `$`):

```patch
---        <Message>Method 'toString' is overriding a method in 'java.lang.Enum' but is not annotated with @Override.</Message>
+++        <Message>Method 'toString' is overriding a method in 'java.lang$Enum' but is not annotated with @Override.</Message>
 ```

In our case, this applies to some `Enum` class but unfortunately not to all of them. Not sure what is the real cause, perhaps that we have more `Enum` classes defined in one Groovy file? All of them override `toString()` method (with redundant `public` modifier).

Thank you.

**Comment by chrismair** [comment]
This issue is puzzling as well. I assume the violation is valid. Can you provide the full violation information and an excerpt of the code it is complaining about (with line numbers? Thanks,

**Comment by tmysik** [comment]
Sorry, it is quite a long time ago. Will report it if it happens again. Thank you.
