### ISSUE TITLE
`UnnecessaryGetter` incorrect behavior

### ISSUE THREAD

**Issue by mkazinauskas** [CodeNarc/CodeNarc#326]
False alarm with `UnnecessaryGetter` when checking `getLocation()` method from [https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/http/HttpHeaders.html#getLocation--](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/http/HttpHeaders.html#getLocation--)

This fails in test where below:
`response.headers.getLocation().path` is used.

**Comment by erdi** [comment]
Isn't this as expected? You are getting a violation of `UnnecessaryGetter` rule because you can use the property notation instead:

`response.headers.location.path`

**Comment by modestukasai** [comment]
GetLocation does not have property underneath. It is just method in the class...
```
    public URI getLocation() {
        String value = this.getFirst("Location");
        return value != null ? URI.create(value) : null;
    }
```

**Comment by chrismair** [comment]
My understanding is that this is still considered legitimate use of the *property syntax*, even if the target class does not have a property of that name. Just naming a zero-arg method getXxx() implies it is returning a "property".

**Comment by chrismair** [comment]
This seems to be a legitimate violation of the rule. Feel free to reopen this issue if if that is not correct.
