### ISSUE TITLE
`SpaceAfterOpeningBrace` issue

### ISSUE THREAD

**Issue by modestukasai** [CodeNarc/CodeNarc#327]
Rule `SpaceAfterOpeningBrace` fails with 
`The opening brace for class xxx is not followed by a space or whitespace` for line:

`new ParameterizedTypeReference<PageWrapper<ClientBean>>() {}`

**Comment by erdi** [comment]
If you do not wish to get violations for `SpaceAfterOpeningBrace ` rule when it encounters empty blocks  then you should set `ignoreEmptyBlock` configuration property for that rule (see http://codenarc.sourceforge.net/codenarc-configuring-rules.html and http://codenarc.sourceforge.net/codenarc-rules-formatting.html).

**Comment by modestukasai** [comment]
What do you think about making `ignoreEmptyBlock` as default?

**Comment by chrismair** [comment]
I don't have a strong opinion on the correct *polarity* of that flag, but I would lean toward keeping it the way it is, just to avoid affecting existing users and their expectations.

**Comment by chrismair** [comment]
Closing this. Feel free to reopen if you want to further discuss this issue.
