### ISSUE TITLE
`ClosureAsLastMethodParameter` issue

### ISSUE THREAD

**Issue by modestukasai** [CodeNarc/CodeNarc#328]
I get error when method is called, that it can be used without parenthesis
```
calculateSmth(Bean1 request1, Bean2 request2)

            1 * service.calculateSmth({ Bean1 request1 ->
                request1.type == MAIN  } as Bean1,
             { Bean2 request2 -> request2.type == MAIN  } as Bean2) == 0.50

Violation in class xxxx. The last parameter to the 'someMethod' method call is a closure an can appear outside the parenthesis
```

**Comment by modestukasai** [comment]
Also easy example with 
```
[].sort(false, { a, b -> a <=> b }).first()

Violation in class xxxx. The last parameter to the 'someMethod' method call is a closure an can appear outside the parenthesis
```

**Comment by chrismair** [comment]
The violation for your 2nd example is legitimate, as it could be rewritten:
`[].sort(false) { a, b -> a <=> b }.first()`

**Comment by chrismair** [comment]
I am unable to reproduce the violation for the code in the 1st example. I am using CodeNarc 1.1 with Groovy 2.3/2.4 and Java 1.8. Are you perhaps using older CodeNarc? Or is the actual code different, since I see no "someMethod" in the example?

**Comment by chrismair** [comment]
Closing. Feel free to reopen if still relevant.
