### ISSUE TITLE
UnnecessarySetter false-positive

### ISSUE THREAD

**Issue by boris-petrov** [CodeNarc/CodeNarc#333]
Any method with `set` prefix is notified. What about doing this only for methods which return `void`? This way a lot of false-positives could be fixed.

**Comment by chrismair** [comment]
That seems reasonable.

**Comment by mkordas** [comment]
@chrismair maybe you could disable this rule at least for chained code like `builder.setFirst(1).setSecond(2).build()`?

**Comment by chrismair** [comment]
Okay, a recent issue and its fix (#346) addressed this problem. As of CodeNarc 1.2, this rule will now ignore/skip any setXxx() call if it is part of another expression, so it will not flag the *builder* example, and will also ignore most *set* calls where its return value is used (in any expression).
