### ISSUE TITLE
Should BooleanMethodReturnsNullRule analyze the AST in more detail?

### ISSUE THREAD

**Issue by darxriggs** [CodeNarc/CodeNarc#34]
I was wondering if the rule should only raise a violation if the code only returns boolean values and null.

I wouldn't expect a violation for a method like below. It returns Object and the code shows clearly that different types can be returned.

    @Test
    void testDefMethodReturnsNull_NoViolation() {
        final SOURCE = '''
            def scriptMethod(clazz) {
                if (clazz == String) {
                    return 'something'
                }   
                if (clazz == Number) {
                    return 1
                }   
                if (clazz == Boolean) {
                    return true
                }   
                return null
            }   
        ''' 
        assertNoViolations(SOURCE)
    }

**Comment by chrismair** [comment]
Fixed for CodeNarc 0.23
