### ISSUE TITLE
Groovy Indentation issue 

### ISSUE THREAD

**Issue by dhudomiet** [CodeNarc/CodeNarc#352]
I am using CodeNarc v1.2 and i am getting Indentation violation when i put closure as last param outside of method.
code: 
```
job('job') {
    label('label')
}
issue:
[Indentation] The statement on line 2 in class None is at the incorrect indent level: Expected column 9 but was 5
```

**Comment by mkordas** [comment]
I confirm, https://github.com/CodeNarc/CodeNarc/issues/310 is not fully fixed in 1.2. CodeNarc still reports false positives for closures in `None` classes.

**Comment by nre-ableton** [comment]
Yes, this should be treated as a duplicate of #310.

**Comment by chrismair** [comment]
Closing as a duplicate of #310.

I have added the above code as a new test case for the **Indentation** rule.
