### ISSUE TITLE
StaticFieldsBeforeInstanceFields rule and Grails domain classes

### ISSUE THREAD

**Issue by tmysik** [CodeNarc/CodeNarc#358]
It is common that Grails domain classes define their static fields after the instance ones. Maybe this rule can have a property (like `doNotApplyToGrailsDomainClasses` or similarly), set by default to `true`.

A workaround is quite easy, just define in your CodeNarc properties something like this (applies for the property file):

```
StaticFieldsBeforeInstanceFields.doNotApplyToFilesMatching=.+/grails\\-app/domain/.+
```

Thanks.

**Comment by chrismair** [comment]
In general, we avoid adding Grails-specific (or any framework-specific) config to regular rules. Fortunately, as you pointed out, the workaround is pretty simple. Thanks.

**Comment by tmysik** [comment]
Well, I would agree in case of any other framework than Grails since CodeNarc already provides some Grails specific rules. Therefore, I would still prefer the attribute with a reasonable default value because now, the rule is by default "broken" and *every* Grails user of CodeNarc has to use this workaround (and non-Grails users would not be affected by it).

What do you think?

**Comment by jlstrater** [comment]
This is a symptom of a larger problem. We have a lot of similar issues with Spock specific syntax and some of the rules. I'm not sure yet what the solution should be. We've talked about it several times at conferences, but detecting the framework is a hard problem with the current setup of Codenarc.  And then, I don't really like the option of setting a config for each rule either. If we did go the configuration route, it would be nice to see a shared variable that all the rules can use to know it's a grails and/or spock project.

**Comment by demus-nine** [comment]
Could I suggest rule configuration templates? One for plain groovy, one for grails, one for spock, some combinations. And some support tooling to apply a usable combination. Or at least more examples on the website for various frameworks.If the tamplates include values for all properties of rules, it would also be a nice reference.

**Comment by chrismair** [comment]
Okay, as a start, I have created a page on the CodeNarc website that describes some useful rule configuration when running CodeNarc against code for the Grails and Spock frameworks:
 - [CodeNarc - Rule Configuration for Grails, Spock, etc.](https://codenarc.github.io/CodeNarc/codenarc-config-for-frameworks.html)

Additions and corrections are welcome.

And perhaps longer term we can look into something like rule config "profiles". See #491.

At least so far, I would still lean toward adding generic (not framework-specific) config properties to the rules as practical to support the framework use cases, rather than putting a bunch of framework-specific logic into the rule implementations. Frameworks come and go, and can change significantly along the way, and I would not want the code to be riddled with special case logic like 
    `    if (isGrailsApplication() && grailsVersion() >= 3.0 && grailsVersion() < 5) { … `

**Comment by tmysik** [comment]
@chrismair 

Yes, an idea about some config profiles (or maybe even better some config modules/plugins/SPI?) would be nice and very useful. Please note that more than one profile should be possible to apply (for example, we are using both Grails as well as Spock).

Thank you.

**Comment by demus-nine** [comment]
I would prefer maven packages you could add as a dependency, that contains configuration in a known location, fx. a jar file on the classpath, that modifies the default values of relevant rules. I would imagine they would need to be additive to support the case where you using say grails, geb and spock for testing, as opposed to grails cucumber and plain junit, fx. Of course manually configured rules would always override any default configuration.
If it were extensible, ie. the end-user could make there own internally distributable maven package using some convention that codenarc accepts, would be perfect, as that's what we are looking at implementing manually for our copious forest of projects with wildly differing code-styles.

**Comment by chrismair** [comment]
For what it's worth, I opened an issue on providing a CodeNarc Plugin mechanism: #494.

**Comment by chrismair** [comment]
Closing this issue. See #494 (plugins) and #491 (profiles) for possible larger-scale solutions.

Feel free to reopen if you feel this particular issue needs additional discussion/work.
