### ISSUE TITLE
CouldBeSwitchStatement does not consider scope

### ISSUE THREAD

**Issue by nre-ableton** [CodeNarc/CodeNarc#363]
I ran into a violation of `CouldBeSwitchStatement` in unit test code which looked a bit like this:

```groovy
@Test
void testA() {
  def closure = { i ->
    if (i == 'foo') {
      throw new Exception()
    }
  }
  // etc...
}

@Test
void testB() {
  def closure = { i ->
    if (i == 'bar') {
      throw new Exception()
    }
  }
  // etc...
}

@Test
void testC() {
  def closure = { i ->
    if (i == 'baz') {
      throw new Exception()
    }
  }
  // etc...
}
```

Changing the variable name fixes the violation, which is a hacky workaround for the time being.

**Comment by chrismair** [comment]
Do you mean that changing the variable name *closure* fixes the violation? Or the parameter name *i*?

**Comment by nre-ableton** [comment]
@chrismair the latter; changing the parameter name `i` fixes the violation.

**Comment by jlstrater** [comment]
hmm.. Ok. Perhaps we should check at the method level?

**Comment by nre-ableton** [comment]
@jlstrater Thanks so much for the fix!
