### ISSUE TITLE
UnusedVariable false-positive

### ISSUE THREAD

**Issue by boris-petrov** [CodeNarc/CodeNarc#369]
```groovy
def (a, _, c) = [1, 2, 3]
println(a)
println(c)
```

This gives an `UnusedVariable` warning for `_` but it shouldn't. Or is there some syntax that I don't know about that can allows me to "skip" the middle variable?

**Comment by chrismair** [comment]
My apologies for not replying to this sooner. I originally thought this was a more complicated Spock-related issue. But I now see that in this case `_` is just a variable name that you do not care about and is conventionally named `_`.  If that is the case, then the rule is behaving properly, but it would certainly be reasonable to ignore variables named `_`. You can set the *ignoreVariableNames* field on that rule to accomplish that.

**Comment by boris-petrov** [comment]
@chrismair - no problem. The question here is that I don't see any reason for me to name the variable in any special way - if I use the first and the third variables, the second shouldn't matter - as there is no syntax that allows me to not specify it - so the name should be irrelevant and no warning for unused variable should be emitted. Do I make sense?

**Comment by chrismair** [comment]
Yes, that makes sense. But I am not inclined to change CodeNarc's behavior. It is behaving *properly*, even if in this particular edge case it is not what you want. If we did make a change to ignore unused variables in that scenario, it would just as likely hide real bugs for other users, when they actually did intend to use those variables.

**Comment by boris-petrov** [comment]
Alright, fair enough! Feel free to close the issue then. Thanks for the support!
