### ISSUE TITLE
[SpaceAfterOpeningBrace] for @Value('${someVariable}') for groovy test class

### ISSUE THREAD

**Issue by dhudomiet** [CodeNarc/CodeNarc#370]
Hi I have this code in constructor:
```groovy
SomeClass(@Value('${someValue}') String someValue) { ... }
```
when i run codeNarcTest i am getting [SpaceAfterOpeningBrace]. When i modify code like that:
```groovy
SomeClass(@Value('${ someValue}') String someValue) { ... } 
```
 or
```groovy
SomeClass(
        @Value('${ someValue}') String someValue) { ... }
```
everything is ok. Could you resolve this issue ?

**Comment by jlstrater** [comment]
Hi @dhudomiet ! Thanks for the helpful bug report. This issue should have been fixed in version 1.1 with #264. Can you please try to update codenarc and see if that resolves your issue? If so, please close this issue.

**Comment by chrismair** [comment]
Hmmm, so far I am unable to reproduce this error. I added this test to **SpaceAfterOpeningBraceRuleTest**, and it passes.
```
    @Test
    void testApplyTo_ConstructorWithAnnotatedParameters_NoViolations() {
        final SOURCE = '''
            class SomeClass {
                SomeClass(@Value('${someValue}') String someValue) { }
            }
        '''
        assertNoViolations(SOURCE)
    }
```

**Comment by chrismair** [comment]
Please reopen if this problem is still occurring in CodeNarc 1.4.
