### ISSUE TITLE
help with sonarqube integration upgrade

### ISSUE THREAD

**Issue by musketyr** [CodeNarc/CodeNarc#373]
I'm trying to resurrect Sonar Groovy plugin with CodeNarc 1.2.1. It's almost ready but it's giving false positive for rules using regular expressions.

<img width="926" alt="snimek obrazovky 2018-11-01 v 11 12 02" src="https://user-images.githubusercontent.com/660405/47846121-327bba80-ddc7-11e8-84e3-294b5327e00e.png">

I wonder if anyone have any suggestions why could this happen from CodeNarc point of view.

If you want to try it yourself then you can run SonarQube with Docker
```
docker run -d -p 9000:9000 --name sonarqube musketyr/sonarqube:6.7.5-SG1.6-RC5
```

Then you can log in to at http://localhost:9000/sessions/new with `admin:admin` and the tutorial will let you generate the API token.

**Comment by chrismair** [comment]
That extra "\\" is suspicious in "\\\S". Are you using the default rule configuration, e.g. *characterBeforeColonRegex*? I would expect the error message to be ```is not preceded by a match for regular expression [\S]```.

**Comment by musketyr** [comment]
thank you very much, I will investigate in that direction at the end of the week. now I need to move forward with other task

**Comment by chrismair** [comment]
Closing; but by all means reopen if this does end up being a legitimate issue.
