### ISSUE TITLE
Improve BracesForTryCatchFinally rule

### ISSUE THREAD

**Issue by erdi** [CodeNarc/CodeNarc#375]
`BracesForTryCatchFinally` rule could, similarly to how formatting around `else` keyword is checked by `BracesForIfElse`, also check that:
- `catch` keyword is on the same line as the closing brace of `try` or previous `catch` block
- the opening brace following `catch` keyword is on the same line as the keyword
- `finally` keyword is on the same line as the closing brace of `try` or `catch` block
- the opening brace following `try` keyword is on the same line as the keyword

**Comment by chrismair** [comment]
From what I can see, these features are all implemented in the `BracesForTryCatchFinally` rule.
