### ISSUE TITLE
UndeclaredVariable Rule

### ISSUE THREAD

**Issue by xGregor** [CodeNarc/CodeNarc#378]
In groovy-script undeclared variables are handled as global vars. Since this caused a really bad problem to us, we want catch this type of failure next time.
Is there a rule for finding undeclared vars?

```
someClosureMethod {
	aUndeclaredVariable = "some content"
}
```
"aUndeclaredVariable" should case an finding.

**Comment by chrismair** [comment]
There is no existing rule for that. I assume it would be technically possible to create one.

**Comment by xGregor** [comment]
Thanks, we created one.
