### ISSUE TITLE
CloseWithoutCloseable false-positive

### ISSUE THREAD

**Issue by boris-petrov** [CodeNarc/CodeNarc#379]
```groovy
def reader = new Reader() {
	@Override
	int read(char[] cbuf, int off, int len) {
		-1
	}

	@Override
	void close() {
	}
}
```

This gives a `CloseWithoutCloseable` warning which is wrong as this is a method that comes from the abstract base class.

**Comment by erdi** [comment]
This is a known limitation when not running in enhanced mode -  see the rule documentation at http://codenarc.sourceforge.net/codenarc-rules-design.html#CloseWithoutCloseable

**Comment by boris-petrov** [comment]
Ah, OK, I'll close this issue then. Why is this `false` by default?

**Comment by boris-petrov** [comment]
Hm, also, setting it to `true` causes a million errors like:

```
Compilation failed for [CustomCompilerPhaseSourceDecorator[SourceFile[/home/boris/project/SomeFile.groovy]]]
```

Any ideas why?

**Comment by erdi** [comment]
You should make yourself familiar with http://codenarc.sourceforge.net/codenarc-enhanced-classpath-rules.html. It's explained there why it's `false` by default and why you're seeing the errors.

**Comment by erdi** [comment]
E.g. if you are using CodeNarc with Gradle then you will need to set this property on your CodeNarc tasks: https://docs.gradle.org/current/dsl/org.gradle.api.plugins.quality.CodeNarc.html#org.gradle.api.plugins.quality.CodeNarc:compilationClasspath

**Comment by boris-petrov** [comment]
Thank you very much for the support! I think I'll be fine from here. Thanks!

**Comment by boris-petrov** [comment]
@erdi it's very strange - I updated from Gradle 7.6.2 to Gradle 8.2.1 and I started getting this issue again. And warnings on `CompareToWithoutComparable`. I haven't changed CodeNarc's configuration, i.e. I still have this:

```gradle
tasks.withType(CodeNarc).configureEach {
	configFile = file("${rootDir}/config/codenarc/codenarc.xml")
	compilationClasspath = sourceSets.inject(files([])) { acc, sourceSet ->
		acc + sourceSet.compileClasspath + sourceSet.runtimeClasspath
	}
	System.setProperty('org.codenarc.enhancedMode', 'true')
}
```

Any ideas what might have changed between Gradle 7 and 8 so that this started to happen?

**Comment by boris-petrov** [comment]
@erdi sorry to ping you again but you might have missed my question. :)
