### ISSUE TITLE
Could not initialize class org.codenarc.rule.junit.JUnitAssertEqualsConstantActualValueAstVisitor

### ISSUE THREAD

**Issue by boris-petrov** [CodeNarc/CodeNarc#380]
I just enabled the `enhanced` ruleset and I get an exception from one of the rules:

```
Error from [org.codenarc.rule.junit.JUnitAssertEqualsConstantActualValueRule] processing source file [/home/boris/project/SomeSpec.groovy]    
java.lang.NoClassDefFoundError: Could not initialize class org.codenarc.rule.junit.JUnitAssertEqualsConstantActualValueAstVisitor
```

The other rules work fine. I see in the name `JUnit` - we are using `Spock` - not sure if that matters.

**Comment by erdi** [comment]
It looks like [`JUnitAssertEqualsConstantActualValueRule` requires JUnit to be on the classpath used to run CodeNarc](https://github.com/CodeNarc/CodeNarc/blob/master/src/main/groovy/org/codenarc/rule/junit/JUnitAssertEqualsConstantActualValueRule.groovy#L46) and JUnit is not in CodeNarc's transitive dependencies as per its POM. This rule should probably fail more gracefully if JUnit is not on the classpath.

As a side note @boris-petrov, if you don't have JUnit tests in your codebase then I wouldn't bother enabling any JUnit specific rules as it will only slow down your CodeNarc analysis for no benefit.

**Comment by boris-petrov** [comment]
@erdi - true, but that would mean to go through each rule and disable it in my config which I would prefer not to do. :) In any case I think this should gracefully fail as you said.

**Comment by chrismair** [comment]
I have removed the requirement to have JUnit on the classpath for the **JUnitAssertEqualsConstantActualValue** rule.
