### ISSUE TITLE
[Feature Request] `maxPriorityXViolations` Arg for Command Line Usage

### ISSUE THREAD

**Issue by omgitsbillryan** [CodeNarc/CodeNarc#390]
### The Problem
Using CodeNarc by [running on the command line](http://codenarc.sourceforge.net/codenarc-command-line.html) does not allow me to pass `maxPriority1Violations=0` [similar to the way I can with Ant](http://codenarc.sourceforge.net/codenarc-ant-task.html). The [CodeNarc.groovy entry file](https://github.com/CodeNarc/CodeNarc/blob/master/src/main/groovy/org/codenarc/CodeNarc.groovy) doesn't seem to support such a param.

### Desired Behavior
I want a way to easily fail my build in the event that more than 0 `P1` violations are found.

**Comment by chrismair** [comment]
Available in CodeNarc 1.3.
