### ISSUE TITLE
ClassStartsWithBlankLine does not work for Jenkins DSL

### ISSUE THREAD

**Issue by mkordas** [CodeNarc/CodeNarc#398]
ClassStartsWithBlankLine says that the following file should have a newline on line two:
```
job('test-job') {
    triggers { // fails here, no new line above
        cron('* * * * *')
    }

    steps {
        groovyScriptFile('my_script.groovy')
    }
}
```

The rule should not fail here, as there is no class defined.

**Comment by chrismair** [comment]
Well, there actually *is* a class, but it is a (implicit) Script class, and I think it is reasonable to ignore those.

I changed **ClassStartsWithBlankLine** and **ClassEndsWithBlankLine** rules to ignore Script classes.
