### ISSUE TITLE
AssignCollectionUnique false positive for .unique(false)

### ISSUE THREAD

**Issue by terramexx** [CodeNarc/CodeNarc#399]
The violation should not occur when using groovy's unique with false mutate flag.
http://docs.groovy-lang.org/next/html/groovy-jdk/java/util/Collection.html#unique(boolean)

`Msg=[unique() mutates the original list.] Src=[def uniqueData = data.unique(false)]`

**Comment by chrismair** [comment]
Fixed for next release
