### ISSUE TITLE
CodeNarc does not catch any errors 

### ISSUE THREAD

**Issue by AbdulRahmanAlHamali** [CodeNarc/CodeNarc#413]
Hello,

I am interested in using CodeNarc for my team's Jenkins Groovy libraries. I tried the following command:
```
java -classpath mvn/org/codehaus/groovy/groovy-all/2.3.11/groovy-all-2.3.11.jar:mvn/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar:mvn/org/codenarc/CodeNarc/1.3/CodeNarc-1.3.jar org.codenarc.CodeNarc -report=console -includes=./vars/*,./pipeline_jobs/* -rulesetfiles=rulesets/basic.xml,rulesets/braces.xml,rulesets/generic.xml -title=MyReport
```

Adding as many rules as possible, just to catch any errors, but nothing is showing:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
CodeNarc Report - Mar 22, 2019 12:16:32 PM

Summary: TotalFiles=25 FilesWithViolations=0 P1=0 P2=0 P3=0

[CodeNarc (http://www.codenarc.org) v1.3]
CodeNarc completed: (p1=0; p2=0; p3=0) 1429ms
```

I tried this with random files that contain stuff like:
```
asd as das dewuf auds fads
if (zzz
{
asdz
}
```

And no violations whatsoever. Any idea why?

**Comment by chrismair** [comment]
The SLF4J defaulting to the NOP logger probably means that all error messages are hidden. Perhaps add the slf4j-simple-xxx.jar or Logback jar.

If a source file does not compile, then CodeNarc will log an error and skip that file.

**Comment by AbdulRahmanAlHamali** [comment]
yup using slf4j-simple does the trick!

Thank you!
