### ISSUE TITLE
UnnecessaryGetter false-negative with `is*` methods

### ISSUE THREAD

**Issue by boris-petrov** [CodeNarc/CodeNarc#417]
Methods beginning with `is` can also be shortened like the ones that begin with `get`. For example:

```groovy
if (subject.isAuthenticated()) {
```

Can be written as:

```groovy
if (subject.authenticated) {
```

This should be handled by the `UnnecessaryGetter` rule or some new one.

**Comment by chrismair** [comment]
**UnnecessaryGetter** rule: Add *checkIsMethods* property. If true, then also check is* methods.

Available in CodeNarc 1.4
