### ISSUE TITLE
Define directory paths to scan

### ISSUE THREAD

**Issue by SebastianHerzog** [CodeNarc/CodeNarc#428]
hi,
I am using the gradle codenarc plugin https://docs.gradle.org/current/userguide/codenarc_plugin.html .
How/Where can I tell CodeNarc in which Folders it is supposed to look for the code files.
Seems to work only for src/main/groovy and src/test/groovy out of the box which i only found out by being lucky i guess because i didn't find these "default paths" in the documentation.

**Comment by erdi** [comment]
CodeNarc is for static code analysis of project sources and not for checking anything in dependencies. Dependencies are binary (bytecode) and not source so it's impossible to do static code analysis on them. Anyway, what would be the benefit of checking dependencies with CodeNarc?

**Comment by SebastianHerzog** [comment]
oh sry i mean i want to change the path to a folder. lets say my code is at src/core how can i tell this to CodeNarc

**Comment by erdi** [comment]
Your question is more about Gradle then CodeNarc as it has to do with configuration of Gradle's codenarc plugin. I'd suggest you ask at https://discuss.gradle.org/.

**Comment by SebastianHerzog** [comment]
ok i will try that thanks.

**Comment by SebastianHerzog** [comment]
https://discuss.gradle.org/t/gradle-codenarc-plugin-how-to-change-target-folder-for-the-scan/32102/2
just in case someone is looking for the same there is the solution.
