### ISSUE TITLE
False positive in SpaceAroundMapEntryColon when spread map operator is used

### ISSUE THREAD

**Issue by erdi** [CodeNarc/CodeNarc#430]
Given the following configuration:
```
ruleset {
    SpaceAroundMapEntryColon {
        characterBeforeColonRegex = /./
        characterAfterColonRegex = /\s/
    }
}
```
The following code:
```
def binding = [*: scriptConfig.parameters]
```
Causes:
> The colon for the literal Map entry for key [*:scriptConfig.parameters] within class com.onresolve.scriptrunner.canned.jira.utils.TypedCustomScriptDelegate is not followed by a match for regular expression [\s]

**Comment by chrismair** [comment]
Available in CodeNarc 1.5 (whenever that is)
