### ISSUE TITLE
characterBeforeColonRegex regex not working as expected

### ISSUE THREAD

**Issue by philbrown-mdt** [CodeNarc/CodeNarc#434]
There does not seem to be a way to specify that no whitespace or some whitespace is acceptable here for characterBeforeColonRegex (for example, `'\\s?'` or `'( )?`). I want to be able to support the following scenarios (which IntelliJ auto-formats as I would expect):

### In-line map without a space

````groovy
static content = {
    foobar(required: false, wait: true) { ... }
}
````

### Formatted multi-line map

    static final Map<String, String> THINGS = ['foo'  : 'bar',
                                               'foo2' : 'bar2',           
                                               'foo22': 'bar22',           
    ]

**Comment by chrismair** [comment]
You can support both of those scenarios with:
```
        characterBeforeColonRegex = /./
        characterAfterColonRegex = /\s/
```
Of course, that allows *anything* before the colon.

**Comment by chrismair** [comment]
Feel free to reopen this issue if there is a problem.
