### ISSUE TITLE
duplicate annotation on same member errors

### ISSUE THREAD

**Issue by Vampire** [CodeNarc/CodeNarc#439]
I test my code using Spock, which is using a Groovy DSL.
I check my test code using CodeNarc via Gradle CodeNarc plugin.
In my test class I have inner classes like the following:
```groovy
    @Alias('test1')
    @Alias('test2')
    @RestrictedTo(RestrictionOne)
    @RestrictionPolicy(NONE_OF)
    static class Test5 extends BaseCommand { }
```
`@Alias` is of course a repeatable annotation.
Running the tests with Spock works flawlessly and the compiled and then decompiled class also looks fine:
```groovy
    @RestrictedTo(CommandTest.RestrictionOne.class)
    @RestrictionPolicy(Policy.NONE_OF)
    @Aliases({@Alias("test1"), @Alias("test2")})
    public static class Test5 extends CommandTest.BaseCommand {
```
But when the `codenarcTest` task is run,
(which actually finishes without build failure o_O !?!)
I get for each instance of multiple annotations (in the example case one instance, the second `Alias` annotation) two compilation errors shown like:
```
Compilation failed for [CustomCompilerPhaseSourceDecorator[SourceFile[D:\Sourcecode\other\command-framework\src\test\groovy\net\kautler\command\api\CommandTest.groovy]]]; org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
None: 365: Cannot specify duplicate annotation on the same member : net.kautler.command.api.annotation.Alias
 @ line 365, column 5.
       @Alias('test2')
       ^
None: 365: Cannot specify duplicate annotation on the same member : net.kautler.command.api.annotation.Alias
 @ line 365, column 5.
       @Alias('test2')
       ^
```

So one point is, that the task should probably fail if that happens, because I guess that the extended rules for which the parsed AST is necessary are not executed.
The other point is, that actually in my case no error should happen as it is perfectly fine code.

**Comment by erdi** [comment]
[Support for `Repeatble` has only been added in Groovy 2.5.0](https://issues.apache.org/jira/browse/GROOVY-8234) - which version are you running CodeNarc with (this can be answered by running ` ./gradlew dependencyInsight --configuration codenarc --dependency groovy`)?

**Comment by Vampire** [comment]
Yeah, that's actually 2.3.11.
Which is strange then, as I use 2.5.4 for the actual code.
But I guess this is a problem in the CodeNarc gradle plugin then that should set it accordingly?

**Comment by Vampire** [comment]
I reported this at https://github.com/gradle/gradle/issues/10521, but then the problem remains, that the Gradle task does not fail on compile error, which actually is a problem in the CodeNarc Ant task as @erdi pointed out, as it does not fail on the compilation error, but just ignores it.

**Comment by erdi** [comment]
I agree that CodeNarc should at least offer a way to fail if there are any compilation errors happening during compilation while performing the analysis. Just logging the error is not enough control, imho. Given that it would be a breaking change, I would suggest making it a configuration option of the Ant task which for backwards compatibility would be disabled. 

I would argue that it this issue should be closed and a new one, just for the purpose of altering the Ant task should be created. Finally, after that issue is implemented, a new issue should be filed with Gradle to expose the new configuration option on configuration of the plugin and/or `org.gradle.api.plugins.quality.CodeNarc` task.

**Comment by chrismair** [comment]
I opened a separate issue #441 to *Enable CodeNarc Ant Task to optionally fail for Groovy compile errors on source files*. That also references an old issue from Sourceforge that discussed some of the motivations for why it is the way it is, and that it is not a trivial thing to fix. But that is not to say that it is not possible.

**Comment by Vampire** [comment]
Well, then I guess this can be closed, as the non-failing was the only issue here, the other was a configuration problem.
