### ISSUE TITLE
SpaceAfterClosingBrace should not trigger if followed by method call parenthesis

### ISSUE THREAD

**Issue by Vampire** [CodeNarc/CodeNarc#440]
`writeLockLockInterceptor.tap { it.delegate = owner.delegate }()` is complained about, that it should look like `writeLockLockInterceptor.tap { it.delegate = owner.delegate } ()`.
I don't think that when called as method there should be a space.
Could this maybe at least be an option?

**Comment by chrismair** [comment]
Fixed for CodeNarc 1.5.

Ignore when followed by opening parenthesis or opening square brace.
