### ISSUE TITLE
Documentation Site to move out of Sourceforge 

### ISSUE THREAD

**Issue by anumalasri** [CodeNarc/CodeNarc#442]
Lot of companies blocked sourceforge.net in their enterprise network .. Can you able to move documentation out of SourceForge ?  

Suggestion to add documentation with in GitHub wiki itself

**Comment by chrismair** [comment]
Probably a good idea. It was briefly blocked at my company, too. That was frustrating!

**Comment by chrismair** [comment]
I have mostly completed the migration to GitHub Pages. The new pages are under the /docs folder, and are available at http://codenarc.github.io/CodeNarc/.

I still have to migrate the Rules Index and code generation scripts, and then switch the codenarc.org domain.

**Comment by chrismair** [comment]
Now available with CodeNarc 1.5. <http://codenarc.org>.
