### ISSUE TITLE
[Feature request] Support @SuppressWarnings("all")

### ISSUE THREAD

**Issue by jordanjennings** [CodeNarc/CodeNarc#445]
I'm adding CodeNarc to an existing project and there are a few legacy / deprecated classes that violate a lot of different rules and that aren't worth fixing. I was hoping that `@SuppressWarnings("all")` would be supported similarly to PMD and Checkstyle but it appears that I have to specify a list of all the individual rules in the `@SuppressWarnings` annotation.

Is there any existing way to disable all rules for a given class or method? I'm using CodeNarc via gradle and didn't see any option there to exclude certain paths, and I don't see any other way to exclude all rules for an entire class/method, etc. Let me know if I'm missing something. Thanks!

**Comment by chrismair** [comment]
Hmmm, I am not sure. If you were using the Ant Task, you could configure the \<fileset\> to exclude those files. But I assume you are using the Gradle **CodeNarc** plugin. It looks like you might be able to define a custom *sourceset*, and specify that on the [Gradle plugin config](https://docs.gradle.org/current/dsl/org.gradle.api.plugins.quality.CodeNarcExtension.html), e.g.
 - https://stackoverflow.com/questions/11581419/how-do-i-add-a-new-sourceset-to-gradle
 - https://stackoverflow.com/questions/47825256/gradle-how-to-build-extra-source-sourcesets

**Comment by jordanjennings** [comment]
Configuring a whole source set just to exclude a couple files is pretty heavyweight, I just decided to fix some of the autoformat-fixable issues and manually exclude the rest for now.

I'll rename this issue to be a feature request to support the special `"all"` suppression.

**Comment by chrismair** [comment]
What do you think about `@SuppressWarnings("*")`, to avoid having to be concerned about capitalization/spelling?

**Comment by jordanjennings** [comment]
That seems very reasonable, however since lots of tooling already supports `@SuppressWarnings("all")` I think the most discoverable and consistent implementation would be to follow that same convention. Javac, PMD, and Checkstyle all support it (and maybe more?) so for people like myself that use multiple JVM languages and tools that feels right.

**Comment by chrismair** [comment]
I see that Eclipse supports `@SuppressWarnings("all")`. I could not find references for PMD or Checkstyle. Let me know if you have references for either of those.

Another option would be `@SuppressWarnings("CodeNarc")`, to be like PMD's `@SuppressWarnings("PMD")`, to cover all warnings. But I probably prefer the simpler "all".

**Comment by jordanjennings** [comment]
Can't find docs for PMD but here's the code:
https://github.com/pmd/pmd/blob/master/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTAnnotation.java#L89

It supports "PMD" or "all" which is nice because sometimes you don't want to suppress all compiler warnings but you do want to suppress PMD. It also supports a prefix for rule names in case of clashes, so you can do "PMD.SomeRule".

Checkstyle source is here:
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java#L130

Checkstyle supports "all" but does not support "checkstyle". It also supports an optional prefix like "checkstyle:CheckName" for name clashes.

I'd like "all" support, but I assume it would be just as easy at the same time to also support "CodeNarc". If that assumption is correct then adding both would be ideal.

**Comment by chrismair** [comment]
Thanks. That was helpful. I'll look into adding support for "all" and "CodeNarc".

**Comment by chrismair** [comment]
Available for CodeNarc 1.5
