### ISSUE TITLE
Feature request: add rule for implicit return

### ISSUE THREAD

**Issue by nre-ableton** [CodeNarc/CodeNarc#450]
I would really like to see a CodeNarc rule which warns about use of the implicit return. For example:

```groovy
// Violation should be raised
boolean example() { true }

// Correct code
boolean example() { return true }
```

Aside from personal preference (I guess this stems from a background of working in other languages where `return` must always be explicitly given), I have run into cases where the implicit return caused bugs which slipped past code review. We use CodeNarc at my company to enforce a stricter, more correct style of Groovy, and IMHO enforcing an explicit `return` statement fits right in with CodeNarc's philosophy.

**Comment by chrismair** [comment]
Available with CodeNarc 1.6.

Only checks methods (not closures). Skips `void` methods and `def` methods, as well as methods whose last statement is a:
 - `throw`
 - `if`
 - `for`
 - `while`
 - `switch`
 - `try/catch`
