### ISSUE TITLE
False-positive in GetterMethodCouldBeProperty

### ISSUE THREAD

**Issue by Vampire** [CodeNarc/CodeNarc#451]
For this class:
```groovy
    static class PingCommand extends PingIntegTest.PingCommand {
        static commandNotAllowedEventReceived
        static restrictionChain

        void handleCommandNotAllowedEvent(@ObservesAsync CommandNotAllowedEventJavacord commandNotAllowedEvent) {
            commandNotAllowedEventReceived?.set(commandNotAllowedEvent)
        }

        @Override
        RestrictionChainElement getRestrictionChain() {
            restrictionChain
        }
    }
```

I'm getting the finding `The method 'getRestrictionChain ' in class net.kautler.command.integ.test.javacord.restriction.RestrictionChainElementIntegTest$PingCommand can be expressed more simply as the field declaration final RestrictionChainElement restrictionChain = restrictionChain`.

This will not work.

At least the static field would be needed to be renamed.
But even then it will not work properly.

The `restrictionChain` instance field will be initialized from the static field at instantiation (in this case `null` which will produce a `NullPointerException`).
With the method it will return the current value of that static field, as it is not a constant.

Also using the field to override the getter in the super-class or interface does not allow to attach an `@Override` annotation to make it clear this overrides or implements some super-method.

**Comment by chrismair** [comment]
I agree this is an edge case that should be fixed.

Perhaps we can also ignore methods with an `@Override` annotation.

**Comment by chrismair** [comment]
>> Perhaps we can also ignore methods with an @Override annotation.

The rule **GetterMethodCouldBeProperty** rule already has a `ignoreMethodsWithOverrideAnnotation` property. It defaults to `false`, so setting it to `true` will avoid the above issue.

**Comment by Vampire** [comment]
Ah, great for that, thanks.
But even then, let's assume this does not override a method or at least does not have the annotation.
The advice would still be wrong and recommend semantically significantly different code.

**Comment by chrismair** [comment]
Agreed, I am looking into fixing the underlying problem for that. I'm considering changing the rule to only count getters for static fields that are final, since non-final fields are not really "constant".

**Comment by chrismair** [comment]
The rule no longer treats static non-final fields as constants, only `static final` fields.
