### ISSUE TITLE
Improve NoJavaUtilDateRule to also raise violation on usages of static methods from java.util.Date

### ISSUE THREAD

**Issue by erdi** [CodeNarc/CodeNarc#454]

**Comment by chrismair** [comment]
I see these static methods on java.util.Date:
 - `static Date	from(Instant instant)`
 - `static long	parse(String s)`  // deprecated
 - `static long	UTC(int year, int month, int date, int hrs, int min, int sec) `   // deprecated

Would you suggest this rule just check for the two deprecated methods? The `from(Instant)` method would seem to be a legitimate conversion method.

**Comment by erdi** [comment]
Yes, it has been brought to my attention after I submitted this issue that we probably do not want to raise violations for `static Date from(Instant instant)` because as you pointed out it is a legitimate conversion method which is useful when dealing with 3rd party legacy methods which have `java.util.Date` parameters. So I agree with you that the rule should just check for the two deprecated static methods you mention in your comment.
