### ISSUE TITLE
False-positive in SpaceBeforeOpeningBrace when constructor gets a closure

### ISSUE THREAD

**Issue by Vampire** [CodeNarc/CodeNarc#455]
CodeNarc complains about this:
```groovy
new LazyReferenceByFunction<Object, Object>({ null }) { }
```
with `The opening brace for class net.kautler.command.util.lazy.LazyReferenceBySupplierTest$1 is not preceded by a space or whitespace`.
But the class opening brace is preceded by a space.
I guess the rule sees the closure opening brace wrongly as class opening brace.

**Comment by Vampire** [comment]
Or if it actually is about the closure opening brace, then I'd like to suggest not to complain if the closure is used as parameter

**Comment by chrismair** [comment]
Fixed for CodeNarc 1.6
