### ISSUE TITLE
Simple installation with NPM Package npm-groovy-lint

### ISSUE THREAD

**Issue by nvuillam** [CodeNarc/CodeNarc#460]
Hi :)

I have struggled to run CodeNarc via command line, so to avoid others to struggle as much as I did, I created a NPM package embedding CodeNarc & the required jar dependencies

https://github.com/nvuillam/npm-groovy-lint

Now it can be as simple as 

```
npm install -g npm-groovy-lint

$npm-groovy-lint -basedir="src" -rulesetfiles="file:config/codenarc/RuleSet-all.txt" -title="MyGroovyLinterReport" -maxPriority1Violations=0 -report="html:MyGroovyLinterReport.html" 
```

If you want you can add a link on your website -> http://codenarc.sourceforge.net/codenarc-command-line.html or wherever you want !

Best regards

Nicolas

**Comment by nvuillam** [comment]
V2 now starts to fix CodeNarc returned errors :)
Is this repo still alive ?

**Comment by chrismair** [comment]
Cool. Thanks for doing that.

The CodeNarc page you listed is from the old/deprecated Sourceforge site. I admit I need to make that more obvious. The project has since moved to GitHub, and the new pages are at:
http://codenarc.github.io/CodeNarc/

I'll take a TODO to update the CodeNarc page(s) to add a link to your GitHub page.

**Comment by nvuillam** [comment]
As far as I know, the documentation exists only on sourceforge site ? If there is somewhere else please tell me and i'll update the links.

Now the NPM package is usable (even if the --fix option can still be improved), i'm glad to give you a spoiler that should arrive soon :)

If by chance CodeNarc rules could reply not only a line number, but also a range ( start line + start char to end line + end char), it would be perfect for what is coming :) ( meanwhile i just highlight the full line )

![image](https://user-images.githubusercontent.com/17500430/75196007-5ea91080-575b-11ea-9086-197d2ef40379.png)

**Comment by chrismair** [comment]
The GitHub repo is at https://github.com/CodeNarc/CodeNarc. The markdown files are under the "docs" folder.

I added a link on the *codenarc-other-tools-frameworks* page. But feel free to do a PR to correct/enhance that page.
http://codenarc.github.io/CodeNarc/codenarc-other-tools-frameworks.html

**Comment by nvuillam** [comment]
I think the main issue is that the repo README starts with CodeNarc.org, who redirects to the sourceforge website ^^
Ok, i'll make a pr to arrange that :)
About the sourceforge pages, i think a single page redirecting to github pages would solve any future mistake from google ^^

**Comment by chrismair** [comment]
I have updated the Sourceforge CodeNarc home page to automatically redirect to the new homepage on GitHub. Thanks for pointing that out.

**Comment by chrismair** [comment]
Feel free to reopen if there is still work to do on this issue.
