### ISSUE TITLE
VariableName rule should only check static final fields for all caps

### ISSUE THREAD

**Issue by tlefevre** [CodeNarc/CodeNarc#467]
I noticed there's been an earlier issue on this, but I don't think it correctly posed the question.

https://google.github.io/styleguide/javaguide.html#s5.2.7-local-variable-names
https://www.oracle.com/technetwork/java/codeconventions-135099.html

The Oracle article is archived though, but is still relevant. 

The default finalRegex for Codenarcs VariableNameRule enforces that they should start with upper case letters. This contradicts the above naming conventions (also, checkstyle adheres to these conventions). 

https://github.com/CodeNarc/CodeNarc/blob/master/src/main/groovy/org/codenarc/rule/naming/VariableNameRule.groovy#L47

This line specifically states that the variable final regex is equal a constant regex, but final variables are per definition not constants. At least per both above documents. 

I don't think that this problem was adequately addressed in the previous issue on this matter.

**Comment by tlefevre** [comment]
True, people would have new warnings pop up that they previously didn't. But that follows with new versions of CodeNarc when new rules get implemented already. 

So changing this would just be a slight variation of this.

**Comment by erdi** [comment]
> But that follows with new versions of CodeNarc when new rules get implemented already.

That's not entirely true, in my opinion. This will only happen if you use the built in rulesets, i.e. ones provided in `rulesets/*.xml` files but I don't know how many users do that and how many users are used to that breaking behaviour by now.

I think that there is a number of questions here:
1. What is CodeNarc contract with regards to backwards compatibility? Is it following semver strictly?
2. If we decided that this is a breaking change that we don't want to make now but we consider the current behaviour as not the right one then when would we get a chance to change it? Basically, when is CodeNarc 2.0 planned for that would allow breaking changes like that?
3. Do we feel strong enough about this change being beneficial to commit to making that braking change? And if so, would we be ok with it if we added information to the description of the rule and its documentation about this breaking change and how to revert to the old behaviour to help anybody who is affected by the change?

I personally would not change the default behaviour but would:
- add a section to the docs for the rule on why the default is what it is and how to workaround it (basically that if you set `finalRegex` to `null` then the rule will only accept camel-cased names) 
- set the milestone on this issue to be `2.0`, add a "breaking change" label and address all such issues before the next major release

**Comment by tlefevre** [comment]
Sounds like a reasonable approach.

**Comment by chrismair** [comment]
I have been debating with myself about this issue for the last week, changing my mind more than once. 

CodeNarc did not yet follow semver fully, though I had been considering it. But I do think that is a reasonable strategy starting now.  Thanks for laying out a path, Marcin. I have checked in some doc updates to reflect the expected future change: [VariableNameRule](http://codenarc.github.io/CodeNarc/codenarc-rules-naming.html#variablename-rule).
