### ISSUE TITLE
Reading properties from file broken in Java 11+

### ISSUE THREAD

**Issue by szpak** [CodeNarc/CodeNarc#471]
I hit https://github.com/gradle/gradle/issues/12646 and I wanted to test if it is problem with CodeNarc itself or the Gradle plugin. However, it turned out that I'm not able to add Java 11 and 14 builds on Travis as the CodeNarc build fails with Java 11 and 14 (probably also with any 9+).

With Java 11 there are 6 tests fails (with Java 14 - 4):
```
PropertiesFileRuleSetConfigurerTest. testConfigure
PropertiesFileRuleSetConfigurerTest. testConfigure_OverridePropertiesFilenameThroughSystemProperty
PropertiesFileRuleSetConfigurerTest. testConfigure_OverridePropertiesFilenameThroughSystemProperty_FileUrl
PropertiesFileRuleSetConfigurerTest. testConfigure_PropertiesFileDoesNotExist
```

I took a look at the failers and the problem seems to be the way how `java.util.Properties` is used. There is an assumption in tests that properties with be loaded in an order given in the configuration file. It was never true. `Properties` extends `Hashtable` and the order is no guaranteed. With Java 11 most likely due to hashcode implementation change along the way:
```
rule2.violationMessage = violation
rule2.name = rule99
```
is read in the reverse order and `rule2.violationMessage` doesn't match anything (there is already `rule99`).

It would be good to decide if:
1. `rule2.name` (and possibly other dependent constructions) should be officially deprecated and claimed as unsupported (with related tests removed) - those most likely are unreliable in people's production configurations.
2. Some ordered Properties implementation should be used instead (e.g. [java-ordered-properties](https://github.com/etiennestuder/java-ordered-properties))
3. Some other fix/mitigation is applied.

Btw, I also added extra timming in `BaselineXmlReport_IntegrationTest` as with Java 11 (as oposed to Java 8 and 13) there were extra leading and trailing empty characters...

My draft PR with Java 11 and 14 builds is [here](#470).

**Comment by chrismair** [comment]
Cool. Thanks for the problem report + the in-depth analysis. I will plan to work on fixing these issues to get us to Java 11 support. I'm still not sure if I want to go all the way to Java 14 for the upcoming release, but we'll handle that as a separate issue anyway.

**Comment by szpak** [comment]
It turned out that the main problem with Java 14 was (rather) old Groovy 2.3 (in 1.5), so it is not crucial to bump the source compatibility in general. It could be change only temporarily during the Travis build with Java 14 to test it with Java 14. Anyway, once fixed the aforementioned Properties issue, I might help with the Travis build, if needed. It would be good to know that CodeNarc works fine with Java 14 (as Groovy 2.5.10 and 3.x do).

**Comment by chrismair** [comment]
I have fixed the tests failing under Java 11.

I agree on your assessment of the inherent danger in overriding a rule name in the properties file, so I have deprecated that, updated the docs, and removed those examples in the tests.

Thanks for your help.
