### ISSUE TITLE
New violation occured once Groovy bumped to 2.5.10 in CodeNarc 1.5

### ISSUE THREAD

**Issue by szpak** [CodeNarc/CodeNarc#474]
As a workaround to run CodeNarc with Java 14 I overridden Groovy dependencies to 2.5.10 in my build (as suggested [here](https://github.com/gradle/gradle/issues/12646#issuecomment-604594943)). However, there started to appear new violations which were not reported with default Groovy 2.3 on classpath.

```
[ant:codenarc] Violation: Rule=ClosureStatementOnOpeningLineOfMultipleLineClosure P=3
Line=79 Msg=[The multi-line closure within class info.solidsoft.gradle.pitest.PitestPlugin contains a
statement on the opening line of the closure.] Src=[project.tasks.register(PITEST_TASK_NAME, PitestTask) { t ->]
```

It might be some changes between Groovy 2.3 and 2.5 (and binary incompatibilities), but it would be good to ensure it doesn't happen if CodeNarc is both build and executed with Groovy 2.5.

Sample [file](https://github.com/szpak/gradle-pitest-plugin/blob/master/src/main/groovy/info/solidsoft/gradle/pitest/PitestTask.groovy), where the new violations are reported.

**Comment by chrismair** [comment]
I can reproduce some similar errors within the CodeNarc project/tests by locally switching to Groovy 2.5.

**Comment by chrismair** [comment]
Interesting. The `ClosureStatementOnOpeningLineOfMultipleLineClosure` tests work fine through Groovy 2.5.8 but then fail on 2.5,9. The behavior changed related to the *lineNumber* of the Block within a Closure.
