### ISSUE TITLE
Codenarc fails on spock table `||` separator

### ISSUE THREAD

**Issue by modestukasai** [CodeNarc/CodeNarc#475]
Hi,
Codenarc fails on spock table in spec seen bellow:
![image](https://user-images.githubusercontent.com/1135855/77856505-57649f00-7200-11ea-8980-34e4ebe0bd6b.png)
with rule:
![image](https://user-images.githubusercontent.com/1135855/77856520-6e0af600-7200-11ea-9a9b-62825c581e2f.png)

**Comment by chrismair** [comment]
This looks to be a duplicate of #176.
