### ISSUE TITLE
Return CodeNarc version via command line ?

### ISSUE THREAD

**Issue by nvuillam** [CodeNarc/CodeNarc#477]
I looked in the repo, but I didn't see :
- **1**. option **-v** / **-version**
- **2**. any way to find in the source the version of codenarc

If there is **2**. , i could make a PR to manage **1**.
If not, could it be possible to plan **1 & 2** in a future version ?

Many thanks !

**Comment by chrismair** [comment]
Great idea. There is logic in `AbstractReportWriter`, but I am inclined to move that out into its own `CodeNarcVersion` class. I can do that part.

**Comment by chrismair** [comment]
Okay, `CodeNarcVersion` is available now.

**Comment by nvuillam** [comment]
Great !
I created #478 so it can be returned via command line :)
When do you plan to release the next CodeNarc version ?

**Comment by chrismair** [comment]
Next version of CodeNarc is likely in May or June.

**Comment by chrismair** [comment]
Fixed by #478.
