### ISSUE TITLE
Core team must not forget to congratulate themselves

### ISSUE THREAD

**Issue by HamletDRC** [CodeNarc/CodeNarc#480]
Hi gang, 

I saw today that there was a [CodeNarc talk](https://www.youtube.com/watch?v=hZWt2-8LBfk) at last year's GR8Conf, and it got me thinking about all the work we put into this so many years ago. 

I hope @chrismair  and @erdi  are doing AWESOME and still having fun with this. 

Still kicking after more than 10 years!

**Comment by HamletDRC** [comment]
From my side, I continued to carry the torch of static analysis after joining Microsoft. I created a set of linting rules for TypeScript that became quite popular: https://github.com/microsoft/tslint-microsoft-contrib. It is deprecated now because the underlying AST technology changed.

**Comment by chrismair** [comment]
Nice! Thanks for the call-out Hamlet. Yes, still going strong. And thanks for the link to Jenn's talk at GR8Conf. That was awesome, Jenn. So many great contributions on this project.

**Comment by erdi** [comment]
Great to hear from you, @HamletDRC! 

CodeNarc will always have a special place in my heart as it is [the first OSS project I have ever contributed to](https://github.com/CodeNarc/CodeNarc/commit/8a13f71bab8d428c7e07d022ea9ac5dd3dbd0009#diff-a57c5664946b9cb5d71f6efcbc8ef594R25). You probably don't remember that, Hamlet, but it happened under your guidance during the Hackargarten at GR8Conf EU 2011! So, whenever I have an opportunity I'm trying to contribute back any custom rules I write for work projects.

**Comment by HamletDRC** [comment]
@erdi  of course! those early conferences were fun times!

**Comment by sbglasius** [comment]
A big shout-out to the CodeNarc team!!!

I'm pretty pleased to see GR8Conf mentioned too ;-)
