### ISSUE TITLE
Provide results in JSON

### ISSUE THREAD

**Issue by nvuillam** [CodeNarc/CodeNarc#481]
For npm-groovy-lint, I have to play with temporary report XML files that I have to parse then delete ... 

As it is not very nice, I'd like to have the results in JSON

So I propose to make 2 new report types :
- json
- jsonconsole

I start the dev in my fork, just notify me if you are not interested by the evolution :)

**Comment by chrismair** [comment]
The json report type sounds fine, requiring a new `JsonReportWriter` class, I assume.

What is the purpose of a separate jsonconsole type? Why does it need to be written to stdout?

**Comment by nvuillam** [comment]
JsonReportWriter & test class in progress :)

About json output in console, it's to be able to parse stdout directly instead of reading a file when you call CodeNarc in command line (i don't need the json output file but I thought someone may in the future so i also started to implement it)

**Comment by chrismair** [comment]
I'm a bit hesitant about adding a specific jsonconsole report type for this one use case. I would probably be more inclined to expand the `-report=REPORT-TYPE[:FILENAME]` command-line parameter to allow specifying that report be written to *stdout*. Perhaps `-report=REPORT-TYPE[:FILENAME|:stdout]`

What do you think about that option? Then I think you could use the `json:stdout` as the report type.

**Comment by nvuillam** [comment]
I completed the dev  in #485 , please can you have a look ?

About consoleJson: 
All the report types are following the scheme TYPE=DETAIL
The ReportWriter class returned uses only TYPE part of the string, so I preferred to not change the current architecture in order to minimize impacts -> https://github.com/CodeNarc/CodeNarc/pull/485/files#diff-8ff0a561279ab0bb4b875fc03b4656f2L31

Is it ok for you ?

**Comment by chrismair** [comment]
I opened #486 to enable ` -report=REPORT-TYPE[:FILENAME|:stdout]`, e.g. `-report=html:stdout`.

I'll try to work on that within the next few days and then I'll ask you to remove `consoleJson` and its refs/docs.

**Comment by nvuillam** [comment]
@chrismair don't bother, I already did it in my fork, it will be included in my PR when my json format updates will be completed  :)

**Comment by chrismair** [comment]
Fixed by #485.
