### ISSUE TITLE
Change UnusedMethodParameterRule to also raise violations on unused parameters of constructors

### ISSUE THREAD

**Issue by erdi** [CodeNarc/CodeNarc#487]
I'm not sure if it's by design or by omission but `UnusedMethodParameterRule` does not raise violations on unused parameters of constructors and I believe that it would be good if it did. I would suggest adding a configuration option to enable reporting on unused constructor parameters to that rule, which for backwards compatibility should be set to false.

**Comment by erdi** [comment]
If the suggested option of adding a config option is ok with you, @chrismair, then I'm happy to provide a PR which would introduce such option and then change the implementation of `UnusedMethodParameterAstVisitor` by switching it to be a `AbstractAstVisitor` instead of `AbstractMethodVisitor`.

**Comment by erdi** [comment]
Another option would be to change `AbstractMethodVisitor.visitClass()` to also call `visitConstructor()` for each item in `node.getDeclaredConstructors()` but I'm not sure if that's in line with what `AbstractMethodVisitor` was designed for.

**Comment by chrismair** [comment]
Yeah, I think that was just an oversight. Your first suggestion sounds good, switching to `AbstractAstVisitor`. Thanks.

**Comment by chrismair** [comment]
Just FYI... I am planning on doing a CodeNarc release within the next couple weeks. But if this does not get in for that, it is no big deal.

**Comment by chrismair** [comment]
I also changed the **UnusedPrivateMethodParameter** rule. Available with CodeNarc 2.0.0.
