### ISSUE TITLE
Github Actions workflow?

### ISSUE THREAD

**Issue by Zethson** [CodeNarc/CodeNarc#488]
Hi,

I would like to use CodeNarc in a Github Actions workflow. However, given that it does not include the main class and really is not super trivial to setup (like [Checkstyle](https://github.com/checkstyle/checkstyle), I was wondering whether you're planning to create a Github Actions workflow or whether someone in the community has already written one that I could copy?

Thank you very much!

**Comment by erdi** [comment]
FWIW, I think it's actually quite easy to run CodeNarc in a Github Actions workflow. If I were to do so, I would simply run CodeNarc via Gradle which has built-in support for it. Running Gradle in Github Actions is fairly simple - it can be done either directly on host using gradle wrapper or using [Gradle Command Github Action](https://github.com/marketplace/actions/gradle-command).

**Comment by Zethson** [comment]
My project is using maven. Can maven plugins also be run separately?

Or do you suggest to run CodeNarc via Gradle, even if the project is Maven based?

**Comment by nvuillam** [comment]
If you need a simple CLI to call codenarc, you can use npm-groovy-lint :)
https://www.npmjs.com/package/npm-groovy-lint

**Comment by Zethson** [comment]
Ahhh nice. This looks way more what I'm looking for.

Will try it out this week and close the issue if I'm happy :)

**Comment by Zethson** [comment]
```
zeth@master /t/Exploding_Springfield> npm-groovy-lint                                                                                                                                  (base) 
/usr/lib/node_modules/npm-groovy-lint/jdeploy-bundle/groovy-lint.js:15
    "use strict";
                ^

SyntaxError: Unexpected token ;
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/lib/node_modules/npm-groovy-lint/jdeploy-bundle/jdeploy.js:4:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

Yeah well, that test ended fast haha

**Comment by erdi** [comment]
There's also [Maven Codenarc Plugin](https://gleclaire.github.io/codenarc-maven-plugin/).

**Comment by Zethson** [comment]
All right. I just need to update node and npm.
This looks like exactly what I want. Thanks!

**Comment by nvuillam** [comment]
You need node 12 minimum sorry :)

**Comment by Zethson** [comment]
Yup. Worked when I upgraded it :)

**Comment by nvuillam** [comment]
If u need to easily configure the rules without updating manually config file, u can also use vscode groovy lint extension :)

**Comment by Zethson** [comment]
Thanks for the pointer!
However, we are pretty much all using IntelliJ for our development.

**Comment by nvuillam** [comment]
I don't have any religion, use what you like the most ;-)
