### ISSUE TITLE
Using CodeNarc with SpringBoot, Gradle 6.3 results in NoClassDefFoundError

### ISSUE THREAD

**Issue by cmhdave** [CodeNarc/CodeNarc#489]
I created a basic Spring Boot project to demonstrate this issue available here:

[https://start.spring.io/#!type=gradle-project&language=groovy&platformVersion=2.2.6.RELEASE&packaging=jar&jvmVersion=1.8&groupId=org.codenarc&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=org.codenarc.demo](https://start.spring.io/#!type=gradle-project&language=groovy&platformVersion=2.2.6.RELEASE&packaging=jar&jvmVersion=1.8&groupId=org.codenarc&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=org.codenarc.demo)

This will create a package with Gradle 6.3.  Change the build.gradle to include codenarc in the plugins section like so:

```
plugins {
	id 'org.springframework.boot' version '2.2.6.RELEASE'
	id 'io.spring.dependency-management' version '1.0.9.RELEASE'
	id 'groovy'
	id 'codenarc'
}
```
Then run `gradlew codenarcMain`

the resulting error is 
```
Execution failed for task ':codenarcMain'.
> java.lang.NoClassDefFoundError: Lgroovy/text/TemplateEngine;
```

If you change the gradle version to 6.2.2 it will work fine.

**Comment by chrismair** [comment]
Since that is using the Gradle CodeNarc plugin, I think that would need to be raised as an issue with Gradle ([Gradle issues](https://github.com/gradle/gradle/issues)), since they control the classpath when CodeNarc is executed that way.

**Comment by cmhdave** [comment]
Will do, thanks @chrismair.  I will close this issue here.
