### ISSUE TITLE
Cannot ignore comma character with DuplicateStringLiteralRule

### ISSUE THREAD

**Issue by dmurat** [CodeNarc/CodeNarc#490]
I cannot find a way to ignore comma character (',') via ignoreStrings property of DuplicateStringLiteralRule. If I'm missing something, please advise.
If not, is it possible to add this support? Tnx.

**Comment by chrismair** [comment]
Yeah, unfortunately that is not currently possible. Perhaps we can make the delimiter configurable.

**Comment by dmurat** [comment]
What about adding a flag to ignore separator too? It might be simpler to do.

**Comment by chrismair** [comment]
I think I'm going to add a separate *delimiter* config property, so you could customize that.

**Comment by chrismair** [comment]
Available with CodeNarc 1.6
