### ISSUE TITLE
Documentation not explicit enough about checks in next release

### ISSUE THREAD

**Issue by cristalp** [CodeNarc/CodeNarc#496]
First of all let me thank you for this great tool!

I just installed 1.5 and wanted to use `ImplicitReturnStatement` as indicated by https://codenarc.github.io/CodeNarc/codenarc-rules-convention.html
But then CodeNarc told me there was no such check.

I must admit that right now I noticed that it says `<Since CodeNarc 1.6>` - however it would be helpful if the documentation is generated (I assume it's generated) only for the currently published release.

As an alternative, it would be helpful if new, unreleased checks could be marked in one way or another.

**Comment by chrismair** [comment]
I agree. We recently switched from static site generation to using GitHub pages. But the way we chose to implement it has that side-effect of immediate update, which is both a blessing and a curse. We will have to look into options to address that.

**Comment by chrismair** [comment]
I have switched the GitHub settings to publish the website from the `gh-pages` branch, and used `git subtree push --prefix docs origin gh-pages` to update. 

So from now on, we can update the website docs as changes are made, but wait to publish the site until a release.

**Comment by cristalp** [comment]
Thanks! It would be really perfect if the same applied to changed parameters. I tried using DuplicateStringLiteral with ignoreStringsDelimiter and kept crashing CodeNarc. Although DuplicateStringLiteral  has been around since 0.11, the parameter has been added in version 1.6.
