### ISSUE TITLE
include required java version in the readme

### ISSUE THREAD

**Issue by jlstrater** [CodeNarc/CodeNarc#501]
While trying to build this project, I had to guess what Java version was needed. hint: it wasn't Java 12. 😉 

I propose adding the required java version to the readme under the development section. I don't mind adding the change, but I'd like to start a conversation here about what should go in that section before starting the work.

**Comment by chrismair** [comment]
Agreed. On the web site home page it says "Java 1.6 or later". But I acknowledge that there probably needs to be an upper bound as well.

And the Groovy version listed in the readme is out of date as well: "Groovy version 2.1". In the codebase (master) it is now Groovy 2.4.
