### ISSUE TITLE
False positives from Indentation rule with inner class declarations

### ISSUE THREAD

**Issue by nre-ableton** [CodeNarc/CodeNarc#504]
CodeNarc 1.5 is warning me about Indentation violations in a very suspicious way. Here's some offending code:

```groovy
class Artifact implements Serializable {
  protected static final class ArtifactLocation {
    /* stuff */
  }
}
```

CodeNarc raises this error:

> `ERROR Artifact.groovy:13: Indentation: The class Artifact$ArtifactLocation is at the incorrect indent level: Expected column 3 but was 26`

I thought that the number 26 was suspicious, and it turned out to be the character position of the keyword `class` in the declaration of the inner class. If I remove the `protected static final` part from the declaration, CodeNarc no longer raises this violation.

**Comment by chrismair** [comment]
Works fine (for me) in Groovy 2.4, but get above violation in Groovy 3.0. I added a test for this scenario.

Fixed by #495.
