### ISSUE TITLE
SpaceAroundOperator: Fix limitations with checking space around ternary operators

### ISSUE THREAD

**Issue by chrismair** [CodeNarc/CodeNarc#507]
SpaceAroundOperator: Fix known limitations with checking space around ternary operators.

**Comment by paplorinc** [comment]
It seems this change causes multiline Groovy ternaries to be rejected, i.e.
return (condition
            ? 0
            : 1
)

**Comment by chrismair** [comment]
That is not the same problem/issue. Please open a separate issue, and if possible please provide some sample code that causes the exception.
