### ISSUE TITLE
Improving indentation support for chained methods with closure parameters

### ISSUE THREAD

**Issue by dmurat** [CodeNarc/CodeNarc#510]
Currently, support for chained methods does not account for methods with closure bodies. For example, if the following test is added in `IndentationRuleTest`, the test will fail on `println someName` statement:

    @Test
    void test_MethodChaining_MultilineClosureParameter() {
        final SOURCE = '''
            |buildFileList().collect { item -> item.name }
            |               .each { name -> println name }
            |               .each { someName -> 
            |                   println someName
            |               }
            |               .each { name -> println name }
            |
        '''.stripMargin()
        assertNoViolations(SOURCE)
    }

Is it possible to add this support?

Tnx.

**Comment by chrismair** [comment]
I think the level of indentation for the .each lines in your example is off by one (or five or nine) columns.

In any case, the changes for the upcoming CodeNarc 1.6 have made this rule more lenient/robust. So this now works (jn the master branch):
```
    void test_MethodChaining_MultilineClosureParameter() {
        final SOURCE = '''
            |buildFileList().collect { item -> item.name }
            |        .each { name -> println name }
            |        .each { someName ->
            |            println someName
            |        }
            |        .each { name -> println name }
        '''.stripMargin()
        assertNoViolations(SOURCE)
    }
```
as does the same code with only a single level of indentation for the .each.

**Comment by dmurat** [comment]
Tnx for looking into this. I think it would be great if CodeNarc can support some common styles of chained methods indentation. I think that style 1 and 2 in the following example are most frequently used in the wild. At least in code that cares enough about indentation 😃 

```
// style 1
buildFileList()
        .collect { item -> item.name }
        .each { name -> println name }
        .each { someName -> 
            println someName
        }
        .each { name -> println name }

// style 2
buildFileList().collect { item -> item.name }
               .each { name -> println name }
               .each { someName -> 
                   println someName
               }
               .each { name -> println name }

// style 3
buildFileList().collect { item -> item.name }
        .each { name -> println name }
        .each { someName ->
            println someName
        }
        .each { name -> println name }
```
I didn't see much of style 3 since it visually hides the first method in the chain.

CodeNarc currently supports style 1 and 3, but style 2 fails with an indentation rule violation. I realize that Indentation rule implementation is pretty complex, and I'm having rather hard time following it. I guess this is one of the reasons for some inconsistencies that I stumbled upon. This might be seen in the next test example:

```
    @Test
    void test_MethodChaining_MultilineClosureParamet_AnotherExample() {
        final SOURCE = '''
            |buildFileList().collect { 
            |                   item -> item.name // <-- does not fail here
            |               }
            |               .each1 { name -> println name }
            |               .each2 { someName ->
            |                   println someName // <-- fails on this line, but it will pass if line is commented out.
            |               }
            |               .each3 { 
            |                   name -> println name // <-- does not fail here
            |               }
        '''.stripMargin()
        assertNoViolations(SOURCE)
    }
```

From the user's perspective, there is no reason for indentation to fail for the `each2` method, but it still does. I tried to make some reasoning about this via debugging, and it looks to me that potential problems might be in `isChainedMethodCallOnDifferentLine()` which will return `true` for `each3` but `false` for `each2`. I'm positive this is not the whole story, but maybe it might help.

Tnx.

**Comment by dmurat** [comment]
I just realized that my last example is not correct. It should be

```
    @Test
    void test_MethodChaining_MultilineClosureParameter_AnotherExample() {
        final SOURCE = '''
            |buildFileList().collect { item -> 
            |                   item.name 
            |               }
            |               .each1 { name -> println name }
            |               .each2 { someName ->
            |                   println someName
            |               }
            |               .each3 { name -> 
            |                   println name 
            |               }
        '''.stripMargin()
        assertNoViolations(SOURCE)
    }
```
With this corrected code, CodeNarc fails consistently for all three methods: `collect`, `each2`, and `each3`. So my attempt of analysis is flawed. 

Anyway, I hope it is clearer now what I would like to have. I don't really know if it is possible, though.

Tnx.

**Comment by dmurat** [comment]
If of any help, here are some related tests. `Style2` test is failing.

```
    @Test
    void test_MethodChaining_MultilineClosureParameter_Style1() {
        final SOURCE = '''
            |buildFileList()
            |        .collect { item -> 
            |            item.name 
            |        }
            |        .each1 { name -> println name }
            |        .each2 { someName ->
            |            println someName
            |        }
            |        .each3 { name -> 
            |            println name 
            |        }
        '''.stripMargin()
        assertNoViolations(SOURCE)
    }

    @Test
    void test_MethodChaining_MultilineClosureParameter_Style2() {
        final SOURCE = '''
            |buildFileList().collect { item -> 
            |                   item.name 
            |               }
            |               .each1 { name -> println name }
            |               .each2 { someName ->
            |                   println someName
            |               }
            |               .each3 { name -> 
            |                   println name 
            |               }
        '''.stripMargin()
        assertNoViolations(SOURCE)
    }

    @Test
    void test_MethodChaining_MultilineClosureParameter_Style3() {
        final SOURCE = '''
            |buildFileList().collect { item -> 
            |            item.name 
            |        }
            |        .each1 { name -> println name }
            |        .each2 { someName ->
            |            println someName
            |        }
            |        .each3 { name -> 
            |            println name 
            |        }
        '''.stripMargin()
        assertNoViolations(SOURCE)
    }
```

**Comment by chrismair** [comment]
The *Indentation* rule started out simple and has become a complicated assortment of special cases. I don't expect to be able to handle style 2, where the indentation is just based on lining up the dots.

**Comment by dmurat** [comment]
After looking more closely at source code, I might have idea of how this can be achieved. If I manage to allocate some time for working on a potential PR, would you consider it? Or you think there is no point complicating `IndentationRule` any further?

**Comment by chrismair** [comment]
Yes, I would consider it, as long as it was maintainable and did not add too much complexity. Perhaps you could describe your intended approach before going too far down that path?

**Comment by dmurat** [comment]
Basic idea is to remember the column number of a method containing a closure with a block, and then use it to add more allowed columns in the flexible check for column number.

I come up with a very rough working draft to illustrate the idea: https://github.com/dmurat/CodeNarc/commit/8d903988763f8b278cde540cfb34d7ce63ec8e96

I'm not quite sure about allowing additional columns in all cases. I think it would be better to limit them somehow for that "style 2 special case".

**Comment by chrismair** [comment]
Okay, that looks relatively straightforward. Some initial comments:
 - What about if/when `methodColumnForBlock[block]` is null? It seems like `allowedColumns` should not be amended in that case.
 - It looks like `recordMethodColumnForClosureBlocks` can be a void method
 - Add a test for violations for Style2 -- when such method calls are at the wrong column

This change would not go in until the next release (which is probably 2.0), in ~ 6 months or so.

**Comment by dmurat** [comment]
Tnx for your comments. I will try to address them in more thorough PR as soon as I can.

The release schedule is not a problem. Actually I'm thinking about writing an article about using unreleased dependencies via jitpack.io. This issue might be a great showcase :-) We will see...

**Comment by dmurat** [comment]
If you have time, please take a look at this branch - https://github.com/dmurat/CodeNarc/tree/methodChainingIndentationImprovements

The functionality is complete. I just don't have time right now for writing a full PR description. I will submit PR soon.
