### ISSUE TITLE
Groovy 3 - SpaceAfterOpeningBrace rule dow not work with closures using lambda syntax

### ISSUE THREAD

**Issue by dmurat** [CodeNarc/CodeNarc#511]
With Groovy 3, I'm having issues with `SpaceAfterOpeningBrace` rule for closures that use newly supported Java lambda syntax.

Since the code of the rule is not very complex, I did manage to adapt the rule to work with lambdas by changing `SpaceAfterOpeningBraceAstVisitor.visitClosureExpression()`:

    @Override
    void visitClosureExpression(ClosureExpression expression) {
        isFirstVisit(expression.code)   // Register the code block so that it will be ignored in visitBlockStatement()
        if (isFirstVisit(expression)) {
            def line = sourceLineOrEmpty(expression)
            def startCol = expression.columnNumber
            boolean ignore = false

            if (isLambdaExpression(expression)) {
                int indexOfOpeningBrace = line.indexOf("{")

                if (indexOfOpeningBrace == -1) { // Lambdas without parenthesis
                    ignore = true
                }
                else {
                    startCol = indexOfOpeningBrace + 1
                }
            }

            if (!ignore && isNotWhitespace(line, startCol + 1) && checkIsEmptyBlock(line, startCol + 1)) {
                addOpeningBraceViolation(expression, 'closure')
            }
        }
        super.visitClosureExpression(expression)
    }

    boolean isLambdaExpression(ClosureExpression closureExpression) {
        return closureExpression.getClass().name == "org.codehaus.groovy.ast.expr.LambdaExpression"
    }

Added test in `SpaceAfterOpeningBraceRuleTest` is here:

    @Test
    void testApplyTo_ClosureWithLambdaSyntax_NoViolations() {
        final SOURCE = '''
            def myClosure = () -> println "bla"
            myClosure = () -> { println "bla" }
            myClosure = () -> { }
            myClosure = () -> { 
              println "bla" 
            }
            myClosure = (def param1) -> { println "bla" }
            myClosure = param1 -> { println "bla" }
            myClosure = param1 -> println "bla"
            myClosure = (def param1, def param2) -> { println "bla" }
        '''

        assertNoViolations(SOURCE)
    }

The test will only work with Groovy 3 in runtime, which requires some `build.gradle` modifications:

    ...
    def groovyTestVersion = '3.0.4'

    dependencies {
        ...
        testRuntimeOnly("org.codehaus.groovy:groovy:$groovyTestVersion")
        testRuntimeOnly("org.codehaus.groovy:groovy-xml:$groovyTestVersion")
        testRuntimeOnly("org.codehaus.groovy:groovy-json:$groovyTestVersion")
        testRuntimeOnly("org.codehaus.groovy:groovy-ant:$groovyTestVersion")
        testRuntimeOnly("org.codehaus.groovy:groovy-templates:$groovyTestVersion")
    }

I'm aware this is an ad-hoc solution, so it might not be appropriate if there is (or will be) some better way for supporting backward-incompatible syntax from Groovy 3. If this is the case, it will be great if you can elaborate a bit (or maybe point me to some docs).

Tnx

**Comment by chrismair** [comment]
Thanks for the detailed test case and potential fix. I used it pretty much exactly.
