### ISSUE TITLE
Consider adding an option in DuplicateStringLiteral for ignoring strings in annotation attributes

### ISSUE THREAD

**Issue by dmurat** [CodeNarc/CodeNarc#512]
I think it will be very useful to add an option in the `DuplicateStringLiteral` rule for ignoring strings used in annotation attributes, if possible.

Many popular APIs (bean validation, JPA, Spring/Spring Boot, etc.) heavily rely on annotations and is quite common to use strings directly in annotation attributes without extracting them into constants. In addition, Groovy did have problems if anything but literal constants is used as annotation attributes (https://issues.apache.org/jira/browse/GROOVY-3278), although this is not a problem anymore for the latest Groovy 2.5.x and Groovy 3 versions.

Tnx.

**Comment by chrismair** [comment]
Can you provide some sample code that causes an unwanted violation.

**Comment by dmurat** [comment]
I was too quick with my conclusions. Sorry about that. Originally I thought that all annotations are affected including those that have attributes with a single literal as a value. It is not true. But annotations that contain attributes with a list as a value are indeed affected. Original code that I'm having a problem with is this:

```
@SpringBootApplication
@EnableJpaRepositories(basePackages = ["org.klokwrk.cargotracker.booking.queryside.rdbms.projection.domain.querymodel"])
@EntityScan(basePackages = ["org.axonframework.eventhandling.tokenstore.jpa", "org.klokwrk.cargotracker.booking.queryside.rdbms.projection.domain.querymodel"])
@CompileStatic
class BookingQuerySideRdbmsProjectionApplication {
  static void main(String[] args) {
    SpringApplication.run(BookingQuerySideRdbmsProjectionApplication, args)
  }
}
```

Here, literals in a list of `basePackage` attribute are repeated, which triggers DuplicateStringLiteral rule violation. This can be confirmed with the following test that I added in `DuplicateStringLiteralRuleTest`:

```
    @Test
    void testInAnnotation_NoViolation() {
        final SOURCE = '''
            @MyAnnotation1StringValue("string1")
            @MyAnnotation2StringValue("string1")
            class MyClass1 {
            }

            @MyAnnotation1ListValue(value = ["string1"])
            @MyAnnotation2StringValue("string1")
            class MyClass2 {
            }
            
            @MyAnnotation1ListValue(value = ["string1", "string2"])
            @MyAnnotation2ListValue(value = ["string3", "string4"])
            class MyClass3 {
            }
        '''

        assertNoViolations(SOURCE)
    }

    @Test
    void testInAnnotation_MultivalueAttributes_NoViolation() {
        final SOURCE = '''
            @MyAnnotation1ListValue(value = ["string1"])
            @MyAnnotation2ListValue(value = ["string1", "string2"])
            class MyClass1 {
            }

            @MyAnnotation1ListValue(value = ["string10", "string11"])
            @MyAnnotation2ListValue(value = ["string11", "string10"])
            class MyClass2 {
            }
        '''

        assertNoViolations(SOURCE)  // <-- I think there should not be any violation
//        assertViolations(SOURCE,  // <-- current state
//                [lineNumber: 3, sourceLineText: '@MyAnnotation2ListValue(value = ["string1", "string2"])', messageText: 'Duplicate String Literal: string1'],
//                [lineNumber: 8, sourceLineText: '@MyAnnotation2ListValue(value = ["string11", "string10"])', messageText: 'Duplicate String Literal: string11'],
//                [lineNumber: 8, sourceLineText: '@MyAnnotation2ListValue(value = ["string11", "string10"])', messageText: 'Duplicate String Literal: string10'])
    }
```

I believe that `DuplicateStringLiteralRule` intention is to ignore values of annotation attributes. If this is the case, then I managed to fix the above situation with simple addition in `DuplicateLiteralAstVisitor`:

```
...
class DuplicateLiteralAstVisitor extends AbstractAstVisitor {
...
    @Override
    void visitAnnotations(AnnotatedNode node) {
        // Skip annotation.
    }
...
}
```

Although I didn't try, I believe the same discussion and the fix pertain to the `DuplicateNumberLiteralRule` rule.

Tnx.

**Comment by chrismair** [comment]
Ignore duplicate values in annotations for **DuplicateStringLiteral** and **DuplicateNumberLiteral** rules.

**Comment by chrismair** [comment]
And thanks for the detailed tests, and bonus points for pointing out the fix.
