### ISSUE TITLE
Invalid SpaceAroundOperator warning since 1.6

### ISSUE THREAD

**Issue by paplorinc** [CodeNarc/CodeNarc#521]
See: https://github.com/CodeNarc/CodeNarc/commit/e6f5050dce39d9c6827c133d96822acc6a9d0ffe#r39859688

Example Groovy failure:
```groovy
(condition
  ? "a:b"
  : 'c:d'
)
```

**Comment by chrismair** [comment]
Can you please provide some sample code that causes the invalid violation.

**Comment by chrismair** [comment]
Or is that what you added over in #507?

**Comment by paplorinc** [comment]
Yes, added simplified example based on our failures
