### ISSUE TITLE
CodeNarc should provide an option for a specific list of files to lint

### ISSUE THREAD

**Issue by nre-ableton** [CodeNarc/CodeNarc#530]
One of the main repositories at my company is rather large; on disk, the project contains roughly 100,000 files if one naively runs `find . -type f | wc -l`. However, there is only one file we are interested in linting with CodeNarc, the top-level `Jenkinsfile`. The command that ends up being executed is this:

> `java -classpath <snip> org.codenarc.CodeNarc -rulesetfiles=ruleset.groovy -report=xml:codenarc-report.xml -includes=./Jenkinsfile

Especially when run from Docker, this can be quite slow (roughly 5 minutes on a reasonably fast machine) Even when setting `-includes=does-not-exist`, it takes the nearly the same amount of time. I guess this is because the entire directory needs to be scanned even if `includes` is just a single file, since technically it's an Ant include pattern.

I wish that CodeNarc provided a separate option to take a specific list of files and not scan an entire directory. This way, one could use `git ls-files`, `locate`, or a hardcoded list of known files instead. Is this feasible to implement?

**Comment by chrismair** [comment]
Hmmm, I'd be interested to see whether running CodeNarc using the [Ant Task](https://codenarc.github.io/CodeNarc/codenarc-ant-task.html) or [like a JUnIt test using Ant](https://codenarc.github.io/CodeNarc/codenarc-run-as-a-test.html), would be faster. That uses a different, Ant-optimized source analyzer. The FilesystemSourceAnalyzer used by the command-line runner does iterate through all files.

**Comment by nre-ableton** [comment]
Unfortunately I don't have an easy way to test this with our CI setup, so I'm not sure I can do a proper benchmark for you. However, the fact that `FilesystemSourceAnalyzer` iterates through all the files as you say does sound suspicious.

**Comment by chrismair** [comment]
I believe this feature is provided in #717

**Comment by nre-ableton** [comment]
@chrismair Great! Looking forward to seeing a release with this fix included.

**Comment by chrismair** [comment]
This was available in CodeNarc 3.2.0.
