### ISSUE TITLE
Maven project failure: Failed to parse plugin descriptor for org.codenarc:CodeNarc:1.6

### ISSUE THREAD

**Issue by Avra-P** [CodeNarc/CodeNarc#531]
Hello,

I am trying to introduce CodeNarc in a maven(3.6.2) /groovy (2.5.7) project (which already has Slf4j v. 1.7.28 ), and I encounter a problem with the the jar i am trying to resolve it as a build plugin.
After reading the repo's readme and releases, I see that I am looking for  `groupId = org.codenarc , artifactId = CodeNarc`, with version 1.6 as the latest.
The Maven Central Repository [link](http://repo1.maven.org/maven2/org/codenarc/CodeNarc/) in [main site's page](https://codenarc.github.io/CodeNarc/) is not valid fyi,  so i searched it a bit and found [this artefact link](https://mvnrepository.com/artifact/org.codenarc/CodeNarc).
I tried to use it in my project's `pom.xml` file, with following snippet:
```
   <plugin>
                <groupId>org.codenarc</groupId>
                <artifactId>CodeNarc</artifactId>
                <version>1.6</version>
                <configuration>
                    <rulesetfiles>file:${project.basedir}/RuleSet</rulesetfiles>
                    <sourceDirectory>${project.basedir}/src</sourceDirectory>
                    <maxPriority1Violations>0</maxPriority1Violations>
                    <maxPriority2Violations>0</maxPriority2Violations>
                    <maxPriority3Violations>0</maxPriority3Violations>
                    <outputDirectory>${project.basedir}/target/codenarchtml</outputDirectory>
                    <xmlOutputDirectory>${project.basedir}/target/codenarcxml</xmlOutputDirectory>
                </configuration>
                <executions>
                    <execution>
                        <id>groovy-sources</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>codenarc</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```
but when i tried to run any mvn command, eg `mvn verify` after the phase I configured it, there's an error regarding artefact's descriptor:
```
Failed to parse plugin descriptor for org.codenarc:CodeNarc:1.6 ({mypath}/.m2/repository/org/codenarc/CodeNarc/1.6/CodeNarc-1.6.jar): No plugin descriptor found at META-INF/maven/plugin.xml -> [Help 1
```

Fyi i have seen [this plugin](https://github.com/gleclaire/codenarc-maven-plugin), which i successfully imported in my project, but it has not been maintained since 2015 so I want to avoid it if possible.

If I am doing something wrong with plugin's usage in my project, I would really appreciate any help to point me to the right direction.
Thank you in advance :)

**Comment by chrismair** [comment]
I will make a note to update the broken Maven Central Repo link on the CodeNarc home page.

But the main CodeNarc project does not provide a Maven plugin. That codenarc-maven-plugin is a separate project -- I'm not aware of its current status. Hmmm, looks like that Maven plugin does not work with Groovy 2.5, at least according to:
<https://github.com/gleclaire/codenarc-maven-plugin/issues/23> and
<https://stackoverflow.com/questions/57576796/how-to-use-codenarc-maven-plugin-with-groovy-2-5>

**Comment by Avra-P** [comment]
ll try to use the `codenarc-maven-plugin` although it is not really safe, since it is not maintained. It seems to work with groovy 2.5.7 , although i am not sure if more issues come up.

I am aware that the main codenarc project is not supporting the maven plugin, my question was mostly regarding 1.6 maven jar found in maven's central repo:  
https://mvnrepository.com/artifact/org.codenarc/CodeNarc/1.6, if someone here is aware if and how it can be used, since it is recent.

Thank you for your response 💪

**Comment by chrismair** [comment]
Feel free to reopen if needed.
