### ISSUE TITLE
Command line instructions do not work out of box.

### ISSUE THREAD

**Issue by macetw** [CodeNarc/CodeNarc#533]
I was unable to run codenarc following the instructions posted. Here is my script:
```#!/bin/bash

set -e

# Sources:
# wget https://repo1.maven.org/maven2/org/codehaus/groovy/groovy-all/1.5.6/groovy-all-1.5.6.jar
# wget https://github.com/CodeNarc/CodeNarc/releases/download/v1.6/CodeNarc-1.6.jar
# wget https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar
 
export GROOVY_JAR=~/lib/groovy-all-1.5.6.jar
java -classpath $GROOVY_JAR:~/lib/CodeNarc-1.6.jar:~/lib/slf4j-api-1.7.25.jar:lib org.codenarc.CodeNarc
```
Adapted from:
https://codenarc.github.io/CodeNarc/codenarc-command-line.html

This was my result:
```
macetw@tmace-t5820:~/code$ codenarc .
Error: Could not find or load main class org.codenarc.CodeNarc
```
I am on ubuntu 18 with 1.8.0.252 Java
```
$ java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~16.04-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
$ uname -a
Linux tmace-t5820 4.15.0-101-generic #102~16.04.1-Ubuntu SMP Mon May 11 11:38:16 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by nvuillam** [comment]
You can try [npm-groovy-lint](https://github.com/nvuillam/npm-groovy-lint), embedding CodeNarc 1.5 (upgrade to CodeNArc 1.6 in progress), if it does not work out of the box (should not happen) , please post an issue :)

https://github.com/nvuillam/npm-groovy-lint

**Comment by macetw** [comment]
I have already tried npm-groovy-lint, and it is not running reliably, which is why I was scaling back to these instructions I linked to. My issue with npm-groovy-lint would be a separate issue maybe with a different project. I'd rather focus on this. Either the instructions are wrong or incomplete that they are not working for me.

**Comment by nvuillam** [comment]
If you prefer to directly use CodeNarc, you should try a more recent version of Groovy and use such CLASSPATH

Example: 

`CodeNarc-1.6.jar groovy/lib/groovy-3.0.5.jar groovy/lib/groovy-templates-3.0.5.jar groovy/lib/groovy-xml-3.0.5.jar groovy/lib/groovy-json-3.0.5.jar groovy/lib/groovy-ant-3.0.5.jar groovy/lib/ant-1.10.8.jar groovy/lib/ant-launcher-1.10.8.jar slf4j-api-1.7.9.jar log4j-slf4j-impl-2.13.0.jar log4j-api-2.13.0.jar log4j-core-2.13.0.jar GMetrics-0.7.jar`

If you see issues in npm-groovy-lint, i'm interested that you post them [there](https://github.com/nvuillam/npm-groovy-lint/issues) :)
