### ISSUE TITLE
UnnecessarySemiColon not detected when there is a space between code and semicolon

### ISSUE THREAD

**Issue by nvuillam** [CodeNarc/CodeNarc#534]
Since CodeNarc 1.6, it seems there has been a regression with UnnecessarySemiColon rule

In the following example, only the first and the last lines UnnecessarySemiColon rules are catched, the second line is ignored because there is a **space** between **String** and **;**

```
package my.company.server;
import java.lang.String ;    
println("test");
```

**Comment by chrismair** [comment]
Okay, we significantly redesigned (and simplified) that rule for 1.6, so I'm not too surprised. I'll take a look. Thanks.

**Comment by nvuillam** [comment]
Will it be possible to create a patch ?
I can't upgrade npm-groovy-lint to CodeNarc 1.6 without this fix :/

**Comment by chrismair** [comment]
Ugh, please help me understand why that particular regression prevents upgrading. It is a false negative, not a false positive, so I was assuming/hoping the impact was minimal. Can you do a workaround until 2.0?

**Comment by nvuillam** [comment]
In the JS layer, npm-groovy-lint can use the returned CodeNarc violations to format and auto-fix issues when possible

If CodeNarc does not return a violation, it means I can't auto-fix it, and UnnecessarySemiColon is one of the "Best Sellers" for users, so it would be a visible regression

My alternatives could be:

- add a lint layer on my side (but npm-groovy-lint aims to embed CodeNarc and propose fixes, not to be a core linter itself)

- create myself a CodeNarc jar, meaning embedding and distributing an unofficial release of CodeNarc (I don't like this idea, this is more clean to use official releases of CodeNarc, and i don't aim yo maintain a fork)

Maybe you have a third option to propose ?

Maybe an 1.7-alpha.1 that I could use ?

**Comment by chrismair** [comment]
I have to admit I do not fully appreciate why that tiny sub-scenario (of a space before the semicolon) would prevent upgrading the entire release, but you know your code and use-cases better than I do. Is it because it breaks some of your test cases, or is that your existing users would prefer that (presumably) tiny use case be supported rather than upgrading? I guess it seems like it should not be a big deal to have this minor known issue for a few months until 2.0 comes out.

But I am open to trying to work this in if it is not feasible to work around.

**Comment by nvuillam** [comment]
It breaks several of my test methods, where I count the number of auto-fixed problems, and I also have similar test methods in VsCode Groovy Lint.

So i would have to change all the tested numbers... and change them back later... 

In a more generic way, i don't like to announce a major upgrade containing easy-to-spot regressions , and the groovy formatter using CodeNarc needs to format correctly !

I release versions of my packages almost every time there is a PR, and it's safe thanks to all the test classes, is there a particular reason that CodeNarc released are only every few months ? 
As everything is automated and tested, it would look safe to work in "Continuous Delivery" mode :)

**Comment by chrismair** [comment]
CodeNarc is closer to the "release train" regular cadence approach like Java and Eclipse. Yes, we could do more often, but there are trade-offs with both more frequent releases and less frequent. My previous job was in an enterprise environment with around 30 Groovy applications, across different teams and leads. Upgrading dependencies was a more involved process, so frequent updates were not always welcome. And there are several downstream projects, like the Grails 2.x plugin, that would be compelled to then upgrade their own CodeNarc dependency to keep up. Trade-offs, as always.

Okay, I'll try to look into that fix and possibly a patch.

**Comment by nvuillam** [comment]
I think i read somewhere that you plan to use semver for CodeNarc 2.0, it seems a great idea, because with such version numbering it would allow dependents to know when an upgrade can be done in 5 minutes or requires more qualification :)

In our case, a quick fix released with just an upgrade of the last number would be painless because dependents know that ascending compatibility is assured

Many thanks for the debug and patch from myself but also from the average 3000 monthly users of VsCode Groovy Lint (15k installs) , and also from the users using npm-groovy-lint (1k downloads/week, and there will be more and more thanks to the inclusion of npm-groovy-lint performed by github engineering team in [github super linter](https://github.blog/2020-06-18-introducing-github-super-linter-one-linter-to-rule-them-all/) :) )

Damn, i love open source ❤️

**Comment by chrismair** [comment]
So far I am unable to reproduce, either in *master* or in a branch off *v1.6*. This new test passes in both:
```
    @Test
    void test_SpaceBeforeSemicolon() {
        final SOURCE = '''
            package my.company.server ;
            import java.lang.String ;
            println("test") ;
        '''
        assertViolations(SOURCE,
                [lineNumber:2, sourceLineText:'package my.company.server ;', messageText:MESSAGE],
                [lineNumber:3, sourceLineText:'import java.lang.String ;', messageText:MESSAGE],
                [lineNumber:4, sourceLineText:'println("test") ;', messageText:MESSAGE]
        )
    }
```
I also tried removing the space before the semicolon in lines 2 and 4, so it matches your example exactly, but it still passes.

**Comment by nvuillam** [comment]
That's strange... i'll try to provide you an example with the result as command line

**Comment by chrismair** [comment]
Just tried with Groovy 3.0.x and that test failed. Okay, I'll look into that.

**Comment by nvuillam** [comment]
Mystery solved , well done !
I'm embedding Groovy 3.0.5 because people working on Jenkinsfile does not always have Groovy installed on their computer :)

**Comment by chrismair** [comment]
Okay, CodeNarc v1.6.1 is now available, containing that fix. Give it a try, when you get a chance.

**Comment by nvuillam** [comment]
Where can I find the 1.6.1 jar ?
I don't see it on [maven](https://mvnrepository.com/artifact/org.codenarc/CodeNarc) and the [github releases page](https://github.com/CodeNarc/CodeNarc/releases) seems to contain only sources for 1.6.1 ( but not the artefacts )

Thanks !

**Comment by chrismair** [comment]
It often takes several hours for it to show up on those MVN Repo search pages, but I was able to pull it in as a dependency a couple hours ago. And I just added a GitHub Release for it as well.

**Comment by nvuillam** [comment]
That works GREAT, thanks !  👍 

And I don't know what you did, but the performances are dramatically improved !

- With CodeNarc 1.5 :  

![image](https://user-images.githubusercontent.com/17500430/89168587-5b714680-d57d-11ea-9133-959a5ce96d38.png)

- With CodeNarc 1.6.1 (+ use of CodeNarc Json console output instead of parsing XML result files) : 

![image](https://user-images.githubusercontent.com/17500430/89168632-6f1cad00-d57d-11ea-8edb-ff558dd95769.png)
