### ISSUE TITLE
DuplicateStringLitteral duplicateStringsMinimumLength parameter

### ISSUE THREAD

**Issue by nvuillam** [CodeNarc/CodeNarc#541]
DuplicateStringLitteral allows to define a list of ignored strings.
I think it would be nice to be able to define the following parameter :
- `duplicateStringsMinimumLength`

Example:
`duplicateStringsMinimumLength: 10`

Lots of short duplicate string values can be 'true', 'false', 'DEBUG:', 'none', 'all' etc ... the user should have the choice to ignore them without manually listing all the short words that can be used in a clean groovy code

**Comment by chrismair** [comment]
Let's please spell out "Min" to "Minimum".

**Comment by nvuillam** [comment]
edited :)

**Comment by nvuillam** [comment]
I'm currently implementing the feature
