### ISSUE TITLE
DuplicateNumberLitteral : new parameter duplicateNumbersMinimumValue

### ISSUE THREAD

**Issue by nvuillam** [CodeNarc/CodeNarc#542]
DuplicateNumberLitteral allows to define a list of ignored numbers.
I think it would be nice to be able to define the following parameter :
- `duplicateNumbersMinimumValue`

Example:
`duplicateNumbersMinimumValue: 10`

Lots of duplicate number values can be -1,-2,3,4,5 the user should have the choice to ignore them without manually listing all the numbers that can be used in a clean groovy code

**Comment by chrismair** [comment]
Let's please spell out "Min" to "Minimum".

**Comment by nvuillam** [comment]
Edited :)

**Comment by nvuillam** [comment]
I'm currently implementing the feature
