### ISSUE TITLE
DuplicateStringLiteral: Please add documentation for configuration with empty String

### ISSUE THREAD

**Issue by cristalp** [CodeNarc/CodeNarc#543]
I just had a moment of head-scratching regarding the configuration of DuplicateStringLiteral. The thing is that we have a lot of single characters like a comma or a space that we don't want to have as duplicate String literal.

And the same goes for empty Strings. But the configuration I tried first didn't work:

```
  DuplicateStringLiteral {
    ignoreStringsDelimiter = '|'
    ignoreStrings = '-|_|/|$|.|:| |,||'
  }
```

That didn't work, but only by looking at the source and creating a test I found the correct configuration:

```
  DuplicateStringLiteral {
    ignoreStringsDelimiter = '|'
    ignoreStrings = '||-|_|/|$|.|:| |,|'
  }
```

Perhaps that would be helpful in the documentation, even though it may be obvious for others   :-)

**Comment by l-1squared** [comment]
Hi, 
I am sorry to respond comparatively late to your issue. 
I think it is in general better to have more documentation, so I will try to incorporate your suggestion.
However, I am right now busy with the build system, so implementation might take a while.

Greetings,
l-1squared

**Comment by cristalp** [comment]
Hi

Thanks for your answer, I look forward to the added documentation!

Best regards,
Eric

Von: Kristof <notifications@github.com>
Gesendet: Mittwoch, 12. August 2020 16:55
An: CodeNarc/CodeNarc <CodeNarc@noreply.github.com>
Cc: Lewis, Eric <Eric.Lewis@ipi.ch>; Author <author@noreply.github.com>
Betreff: Re: [CodeNarc/CodeNarc] DuplicateStringLiteral: Please add documentation for configuration with empty String (#543)


Hi,
I am sorry to respond comparatively late to your issue.
I think it is in general better to have more documentation, so I will try to incorporate your suggestion.
However, I am right now busy with the build system, so implementation might take a while.

Greetings,
l-1squared

**Comment by chrismair** [comment]
This rule ignores (zero-length) empty strings. I will add a note to the documentation about that.

I also added a test for those single-char strings:
<https://github.com/CodeNarc/CodeNarc/blob/master/src/test/groovy/org/codenarc/rule/dry/DuplicateStringLiteralRuleTest.groovy#L286>

Suggestions or PRs are welcome if you have a better way to document that.

The next release of CodeNarc (v2.0.0) also adds a `duplicateStringMinimumLength` property to the rule, so you could optionally set that to `2` and then the rule would ignore single-character strings.

**Comment by cristalp** [comment]
Thanks a lot for your great work!
