### ISSUE TITLE
VariableName rule incorrectly flags fields marked with the `@Field` annotation

### ISSUE THREAD

**Issue by nre-ableton** [CodeNarc/CodeNarc#561]
In singleton classes (such as those used by Jenkins pipelines), fields must be marked with `@Field` (provided by `groovy.transform.Field`). The following code is treated as a violation of the `VariableName` rule:

```groovy
import groovy.transform.Field

@Field static final String FOO_BAR = 'something'
```

This results in:

> `ERROR vars/foo.groovy:3: VariableName: Variable named FOO_BAR in class None does not match the pattern [a-z][a-zA-Z0-9]*`

`static final` fields in regular classes are of course processed correctly. Related to https://github.com/CodeNarc/CodeNarc/issues/467.

**Comment by chrismair** [comment]
Changed the **VariableName** rule to ignore variables with the `@Field` annotation.
