### ISSUE TITLE
UnnecessarySubstring is unsafe; should be deprecated

### ISSUE THREAD

**Issue by bernhof** [CodeNarc/CodeNarc#562]
With reference to old issue from sourceforge: https://sourceforge.net/p/codenarc/bugs/98/

[UnnecessarySubstring](https://codenarc.org/codenarc-rules-unnecessary.html#unnecessarysubstring-rule) warns about all uses of `String.substring`, but replacing with range fails if string's length is 1.

```
String input = "/"
input.substring(1) // works
input[1..-1] // fails
input.substring(0, input.size() - 1) // works
input[0..-2] // fails
```

https://groovyconsole.appspot.com/script/5161322018766848

**Comment by chrismair** [comment]
Okay, so I guess we should consider removing/disabling the check for `substring(int, int)`.

**Comment by bernhof** [comment]
Yes and for `substring(int)`, too.

**Comment by chrismair** [comment]
I have deprecated the **UnnecessarySubstring** rule.
