### ISSUE TITLE
@Library triggers several false rules violations

### ISSUE THREAD

**Issue by DrStrangepork** [CodeNarc/CodeNarc#563]
The very first line in all our Jenkinsfiles is this:

    @Library('utils@master') _

This line triggers several CodeNarc rules - UnusedVariable, VariableName, CompileStatic, NoDef, and VariableTypeRequired - none of which are actual issues. Is there a way to exempt a line starting with '@Library' or perhaps disable all rules "for the following line"?

**Comment by chrismair** [comment]
If you have upgraded to CodeNarc 2.x, you can add a `codenarc-disable-line` comment on that same line.

See [Disabling Rules From Comments](https://codenarc.org/codenarc-configuring-rules.html#disabling-rules-from-comments).

**Comment by DrStrangepork** [comment]
I am using CodeNarc via npm-groovy-lint, and I found the solution there in CodeNarc 1.6.1.
