### ISSUE TITLE
How can I use the Coupling Metrics from GMetrics?

### ISSUE THREAD

**Issue by joasgarcia** [CodeNarc/CodeNarc#572]
For examples:
- https://dx42.github.io/gmetrics/metrics/AfferentCouplingMetric
- https://dx42.github.io/gmetrics/metrics/EfferentCouplingMetric

**Comment by chrismair** [comment]
There is no current way to use those from within CodeNarc. Those are package-level metrics, and so far CodeNarc is really more file-based.
