### ISSUE TITLE
Add NoBlankLineBeforeAnnotatedField rule

### ISSUE THREAD

**Issue by erdi** [CodeNarc/CodeNarc#582]
It should raise violations when there is no blank line before a field declaration that uses annotations.

Example violations:
```
    class MyClass {
        // No violations for field declarations preceded by a comment
        @Delegate
        AutoCloseable stream
        
        String publicField                  // violation
        @PackageScope
        String packageScopedField
    }
```

**Comment by chrismair** [comment]
I renamed `NoBlankLineBeforeAnnotatedField` rule to `MissingBlankLineBeforeAnnotatedField` to be consistent with the other "MissingXxx" rules in the same ruleset.

**Comment by erdi** [comment]
Makes sense.
