### ISSUE TITLE
Add MethodCallNameTrailingWhitespace rule

### ISSUE THREAD

**Issue by erdi** [CodeNarc/CodeNarc#586]
The rule should check that there is no trailing whitespace in the method name when a method call contains parenthesis or that there is at most one space after the method name if the call does not contain parenthesis.

Examples of violations:

```
    aMethod ("arg") //violation
    
    aMethod  "arg" //violation
    
    throw new Exception () //violation
    
```

**Comment by chrismair** [comment]
There ended up being some test failures and 23 false positives ("_There is whitespace between super and parenthesis in a constructor call_") against other CodeNarc source files, when running under Groovy 3.0.7. I adjusted the rule logic so the tests would pass under both Groovy 2.5 and 3.0. Feel free to make changes if you have a better or more robust way to fix that.

**Comment by erdi** [comment]
Your changes look sensible to me and as long as the tests pass on both versions then we're fine as far as I'm concerned.

One cool thing to have would be to adjust the build so that tests also run using Groovy 3 so that contributors are told straight away that their tests are not passing on that version.

**Comment by chrismair** [comment]
> One cool thing to have would be to adjust the build so that tests also run using Groovy 3

Agreed.
