### ISSUE TITLE
Is there is a way to invert rule via configuration?

### ISSUE THREAD

**Issue by rabits** [CodeNarc/CodeNarc#591]
Hello floks,

Checked the rules configs and not found an ability to invert the rule - only `enabled` is here... For example I want to enforce the next syntax:
```
if( true ) {
}
```
so I need to invert `SpaceAfterIfRule` and probably introduce a couple of other rules that will check that I have spaces in the round brackets.

**Comment by chrismair** [comment]
No, there is no built-in way to "invert" a rule. That would require adding extra flags and logic to the existing rule to support the opposite behavior (or else new rules). And what you describe would include a new rule, I think, to check for the space after the opening parentheses and before the closing parentheses -- which is not covered by the existing **SpaceAfterIf** rule.

**Comment by rabits** [comment]
Hmmm, so for the most of the rules we need to have quite the same rules with "Not" prefix? I think since the rule is binary (true/false) - it could be easily inverted: because basically what the NotSpaceAfterIf rule will do - is to search the same and invert the result.

For sure there will be additional logic to allow such behavior as inversion - but it will save ton of time on developing the inverted rules and increase the configuration simplicity. Maybe it's worth it?

**Comment by rabits** [comment]
Checked the logic - and looks like it will be not so easy to implement, as I expected...

**Comment by chrismair** [comment]
I added an issue to create new rules for parentheses: #592: "New SpaceAfterOpeningParenthesis and SpaceBeforeClosingParenthesis rules".

**Comment by chrismair** [comment]
You can open issues, and optionally submit PRs, for adding support to individual rules, or add new rules. I'm closing this issue, but feel free to reopen if you want to continue the discussion.

**Comment by rabits** [comment]
Yeah, I checked the amount of efforts to make it work properly for me - and it's too much, sorry.
