### ISSUE TITLE
[bug] Backslash in UnnecessaryGString causes Triple Double-Quote String to incorrectly be fixed to Triple Single-Quote breaking interpolation

### ISSUE THREAD

**Issue by darthwalsh** [CodeNarc/CodeNarc#597]
Starting code

```groovy
def path = "C:\\b"

def a = 'a'

def b = """
  ${a}
"""
```

Run `npm-groovy-lint --fix`

### Actual:
```groovy
def path = "C:\\b"

def a = 'a'

def b = '''
  ${a}
'''
```

The string has changed to single-quote, breaking interpolation.

### Expected
```groovy
def path = "C:\\b"

def a = 'a'

def b = """
  ${a}
"""
```

### Workaround
Fixing the `UnnecessaryGString` with `def path = 'C:\\b'` means the bug will not be triggered

**Comment by chrismair** [comment]
CodeNarc produces the following violation on the original code above:
```
Violation[rule=UnnecessaryGStringRule[name=UnnecessaryGString, priority=3], lineNumber=2, sourceLine=def path = "C:\b", message=The String 'C' can be wrapped in single quotes instead of double quotes]
```

That top source line ends up including the ascii backspace escape `\b` when rendered by the Groovy AST (`ConstantExpression.value`) -- which is what CodeNarc uses to build that violation message. I would be surprised if that affected npm-groovy-lint, but I am not sure.

It sounds like npm-groovy-lint is fixing the wrong source line. I suggest opening an issue with npm-groovy-lint.

**Comment by chrismair** [comment]
Feel free to reopen if needed.
