### ISSUE TITLE
Grammar error in project motto/logo

### ISSUE THREAD

**Issue by nre-ableton** [CodeNarc/CodeNarc#600]
Sorry to nitpick, but the CodeNarc logo triggers my obsessive grammar twitch. :smile: It should be "Fewer bugs, better code". IMHO that also has a nicer ring to it.

**Comment by chrismair** [comment]
You're not wrong, but closing as duplicate of #128. Our legal team is evaluating options. Don't lose hope.

**Comment by nre-ableton** [comment]
Ah, sorry for the dupe. I missed that issue in the backlog. My bad!
