### ISSUE TITLE
[MissingBlankLineBeforeAnnotatedField] False-positive at the beginning of a class

### ISSUE THREAD

**Issue by boris-petrov** [CodeNarc/CodeNarc#606]
Thanks for the new release! It brought a false-positive in the `MissingBlankLineBeforeAnnotatedField` rule:

```groovy
abstract class JerseySpec extends Specification {
    @Delegate
    private JerseyTest jerseyTest
    ...
```

This leads to a `MissingBlankLineBeforeAnnotatedField` violation on the `private JerseyTest jerseyTest` line which I believe is a false-positive as that's in the beginning of the class.

**Comment by erdi** [comment]
I don't believe it's a false positive, there is not blank line before an annotated field so it does what it says on the tin. Feels to me like you want it not to raise violations in this particular case (at the beginning of a class) but that would be a feature request and would need to be enabled via a config option for backwards compatibility.

**Comment by boris-petrov** [comment]
Well, yes, it's not *really* a false-positive but there should be an exception for that particular case, that's what I meant. :)

**Comment by erdi** [comment]
> there should be an exception for that particular case

I would say "it should be possible to make that particular case an exception" rather than "there should be an exception for that particular case" because people's opinion on whether to raise a violation or not in that case will differ. 😃

**Comment by chrismair** [comment]
I changed the rule to ignore fields that start on the first line of the class.
