### ISSUE TITLE
SpaceAfterMethodDeclarationName - possible false positive when methods have annotations followed by comment lines

### ISSUE THREAD

**Issue by dmurat** [CodeNarc/CodeNarc#612]
I believe that SpaceAfterMethodDeclarationName produces false positives for some border cases in the presence of annotations followed by a line comment.
False-positive occurs if line comment contains a method name and opening and closing brackets with some space between like in the following example:

```
  @Generated // Some comment about main method (bla bla)
  static void main(String[] args) {
    SpringApplication.run(BookingCommandSideApplication, args)
  }
```

I guess line comments should be ignored by the rule.

Tnx

**Comment by chrismair** [comment]
I added a test for this scenario, but it seems to work fine. I tried in both Groovy 2.5.x and 3.0.x.

**Comment by dmurat** [comment]
This one is really weird. In a project using Gradle, a violation will happen after clean compile on the first run of CodeNarc. However, on the second run, the violation does not occur.

As I also cannot provoke the problem from the test, I think you can close this one.
