### ISSUE TITLE
SpaceAroundMapEntryColon False Positive in Gradle files using exclude clause in dependences

### ISSUE THREAD

**Issue by alwa** [CodeNarc/CodeNarc#615]
CodeNarc incorrectly classifies some Gradle code as map manipulation (see violation in screenshot below)

CodeNarc version: 1.4

Screenshot is from SonarQube:
![fp](https://user-images.githubusercontent.com/1206247/116093611-1eb72380-a6a7-11eb-85d5-8e3a2136da46.jpg)

**Comment by alwa** [comment]
Similar issue. The rule complains about this as well:

```
task javadoc(type: Javadoc) {
...
}
```

**Comment by alwa** [comment]
And this:

```apply plugin: 'com.android.library'

**Comment by chrismair** [comment]
But I believe all of those examples are indeed Maps. The Gradle DSL is implemented within Groovy, so those are legitimate violations.

For what it's worth, you can configure the [SpaceAroundMapEntryColon](https://codenarc.org/codenarc-rules-formatting.html#spacearoundmapentrycolon-rule) rule to accommodate that formatting style or to be more lenient, or even skip the Gradle files.

**Comment by alwa** [comment]
@chrismair Oh okay. How would you write my examples in proper Groovy that would not cause violations?

**Comment by chrismair** [comment]
The CodeNarc rule is not suggesting you remove the colons, just that you change the formatting around them or else configure the rule to allow your chosen style.

In the cases above, you could adjust the rule configuration to allow any character in front of the colon. There are multiple ways to [configure the rules in your ruleset](https://codenarc.org/codenarc-configuring-rules.html), but something like this would accomplish making that rule more lenient:
```
 ruleset {
        SpaceAroundMapEntryColon {
            characterBeforeColonRegex = \.\
        }
        // ...
```
That regular expression would allow any char before the colon.

Or you could set the `doNotApplyToFileNames` property of the rule to skip checking your Gradle files, e.g.
`    doNotApplyToFileNames = 'build.gradle'`
