### ISSUE TITLE
UnusedImports triggers for AST introduced imports with no use

### ISSUE THREAD

**Issue by sbglasius** [CodeNarc/CodeNarc#619]
When Grails is introducing unused imports through AST transformations, these are reported without a line number.

![image](https://user-images.githubusercontent.com/625868/119795998-47664f00-bed9-11eb-92eb-87d6d54fe89a.png)

**Comment by sbglasius** [comment]
@chrismair  not to push, but do you have an estimated release time-frame?

**Comment by chrismair** [comment]
The next release is currently expected in the August - October timeframe.

**Comment by sbglasius** [comment]
Any chance there could be a patch-release before then?
