### ISSUE TITLE
Documentation still says `applyToClassNames` and `doNotApplyToClassNames`

### ISSUE THREAD

**Issue by rkrisztian** [CodeNarc/CodeNarc#622]
I was looking at this documentation:

https://codenarc.org/codenarc-configuring-rules.html

It mentions two properties that are no longer valid in a Groovy RuleSet file:

* `doNotApplyToClassNames`
* `applyToClassNames`

Because they have been changed to:

* `applyToFilesMatching`
* `doNotApplyToFilesMatching`

And I had to find out the hard way. Could you please update the docs?

Thanks in advance.

PS.: And they are regular expressions now...

**Comment by chrismair** [comment]
Those *applyToClassNames* and *doNotApplyToClassNames* rule properties are still valid, but are not available for some rules. There is a note on that same page about that:

> NOTE: The applyToClassNames and doNotApplyToClassNames rule configuration properties are
> available only to subclasses of AbstractAstVisitorRule.  ...

**Comment by rkrisztian** [comment]
Sorry, I made the mistake of not reading your documentation more thoroughly.

Since there is a Javadoc available too, that should be my guide for the next time I run into a problem like this.

Thanks for the support.
