### ISSUE TITLE
`ExplicitCallToDivMethod` is a false positive for `new MarkupBuilder(...).div {}`

### ISSUE THREAD

**Issue by rkrisztian** [CodeNarc/CodeNarc#623]
See https://docs.groovy-lang.org/latest/html/api/groovy/xml/MarkupBuilder.html

I think it makes sense to allow for certain `div` methods like this to be called as an exception.

**Comment by chrismair** [comment]
Unfortunately there is no way to know whether the call to `div()` is within a closure used by MarkupBuilder. I have narrowed the window for false positives by ignoring `dev()` method calls if its argument is a Map, Closure or String. Other than that, the workaround will be to disable the rule for the appropriate classes, files or methods.
