### ISSUE TITLE
SpaceAfterMethodCallName when using lambda groovy 3

### ISSUE THREAD

**Issue by henriquelsmti** [CodeNarc/CodeNarc#627]
SpaceAfterMethodCallName invalidate bellow code:
`[1, 2, 3].forEach (it) -> { println it}`

codenarc version: 2.1.0

**Comment by chrismair** [comment]
Please open a separate issue for the 2nd problem. That is a different rule and will be a different fix.

**Comment by chrismair** [comment]
Available with v2.2.0
