### ISSUE TITLE
SpaceInsideParentheses rule finds violations in regex Patterns

### ISSUE THREAD

**Issue by treyturner** [CodeNarc/CodeNarc#628]
The SpaceInsideParentheses rule catches cases inside of regex Patterns, which seems unintentional.

```
~/^(\w{5} )?\d{2}$/   // violation
~/^( \w{5})?\d{2}$/   // violation
```

While it's true we can replace the space with \s, this relaxes the pattern since then any whitespace matches. We're suppressing this for the time being, but I thought modifying the rule to exclude Patterns might be a useful improvement.

Thanks for your consideration!

**Comment by chrismair** [comment]
This is a duplicate of #609. I will add the above examples as additional tests though.

**Comment by treyturner** [comment]
Oops, sorry about that and thank you!
