### ISSUE TITLE
[BUG] ClassStartsWithBlankLine violates empty interfaces and classes if the declaration takes more than 1 line.

### ISSUE THREAD

**Issue by SergeyMormul** [CodeNarc/CodeNarc#638]
If the interface/class declaration is so long that it is beneficial to move a part of declaration to the next line, then there is a violation of the rule.

E.g. on our project we have Spring Mongo Repositories which are named as the database collections they represents
```groovy
interface SomeLongCollectionNameWhichIsHardToRenameWithoutUpdatingTheWholeProjectRepository 
    extends MongoRepository<SomeLongCollectionNameWhichIsHardToRenameWithoutUpdatingTheWholeProject, String>,
            SomeLongCollectionNameWhichIsHardToRenameWithoutUpdatingTheWholeProjectRepositoryExtension { }
```
If the declaration in a single line it violates LineLength rule. Anyway, it makes sence to have shorter lines of code.

In addition to that the implementation of the Extension interface violates the rule even if a blank line is present:
```groovy
class SomeLongCollectionNameWhichIsHardToRenameWithoutUpdatingTheWholeProjectRepositoryImpl extends BaseRepositoryExtension
    implements SomeLongCollectionNameWhichIsHardToRenameWithoutUpdatingTheWholeProjectRepositoryExtension {

    @Override
    void customRepositoryMethod( /* parameters */ ) { ... }
    ...
}
```

Dependencies:
Codenarc 2.1.0
Groovy 2.5.14
SpringBoot 2.5.1
Gradle 6.8

**Comment by chrismair** [comment]
Will be available with CodeNarc 2.2.0.
