### ISSUE TITLE
`SpaceAroundMapEntryColon` doesn't work with Groovy 3

### ISSUE THREAD

**Issue by boris-petrov** [CodeNarc/CodeNarc#641]
`build.gradle`:

```gradle
plugins {
	id 'java'
	id 'groovy'
	id 'codenarc'
}

repositories {
	mavenCentral()
}

dependencies {
	codenarc 'org.codenarc:CodeNarc:2.1.0'
	codenarc "org.codehaus.groovy:groovy:${GroovySystem.version}"
}

tasks.withType(CodeNarc).configureEach {
	configFile = file("${rootDir}/codenarc.xml")
}
```

`codenarc.xml`:

```xml
<ruleset xmlns="http://codenarc.org/ruleset/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://codenarc.org/ruleset/1.0 https://raw.githubusercontent.com/CodeNarc/CodeNarc/master/src/main/resources/ruleset-schema.xsd"
         xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/CodeNarc/CodeNarc/master/src/main/resources/ruleset-schema.xsd">
    <ruleset-ref path='rulesets/formatting.xml'>
        <rule-config name='SpaceAroundMapEntryColon'>
            <property name='characterAfterColonRegex' value='\s'/>
        </rule-config>
    </ruleset-ref>
</ruleset>
```

`src/main/groovy/A.groovy`:

```groovy
class A {
        static x = [a: 1]
}
```

`gradle codenarcMain` leads to errors for `SpaceAroundMapEntryColon` which are wrong. Happens on both JDK 15 and JDK 16. Removing the explicit dependency on Groovy 3 (hence using Groovy 2 which CodeNarc uses by default) fixes the issue.

Initially found [here](https://github.com/CodeNarc/CodeNarc/issues/630#issuecomment-886762069).

**Comment by chrismair** [comment]
I added a test case for this, but so far unable to reproduce, at least within IntellJ IDEA, even after switching to Groovy 3.0.8 and JDK 16.

**Comment by boris-petrov** [comment]
@chrismair - did you follow my explanation? I just did what I've written and I do get violations.

**Comment by chrismair** [comment]
Sorry, my answer was not as clear as it should have been. I did not mean to imply that I could not reproduce, so I was done. I was just saying that I could not reproduce within the IDE and the CodeNarc test suite. So that just meant the investigation was going to be more time-consuming.

In any case, I did reproduce using the steps you supplied, though I had to explicitly specify a later version of Groovy in the **build.gradle** -- I guess my Gradle is probably older and was using an earlier Groovy version for *GroovySystem.version*.

And I was able to resolve those violations by using this dependency instead:
    `codenarc "org.codehaus.groovy:groovy-all:$groovyVersion"`

I would guess this is all related to the automatic declared dependencies of CodeNarc. And in your build file, you were overwriting only the core `groovy` dependency and not the other groovy dependencies.

Let me know if using **groovy-all** fixes it for you.

**Comment by boris-petrov** [comment]
Thanks for digging in!

Using `groovy-all` does indeed fix the issue. I should have figured it out by myself! But I always thought that `groovy-all` was not available for Groovy 3...

In any case, thanks for taking the time. I'll let you close the issue if you don't think there is anything more to be done.

The only thing I can say that could be improved is that CodeNarc should use the Groovy version that the current Gradle it is running in uses (in my case that's Groovy 3.0.7 as that's the version Gradle 7.x comes with) - that would fix both my [original issue](https://github.com/CodeNarc/CodeNarc/issues/630) and this one.

Thanks again!

**Comment by chrismair** [comment]
Great. I think your suggestion would be for the Gradle plugin, rather than CodeNarc itself.

**Comment by boris-petrov** [comment]
Sure, that makes sense. Will you do this or should I? And do we have to open the issue in Gradle's repo itself (as the plugin is built-in)?

**Comment by erdi** [comment]
I don't agree that CodeNarc should use the Groovy version that is being used by the version of Gradle running the build. CodeNarc declares a dependency on a Groovy version and Gradle respects that by using that version of Groovy when running CodeNarc. You also have full ability of overriding it by adding a different version of Groovy to the `codenarc` dependency configuration. 

It would be very strange that if you upgraded Gradle then out of the sudden a different version of Groovy was used when running CodeNarc. On top of that there is no guarantee that the version of Groovy used by the version of Gradle being used is compatible wth CodeNarc. You can try opening a ticket in Gradle's issue tracker as you suggest but I doubt it will not get rejected.

**Comment by boris-petrov** [comment]
> It would be very strange that if you upgraded Gradle then out of the sudden a different version of Groovy was used when running CodeNarc.

That's literally what happens with everything else that uses Groovy - people update Gradle, a new version of Groovy is used. I believe that's perfectly fine and expected.

Even if it weren't, then people reach the same two issues that I hit - first CodeNarc doesn't work on JDK 16 (and it used to work great on JDK 15 without specifying more than a dependency on CodeNarc itself); secondly people should put specifically a dependency on `groovy-all` as otherwise that leads to this issue here.

In any case, I will try opening an issue and we'll see what they say. :)

**Comment by boris-petrov** [comment]
> Great. I think your suggestion would be for the Gradle plugin, rather than CodeNarc itself.

Actually, I'm not sure how *exactly* things work, but isn't CodeNarc's Groovy version defined [here](https://github.com/CodeNarc/CodeNarc/blob/v2.1.0/build.gradle#L27)? So shouldn't this somehow specify a different version based on the runtime Groovy version (which comes from Gradle)?

**Comment by erdi** [comment]
I think that you are confusing the version of Groovy used by Gradle as a "runtime Groovy version". That version is used by Gradle and only by Gradle. If you want to compile Groovy project code you need to specify a Groovy version. Same for running groovy code. And this also applies to running CodeNarc. There is no such thing as a default Groovy version which comes with Gradle. There is a version of Groovy used by Gradle but it's only used for running Gradle code itself and in isolation, nothing else.

**Comment by erdi** [comment]
One thing you might be missing is that even though Gradle runs CodeNarc it loads it using a separate classloader which is isolated from Groovy shipped with and used by Gradle. And that is done on purpose so that the version of Groovy used by Gradle is isolated from the one used by CodeNarc and that it does not get in the way.

**Comment by boris-petrov** [comment]
@erdi - thanks for the explanation. What you say makes perfect sense. I guess I got confused because I don't explicitly depend on Groovy but my tests compile. I guess there is some transitive dependency somewhere.

But still the same problem remains - cases like mine - where the Groovy code is compiled with one Groovy version (wherever it comes from) but CodeNarc is run with another. I guess there is nothing that can be done though - CodeNarc can't really control this.
