### ISSUE TITLE
Please provide a "latest" tag on dockerhub

### ISSUE THREAD

**Issue by jdufresne** [CodeNarc/CodeNarc#648]
It is conventional to provide a "latest" tag on dockerhub so consumers can pull the latest version, whatever that happens to be.

Here is the list of tags on dockerhub:

https://hub.docker.com/r/codenarc/codenarc/tags

For example, the groovy docker image has "latest" tag:
https://hub.docker.com/_/groovy?tab=tags

**Comment by chrismair** [comment]
Good idea. Done.
