### ISSUE TITLE
UnnecessaryPublicModifier: false positive with annotations

### ISSUE THREAD

**Issue by zman0900** [CodeNarc/CodeNarc#650]
The UnnecessaryPublicModifier rule sometimes gives false positive for methods with annotations where the annotation's parameters contain the string 'public'.

Example:

```java
package some.package

import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.ValueSource

import static org.junit.jupiter.api.Assertions.assertFalse

class FakeTest {

    @ParameterizedTest
    @ValueSource(strings = [
            'some public value',
            'some other value',
    ])
    void testNothing(final String value) {
        assertFalse(value.isEmpty())
    }

}
```

Results in:

> [codenarc] File: some/package/FakeTest.groovy
> [codenarc]     Violation: Rule=UnnecessaryPublicModifier P=3 Loc=.(FakeTest.groovy:15) Msg=[The public keyword is unnecessary for methods] Src=[void testNothing(final String value) {]

**Comment by chrismair** [comment]
Available with next CodeNarc release
