### ISSUE TITLE
ClassStartsWithBlankLineRule thorws NPE on annotation.

### ISSUE THREAD

**Issue by SergeyMormul** [CodeNarc/CodeNarc#652]
This is related to this bug: https://github.com/CodeNarc/CodeNarc/issues/590#issue-786364497

I have 
```
Error from [org.codenarc.rule.formatting.ClassStartsWithBlanLineRule] processing source file [...UnitTest.groovy]
java.lang.NullPointerException: Cannot invoke trim() on null object
```
For the annotation class like
```
@Target( ElementType.TYPE )
@Retention( RretentionPolicy.RUNTIME )
@Inherited
@interface UnitTest { }
```
The hotfix of adding an empty line into the class body violates ClassEndsWithBlankLine. The NPE is thrown regardless of a number of spaces between {}.

Configuration:
gradle: 7.3
groovy: 3.0.9
codenarc: 2.2.0

**Comment by chrismair** [comment]
Available in the next CodeNarc release
