### ISSUE TITLE
Upgrade to Groovy 3

### ISSUE THREAD

**Issue by chrismair** [CodeNarc/CodeNarc#654]
Establish a baseline dependency of Groovy 3.x. Groovy 2.x will no longer be supported.

**Comment by chrismair** [comment]
This also implies a requirement for Java 8 or later.

**Comment by faireai-fmonorchio** [comment]
When upgrade to Groovy 4?

**Comment by chrismair** [comment]
We are finishing up the major release for Groovy 3 and Java 8. We'll have to add testing/support for Groovy 4 in a future release.
