### ISSUE TITLE
SpaceAfterMethodCallName reports about wrong line of code.

### ISSUE THREAD

**Issue by SergeyMormul** [CodeNarc/CodeNarc#657]
For the piece of Groovy code like
```groovy
1 def failEvents = messages.parallelStream()
2                          .filter { item -> item.headers.get( headerName ) == 'failed' }.collect ( Collectors.toList() ) as List<Message>
```
SpaceAfterMethodCallName failed with the following message in console

> [ant:codenarc] File: com/project/TestClass.groovy
[ant:codenarc] Violation: Rule=SpaceAfterMethodCallName P=3 Line=1 Msg=[There is whitespace between method name and parenthesis in a method call.] Src=[def failEvents = messages.parallelStream()]

The rule should report about the line 2.

Groovy 2.5.15
Codenarc 2.2.0

**Comment by chrismair** [comment]
Available with the next CodeNarc release
