### ISSUE TITLE
Don't depend on `groovy-all` but only on the specifically required groovy artifacts

### ISSUE THREAD

**Issue by erdi** [CodeNarc/CodeNarc#67]
Now that [Gradle CodeNarc plugin is using the version of groovy CodeNarc depends on instead of the one shipped with gradle](http://www.gradle.org/docs/release-candidate/release-notes#codenarc-plugin-groovy-version-changes) to execute CodeNarc some [users that don't want to use `groovy-all` artifact in their builds have run into trouble](https://groups.google.com/d/msg/gradle-dev/A6jdwa5uoB4/3Qy67dW4HfMJ). 

It would probably be a good idea not to depend on `groovy-all` anymore but just on groovy artifacts that are really necessary for CodeNarc to run. It will require bumping Groovy version used as pre-2.0 groovy versions were only available in `groovy-all` form. CodeNarc depends on Groovy 1.7.5, which was released 2010-09-16 making it 4 years old now. This is probably a good excuse to upgrade.

**Comment by chrismair** [comment]
For CodeNarc 0.23
