### ISSUE TITLE
`StaticMethodsBeforeInstanceMethods` false positive on file with only one method

### ISSUE THREAD

**Issue by hakanai** [CodeNarc/CodeNarc#671]
We have a few source files where the general structure is like this:

```groovy
#!/usr/bin/groovy

import acme.Utils

static boolean call() {
    new Utils().isSomething()
}
```

For some reason (presumably because Utils contains some instance methods?) this triggers the `StaticMethodsBeforeInstanceMethods` warning, despite there being only one method declared in the file.

Versions in use:
* CodeNarc v1.2.1 (v2.x is obviously out and I do want to upgrade, but I see nothing in the changelog mentioning this warning anyway, so I'm not optimistic.)

**Comment by chrismair** [comment]
The false positive is because it is a script, and the rule was not properly ignoring generated methods, such as the `run()` method generated for script classes.
