### ISSUE TITLE
Missing build instructions

### ISSUE THREAD

**Issue by UlrichEckhardt** [CodeNarc/CodeNarc#674]
The documentation simply lacks the necessary steps from checking out the source code to getting it to run:
* README.md contains a list of dependencies (Groovy, SLF4J, GMetrics) and the recommendation to use Java 8-11.
* codenarc-command-line.md says "Usage: `java org.codenarc.CodeNarc [OPTIONS]`", but that doesn't work.
* codenarc-command-line.md later on tells me to put the jars with Groovy and CodeNarc my `CLASSPATH`. I do have an idea what that means, but it would be easier to spell it out. Also, the only file with a ".jar" extension I have is gradle-wrapper.jar, none for CodeNarc.

I'm pretty sure this is a piece-of-cake for someone with a Java background, but I don't have that.

I would also welcome infos how to build this into something that can be used as a Docker container, like the ones on dockerhub. I honestly don't want to install various libraries into my system just to run this and it would also shield the code from my system, for reproducability.

**Comment by chrismair** [comment]
Apologies for the very late response. You are certainly correct that the existing instructions assume some familiarity with the Java ecosystem.

I assume you have seen the page on running CodeNarc on Docker: https://codenarc.org/codenarc-docker.html. But of course that will only work for already-released CodeNarc versions, and your question mentioned building from source. 

I'll look into enhancing the docs to describe the steps, using Gradle.

**Comment by chrismair** [comment]
Enhancements to the documentation:
 - README: Add info on building the CodeNarc jar from source.
 - _CodeNarc Command-Line_ page: 
     - Add info on building CodeNarc jar locally from source. 
     - For sample Gradle run script, add info on using locally-built CodeNarc jar as alternative to published jar. 
     - For running from shell script, add links for downloading CodeNarc, Groovy and Logback jars.

**Comment by UlrichEckhardt** [comment]
Nice! That makes it a lot easier for people not familiar with the infrastructure.
