### ISSUE TITLE
Rule "ExceptionExtendsError" false positive

### ISSUE THREAD

**Issue by faireai-fmonorchio** [CodeNarc/CodeNarc#675]
Hi all,

I'm using this "ExceptionExtendsError" rule but I have a class that implements an "Error" interface from a 3rd party library and not that from jdk.
I think that is better to check package or, in alternative, find text "extends Error" and not only "Error" so we can exclude interfaces.

**Comment by chrismair** [comment]
Fixed to now exclude:
`interface MyError extends Error { }`
and
`class MySpecialError implements Error { }`

**Comment by faireai-fmonorchio** [comment]
Thanks
