### ISSUE TITLE
Use XmlParserFactory

### ISSUE THREAD

**Issue by paulk-asert** [CodeNarc/CodeNarc#678]
XmlParserFactory provides a bridge between groovy.util.XmlParser (up to Groovy 3) and groovy.xml.XmlParser (Groovy 3 and above). Using this feature would allow folks who have moved to Groovy 4 to potentially use CodeNarc 3. This would only be true (currently) for projects not making use of new syntax features (e.g. "record" or "sealed" keyword).

**Comment by chrismair** [comment]
Fixed by #679.
