### ISSUE TITLE
[3.0.0] `UnnecessaryPublicModifierRule` throws `StringIndexOutOfBoundsException`

### ISSUE THREAD

**Issue by boris-petrov** [CodeNarc/CodeNarc#683]
```groovy
package com.company

import spock.lang.Requires
import spock.lang.Specification

class SomeSpec extends Specification {
	@Requires({ true })
	def 'asd'() {
		expect:
		true
	}
}
```

This causes CodeNarc 3.0.0 to throw `StringIndexOutOfBoundsException`. It's because of the `@Requires` annotation.

**Comment by chrismair** [comment]
Yes, it is because the method has an annotation and that annotation line includes '{'.

**Comment by darxriggs** [comment]
There is already a commit fixing this. Shouldn't this issue be closed then?

**Comment by chrismair** [comment]
Yes, agreed.
