### ISSUE TITLE
Add CodeNarc 3.0.0 JAR to release assets on GitHub

### ISSUE THREAD

**Issue by nre-ableton** [CodeNarc/CodeNarc#690]
All of the other releases have a `CodeNarc-vA.B.C.jar` file in the assets, but v3.0.0 doesn't seem to have one. Could someone please upload a JAR file for this release? Thanks!

**Comment by chrismair** [comment]
Done. That was an oversight. Thanks.

**Comment by nre-ableton** [comment]
@chrismair thank you!

**Comment by nvuillam** [comment]
Thanks, I'll be able to upgrade npm-groovy-lint someday :)
