### ISSUE TITLE
Add functionality to combine codenarc results from different runs

### ISSUE THREAD

**Issue by mikelee3** [CodeNarc/CodeNarc#691]
We have a multi-module Gradle project and would like to combine our codenarc results into a single result file instead of having codenarcMain and codnarcTest results for each subproject. I cannot find a built-in way to accomplish this, so can this be added as a feature request?

**Comment by erdi** [comment]
Gradle support for CodeNarc is maintained by the Gradle team (it's a core plugin) and not by the CodeNarc team so you will need to take that feature request to them. Secondly, it should be fairly easy to add a new task that will perform CodeNarc analysis on multiple source sets so it's something that you can already do yourself. The docs for CodeNarc tasks are at https://docs.gradle.org/current/dsl/org.gradle.api.plugins.quality.CodeNarc.html, you just need to add new one and configure it appropriately.

**Comment by chrismair** [comment]
Feel free to reopen if necessary
