### ISSUE TITLE
warning package=com.xyz.abc.v2.Runner PackageName

### ISSUE THREAD

**Issue by sbollap1** [CodeNarc/CodeNarc#696]
I am seeing a waring on the very first line of the groovy file at the package statement, the warning is not giving me any clues as to how
what needs to be fixed any clues will be appreciated. showing you a screenshot of the warning

![image](https://user-images.githubusercontent.com/4892241/164293135-0e9ae7c7-7703-4bd0-bbfb-3ecc87f9019a.png)

@nvuillam thanks

**Comment by nvuillam** [comment]
@sbollap1 this is a warning for PackageName rule, that you can see in CodeNarc documentation here :)

https://codenarc.org/codenarc-rules-naming.html#packagename-rule

**Comment by sbollap1** [comment]
@nvuillam  yes found it after I posted this question. thanks :)

**Comment by chrismair** [comment]
Feel free to reopen if there is still a CodeNarc issue.
