### ISSUE TITLE
Where to Configure ParameterCount for Megalinter

### ISSUE THREAD

**Issue by sbollap1** [CodeNarc/CodeNarc#697]
I am seeing a bunch of warnings like this. I would like to configure the Number of Parameters to 10. Appreciate if anyone can point me to where this can be set
`
 93    warning  Number of parameters in method com.abc.walter.v2.None.getSomeCodeDone exceeds maximum allowed (5).  ParameterCount 
`
@nvuillam  thanks

**Comment by SergeyMormul** [comment]
The rule is ParameterCount in the ruleset/size.xml section.
Set the `maxParameters` property.

Further, look into the documentation. There is everything! E.g. here is the size rules section: https://codenarc.org/codenarc-rules-size.html

**Comment by chrismair** [comment]
Feel free to reopen if needed.
