### ISSUE TITLE
BraceForTryCatchFinally does not support try-with-resources

### ISSUE THREAD

**Issue by SergeyMormul** [CodeNarc/CodeNarc#701]
The rule fails for try-with-resources block like the following
```groovy
try (def input = url.openStream(); def output = new ByteArrayOutputStream(4096)) {
     // some code here to work with streams
}
catch (IOException e) {
    // some code to handle the exception
}
```
The rule also failed for a single parameter in `try`.
The rule also failed on the first line for a multiline try-with-resources like the following
```groovy
try (def input = url.openStream()
     def output = new ByteArrayOutputStream(4096)) {
     // some code here to work with streams
}
```

**Comment by chrismair** [comment]
For the first issue, please set the *catchOnSameLineAsClosingBrace* rule property to *true*.

I was not able to reproduce the 2nd issue. In any case please include the full violation information for any remaning issues.

**Comment by SergeyMormul** [comment]
Checked with Codenarc 3.1.0, Groovy 4.0.3.
Both cases violates EmptyTryBlock. BraceForTryCatchFinally is not violated.
Console outputs:
```
[ant:codenarc] File: com/test/TestClass.groovy
[ant:codenarc]     Violation: Rule=EmptyTryBlock P=2 Line=112 Msg=[The try block is empty] Src=[try ( def inputStream = assetUrl.openStream(); def outputStream = new ByteArrayOutputStream( 4096 ) ) {]
```
or
```
[ant:codenarc] File: com/transparent/symphone/adapter/outbound/asset/DefaultAssetTransferTool.groovy
[ant:codenarc]     Violation: Rule=EmptyTryBlock P=2 Line=112 Msg=[The try block is empty] Src=[try ( def inputStream = assetUrl.openStream()]
```

**Comment by chrismair** [comment]
Ahh, okay, yeah **EmptyTryBlock** makes more sense. We'll take a look.

**Comment by chrismair** [comment]
I ended up ignoring all try-with-resources statements (since having an empty try block with those is a valid scenario).
