### ISSUE TITLE
[3.0.1] `UnnecessaryPublicModifierRule` throws `PatternSyntaxException`

### ISSUE THREAD

**Issue by boris-petrov** [CodeNarc/CodeNarc#703]
I have a Spock test named something like  `Foo {bar,baz}` which causes CodeNarc to throw a `java.util.regex.PatternSyntaxException: Illegal repetition near index 27`. This is new since 3.0.0.

**Comment by pbielicki** [comment]
We're experiencing the same issue

**Comment by chrismair** [comment]
Will be available with CodeNarc v3.1.0.
