### ISSUE TITLE
Allow functioning with Groovy 4

### ISSUE THREAD

**Issue by paulk-asert** [CodeNarc/CodeNarc#706]
The next thing to get working for Groovy 4 functionality is to handle super calls in the codebase. To fix other issues, the MOP calls to handle super calls are slightly different between Groovy 3 and Groovy 4. This doesn't affect users who compile and test all on Groovy 3 or all on Groovy 4, but makes it harder to write rules which can be compiled on one of those versions and used on the other.

The recommended approach is to use @CompileStatic for all such calls.

**Comment by paulk-asert** [comment]
See: #707 (this covered all tests used by the Groovy codebase CodeNarc usage but might not be all cases)
I can't say I am particularly happy that this change is required but I couldn't think of a better way.
There should probably also be some doco or a note in the release notes for users wanting to write their own rules to do something similar.

**Comment by chrismair** [comment]
Whoa! Yeah, that is pretty awful. I need to spend some more time reviewing that, perhaps with a drink or two.

**Comment by chrismair** [comment]
Okay, well I'm not thrilled with it either, but it seems reasonable and the alternatives (e.g. separate jars for Groovy 3 and 4) are even less attractive.

Thanks Paul for looking into this, determining the proper fix and then implementing it!

I'll add a note to the release notes and to the page about Creating Rules re: @CompileStatic for calls to super.visitXxx().

**Comment by henrik242** [comment]
Any progress on Groovy 4 compat? I'm getting `groovy.lang.MissingMethodException: No signature of method: org.codenarc.rule.AbstractAstVisitor.visitClassEx() is applicable for argument types: (org.codehaus.groovy.ast.ClassNode) values: [no.foo.bar.MyTest]`

**Comment by paulk-asert** [comment]
Any chance you could try a snapshot of codenarc? Some relevant commits have been made but aren't in a release just yet.

**Comment by henrik242** [comment]
@paulk-asert Sure! Is it available from a maven repo somewhere?

**Comment by henrik242** [comment]
@paulk-asert OK, I'll see if I have some time available. Otherwise a snapshot or RC release would be appreciated :)

**Comment by henrik242** [comment]
@chrismair Thanks a lot! I don't see it in https://repo1.maven.org/maven2/org/codenarc/CodeNarc/ yet, are there other places I should look?

**Comment by chrismair** [comment]
I just learned that Snapshot releases are not synced to Maven Central.

You need to declare the snapshot repo in your build file. For instance, in Gradle:
```
repositories {
    mavenCentral()
    maven {
    	url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
     
dependencies {
    implementation 'org.codenarc:CodeNarc:3.0.2-SNAPSHOT' 
    implementation 'ch.qos.logback:logback-classic:1.2.3'
    implementation 'org.codehaus.groovy:groovy-all:3.0.9'
}

```

**Comment by henrik242** [comment]
@chrismair Thanks!

I still get some errors with `3.0.2-SNAPSHOT`: 
```
Error processing file: 'foo/bar/SomeTest.groovy'; groovy.lang.MissingMethodException: No signature of method: org.codenarc.rule.AbstractAstVisitor.visitClassEx() is applicable for argument types: (org.codehaus.groovy.ast.ClassNode) values: [foo.bar.SomeTest]
Possible solutions: visitClass(org.codehaus.groovy.ast.ClassNode), visitClass(org.codehaus.groovy.ast.ClassNode)
Error from [org.codenarc.rule.exceptions.ExceptionExtendsErrorRule] processing source file [/Users/foo/src/baz/shared/common/src/test/java/foo/bar/SomeTest.groovy]
groovy.lang.MissingMethodException: No signature of method: org.codenarc.rule.AbstractAstVisitor.visitClassEx() is applicable for argument types: (org.codehaus.groovy.ast.ClassNode) values: [foo.bar.SomeTest]
Possible solutions: visitClass(org.codehaus.groovy.ast.ClassNode), visitClass(org.codehaus.groovy.ast.ClassNode)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:72)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:148)
        at org.codenarc.rule.exceptions.ExceptionExtendsErrorAstVisitor.visitClassEx(ExceptionExtendsErrorRule.groovy:45)
        at org.codenarc.rule.AbstractAstVisitor.visitClass(AbstractAstVisitor.java:131)
        at org.codenarc.rule.AbstractAstVisitorRule.applyTo(AbstractAstVisitorRule.java:97)
        at org.codenarc.rule.AbstractRule.applyTo(AbstractRule.java:143)
        at org.codenarc.rule.Rule$applyTo$2.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codenarc.rule.Rule$applyTo$2.call(Unknown Source)
```

**Comment by chrismair** [comment]
Okay, yeah I can reproduce that running with Groovy 4. Hmmm, well that code already has that @CompileStatic "fix", so that is frustrating and puzzling.

**Comment by chrismair** [comment]
Okay, yeah I can reproduce that running with Groovy 4. That rule does not yet include the `@CompileStatic` fix.

@paulk-asert How did you decide which subset of CodeNarc rules to fix with the `@CompileStatic` annotation? There are hundreds of other places in the code without it, including `ExceptionExtendsErrorRule`.

This makes me reconsider the solution, and whether it makes more sense to just build and deliver a separate Groovy 4 jar going forward. Not that I like that solution either, but it seems like that might be the lesser evil.

**Comment by paulk-asert** [comment]
As I mentioned in the earlier comment[1], I only covered tests that the Groovy codebase used.
Maybe a separate Groovy 4 jar is the way to go, I was trying to avoid that - so far Grails/Micronaut/Spock have avoided the need but they are only part-way to supporting Groovy 4.
I don't know how widespread third-party rules might be. They might also need to make Groovy 4 versions. But as it is they might need to do some rewriting anyway.

[1] https://github.com/CodeNarc/CodeNarc/issues/706#issuecomment-1116977001

**Comment by henrik242** [comment]
> Maybe a separate Groovy 4 jar is the way to go, I was trying to avoid that - so far Grails/Micronaut/Spock have avoided the need

I believe at least Spock has a separate Groovy 4 release. Quoting from their README: 

"The latest 2.x release version is 2.2-M1 (2.2-M1-groovy-2.5, 2.2-M1-groovy-3.0, 2.2-M1-groovy-4.0), released on 2022-02-16."

**Comment by paulk-asert** [comment]
I stand corrected re Spock. I guess we should bump our Spock version in Groovy at some point!  😄

**Comment by chrismair** [comment]
I have reverted the changes from  #707, in favor of publishing a Groovy 4-specific version of CodeNarc. See #709.
