### ISSUE TITLE
Consider changing version, not artifact name, to indicate Groovy 4 compatibility

### ISSUE THREAD

**Issue by DPUkyle** [CodeNarc/CodeNarc#711]
Hi team, I'm working on getting Gradle ready to support Groovy 4.

Our built-in plugin for CodeNarc supports easily configuring the CodeNarc version using the `codenarc` extension:
```
codenarc {
    toolVersion = '3.1.0'
}
```

The configured value is substituted to this string `"org.codenarc:CodeNarc:$toolVersion"` and _violà_, we resolve the CodeNarc library and its dependencies.

The change to publish CodeNarc 3.1.0 under a different GAV for Groovy 4 compatibility means we would have to change this scheme. It's not a deal-breaker, but would require extra complexity to inspect the compile or runtime classpaths of the code being analyzed, figure out whether it's using Groovy 4+ vs. 3 or below, and adjust the coordinates accordingly.

As an alternative, may I suggest the CodeNarc project consider publishing consistent `group` and `artifact` values, but indicating in the `version` string if Groovy 4 is supported? This is how the Spock framework publishes their versions: `org.spockframework:spock-core:2.1-groovy-2.5`, `org.spockframework:spock-core:2.2-M3-groovy-4.0` etc.

I was curious how spock manages this numbering scheme and see two interesting areas:

1. GitHub Actions workflow to do matrix-based releases, passing the Groovy version as a `variant` sysprop: https://github.com/spockframework/spock/blob/spock-2.2-M3/.github/workflows/release.yml#L66-L91
2. Logic in their buildscript to react to the `variant` value, setting Groovy group and version accordingly: https://github.com/spockframework/spock/blob/spock-2.2-M3/build.gradle#L24-L44

What are your thoughts on this release mechanism?

**Comment by chrismair** [comment]
I certainly want to help and accommodate you and the Gradle team. My main concern is how this impacts all of the existing consumers that have already setup their build scripts and tooling.

**Comment by chrismair** [comment]
As we discussed, I have published CodeNarc version 3.1.0-groovy-4.0.

https://mvnrepository.com/artifact/org.codenarc/CodeNarc/3.1.0-groovy-4.0

Feel free to reopen if further discussion or changes are needed. Thanks for the feedback.
