### ISSUE TITLE
Implicit Parentheses Around Method Arguments

### ISSUE THREAD

**Issue by drernie** [CodeNarc/CodeNarc#727]
Groovy allows [optional parentheses](https://blog.mrhaki.com/2009/10/groovy-goodness-optional-parenthesis.html).
However, there seems only a single Rule for when they are NOT required:

https://codenarc.org/codenarc-rules-unnecessary.html#unnecessaryparenthesesformethodcallwithclosure-rule 
> If a method is called and the only parameter to that method is an inline closure then the parentheses of the method call can be omitted.

There's a case to be made for requiring ALL methods to have explicit parentheses, for consistency and unambiguity. Is that something you might be willing to support?

From: https://github.com/nvuillam/npm-groovy-lint/issues/267

**Comment by chrismair** [comment]
> There's a case to be made for requiring ALL methods to have explicit parentheses, for consistency and unambiguity. Is that something you might be willing to support?

Probably not. There are certain idiomatic cases where parentheses would be unexpected and unpleasant, including where the last argument is a Closure, as that rule checks for.

There is also issue #433 , now a few years old, discussing a rule for checking for unnecessary parentheses, which I believe is the opposite of what you are asking about.

**Comment by UlrichEckhardt** [comment]
```groovy
pipeline {
    step {
        // code for first build pipeline step
    }
    step {
        // second step
    }
}
```
You wouldn't want parentheses here.

**Comment by drernie** [comment]
Okay, I will concede.
