### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by schorlton** [CodeNarc/CodeNarc#734]
Hi, thanks for your work on CodeNarc. Would it be possible to tag a new release? I think https://github.com/CodeNarc/CodeNarc/pull/717 and other merged PRs will be greatly appreciated by the community. (cc @nvuillam)

Thanks!!

**Comment by chrismair** [comment]
#717 was available in CodeNarc v3.2.0.

My intent is to do the next release within the next several weeks.

**Comment by UlrichEckhardt** [comment]
@schorlton, 3.4 was tagged and released in January, so I think you could close this issue.

**Comment by schorlton-bugseq** [comment]
Sorry for the delay, thanks both!
