### ISSUE TITLE
Documentation for PackageName rule is incorrect

### ISSUE THREAD

**Issue by asteiner-psh** [CodeNarc/CodeNarc#740]
Documentation for PackageRule (https://codenarc.org/codenarc-rules-naming.html#packagename-rule) says that `regex`'s default value is `[a-z]+[a-z0-9](\.[a-z0-9]+)`.

The Rule's source says the default value is actually `[a-z]+[a-z0-9]*(\.[a-z0-9]+)*`.

https://github.com/CodeNarc/CodeNarc/blob/edc67a58a7c400e44f1090e642dfab238f05b770/docs/codenarc-rules-naming.md?plain=1#L233

https://github.com/CodeNarc/CodeNarc/blob/edc67a58a7c400e44f1090e642dfab238f05b770/src/main/groovy/org/codenarc/rule/naming/PackageNameRule.groovy#L40C21-L40C50

**Comment by chrismair** [comment]
Thanks. That trailing asterisk probably got dropped when we migrated the docs to markdown.
