### ISSUE TITLE
SpaceAfterCommentDelimiter and SpaceBeforeCommentDelimiter has false negatives for dollar-slashy strings

### ISSUE THREAD

**Issue by rkrisztian** [CodeNarc/CodeNarc#743]
Example Spock test code from [my project](https://github.com/rkrisztian/search):

```groovy
	void 'one pattern, with match, file excluded'() {
		when:
			findFiles new Conf(
					paths: [new GlobPattern('*.groovy')],
					excludeFilePatterns: [~$//example.+/$]
			)

		then:
			!foundFiles
	}
```

Result:

```none
FileFinderTest.groovy | SpaceAfterCommentDelimiter | 3 | 52 | [SRC]excludeFilePatterns: [~$//example.+/$][MSG]The comment does not begin with space or whitespace
-- | -- | -- | -- | --
FileFinderTest.groovy | SpaceBeforeCommentDelimiter | 3 | 52 | [SRC]excludeFilePatterns: [~$//example.+/$][MSG]The comment is not preceded by a space or whitespace
```

Dollar-slashy strings can freely include forward-slash characters, but this rule does not seem to know that `//` is not a comment.

**Comment by chrismair** [comment]
Well, that is fustrating, but not surprising. Those comment rules have to use heuristics and regular expressions to check the comments, since comments are not part of the Groovy AST. Thanks for describing the issue.
