### ISSUE TITLE
false-positive for UnnecessarySetter when the method is static

### ISSUE THREAD

**Issue by stevenh** [CodeNarc/CodeNarc#748]
If you have a method which is static it triggers UnnecessarySetter warning e.g.
```groovy
public static void setMyThing(String value) {
    privateVal = value
}

setMyThing('test')
```

However using the suggestion
```groovy
myThing = 'test'
```
Results to a hard to debug error from groovy:
```log
General error during canonicalization: class org.codehaus.groovy.ast.expr.PropertyExpression cannot be cast to class org.codehaus.groovy.ast.expr.TupleExpression (org.codehaus.groovy.ast.expr.PropertyExpression and org.codehaus.groovy.ast.expr.TupleExpression
```

I hope the above example demonstrates the issue, as the original was much more complex.

**Comment by chrismair** [comment]
I'm tempted to change the rule to skip static methods. I don't think it was intended to include those anyway.

**Comment by stevenh** [comment]
That sounds sensible

**Comment by chrismair** [comment]
Because this rule analyzes method calls rather than method declarations, it does not always know whether the method is static. So I went with a narrower fix, for now, that just ignores calls to setter methods that match a static method name within the same class.
