### ISSUE TITLE
Java 21 support

### ISSUE THREAD

**Issue by efenderbosch-atg** [CodeNarc/CodeNarc#757]
Is Java 21 support on the roadmap? 17 worked just fine, but now other tools in our toolchain support 21 and we want to move to 21.

**Comment by peter-thomas-mgd** [comment]
At a minimum the Gradle plugin should expose toolchain support so that we can run the code analysis task on a supported version of Java if the rest of the build fully supports Java 21.

**Comment by efenderbosch-atg** [comment]
I get this:

```
Execution failed for task ':codenarcTest'.
> A failure occurred while executing org.gradle.api.plugins.quality.internal.CodeNarcAction
   > BUG! exception in phase 'semantic analysis' in source unit 'Script1.groovy' Unsupported class file major version 65
```

**Comment by efenderbosch-atg** [comment]
Opened a gradle issue: https://github.com/gradle/gradle/issues/27252

**Comment by chrismair** [comment]
I get the same error running CodeNarc command-line (i.e. without Gradle).

It looks like Groovy does not yet support Java 21. That will be a prerequisite, and may require a Groovy major version upgrade (e.g. Groovy 5). TBD...

**Comment by efenderbosch-atg** [comment]
Gradle 8.5 release notes indicate full compatibility w/ Java 21, which is why I opened the ticket there.

https://docs.gradle.org/8.5/release-notes.html

>Full Java 21 support
>Gradle 8.4 supported compiling and testing with Java 21 using [Java toolchains](https://docs.gradle.org/8.5/userguide/toolchains.html), but running Gradle itself on Java 21 was not yet supported.
>With this release, Gradle now fully supports compiling, testing and running on [Java 21](https://openjdk.org/projects/jdk/21/).
>See the full [compatibility documentation](https://docs.gradle.org/8.5/userguide/compatibility.html#java) for details.

**Comment by peter-thomas-mgd** [comment]
We have a number of projects built on Groovy 4.0.15 and compiled with Gradle 8.5 with source compatibility set to Java 17. Projects that have not enabled the CodeNarc plugin compile and deploy to test environments without issue using JRE 21. Projects that have the CodeNarc plugin enabled fail to build, unless the JRE is downgraded to version 17. Once compiled, they can deploy and run on JRE 21. So the issue appears to be a limitation of the CodeNarc plugin itself, not Groovy. We have also observed that the CodeNarc plugin for IntelliJ IDEA works correctly when the IDE is configured to use Java 21. This also suggests that the issue is due to the CodeNarc plugin integration with Gradle and not the code base for the inspections.

**Comment by chrismair** [comment]
Thanks @peter-thomas-mgd .. Yes, I was using an older Groovy version when testing before. I confirmed that with Groovy 4.0.15, the Java 21 test of CodeNarc command-line works fine.

**Comment by efenderbosch-atg** [comment]
In the meantime I'm trying to get a custom gradle task working and not having much luck.

`build.gradle.kts` :

```kotlin
dependencies {
    codenarc("org.slf4j:slf4j-simple:1.7.36")
    codenarc("org.slf4j:slf4j-api:1.7.36")
    codenarc("org.codenarc:CodeNarc:3.3.0-groovy-4.0")
}

tasks.register<JavaExec>("codenarc2") {
    mainClass = "org.codenarc.CodeNarc"
    args(
        "-basedir=src/test/groovy",
        "-rulesetfiles=config/codenarc.groovy",
        "-report=html",
        "-failOnError=true"
    )
    classpath = configurations["codenarc"]
}
```

When I run `./gradlew codenarc2` I get a stack trace

```
ERROR: java.lang.NoClassDefFoundError: org/slf4j/Logger
java.lang.NoClassDefFoundError: org/slf4j/Logger
<snip>
CodeNarc - static analysis for Groovy,
Usage: java org.codenarc.CodeNarc [OPTIONS]
<snip>
```

If I turn on the `--info` flag I can see that it is including the slf4j-simple jar from my gradle cache in the classpath from  `~/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-simple/1.7.36/a41f9cfe6faafb2eb83a1c7dd2d0dfd844e2a936/slf4j-simple-1.7.36.jar`

But the slf4j-api jar is not being included. Any ideas?

It does dump output like the command line args are not present, but I can see them logged `org.codenarc.CodeNarc -basedir=src/test/groovy -rulesetfiles=config/codenarc.groovy -report=html -failOnError=true`

**Comment by chrismair** [comment]
Hmmm .. nothing obvious to me, though I would not claim to be a Gradle expert. I don't believe you need the SLF4J API jar if you already include one of the impl jars. You could try :
 - A different SLF4J implementation, e.g. `implementation 'ch.qos.logback:logback-classic:1.2.3'`
 - Deleting your Gradle cache (.gradle) and forcing everything to download.
 - Using the default configuration instead, e.g. defining dependencies using `implementation` and then `classpath = sourceSets.main.runtimeClasspath`

**Comment by efenderbosch-atg** [comment]
Slight better custom task that replicates what the plugin does for `codenarcTest` task.

```
configurations.register("codenarc") {
    dependencies {
        implementation("org.codenarc:CodeNarc:3.3.0-groovy-4.0")
    }
}

tasks.register<JavaExec>("codenarcTest") {
    mainClass = "org.codenarc.CodeNarc"
    args(
        "-basedir=src/test/groovy",
        "-rulesetfiles=file:config/codenarc.groovy",
        "-report=html:build/reports/codenarc/test.html",
        "-maxPriority1Violations=0",
        "-maxPriority2Violations=0",
        "-maxPriority3Violations=0",
    )
    classpath = sourceSets.main.get().runtimeClasspath + configurations["codenarc"]
}
```

And I removed `codenarc` from `plugins`.

**Comment by peter-thomas-mgd** [comment]
@efenderbosch-atg Thanks for posting your workaround configuration. We have implemented this in our build files (Groovy DSL) and I can confirm that it works in our production environment.

```Groovy
// -- Workaround for Java 21 and CodeNarc Issues --
configurations.register('codenarc') {
    dependencies {
        implementation("org.codenarc:CodeNarc:${codeNarcVersion}")
    }
}

tasks.register('codenarcMain', JavaExec) {
    mainClass = 'org.codenarc.CodeNarc'
    args(
            '-basedir=src/main/groovy',
            '-rulesetfiles=file:config/codenarc/rules.groovy',
            '-report=html:build/reports/codenarc/main.html',
            '-maxPriority1Violations=0',
            '-maxPriority2Violations=0',
            '-maxPriority3Violations=0',
    )
    classpath = sourceSets.main.runtimeClasspath + configurations['codenarc']
}

tasks.register('codenarcTest', JavaExec) {
    mainClass = 'org.codenarc.CodeNarc'
    args(
            '-basedir=src/test/groovy',
            '-rulesetfiles=file:config/codenarc/rules.groovy',
            '-report=html:build/reports/codenarc/test.html',
            '-maxPriority1Violations=0',
            '-maxPriority2Violations=0',
            '-maxPriority3Violations=0',
    )
    classpath = sourceSets.main.runtimeClasspath + configurations['codenarc']
}

check.dependsOn codenarcMain
check.dependsOn codenarcTest
codenarcTest.mustRunAfter codenarcMain
test.mustRunAfter codenarcTest
```

**Comment by aibolit** [comment]
Seems like it's a problem with older groovy - I got it to work with the following

``` gradle
dependencies {
    codenarc 'org.apache.groovy:groovy-all:4.0.20'
    codenarc 'org.codenarc:CodeNarc:3.4.0-groovy-4.0'
}    
```

**Comment by peter-thomas-mgd** [comment]
@aibolit Thanks for the tip. We were able to successfully refactor our build to use the plugin by explicitly declaring the dependencies as per your solution.
