### ISSUE TITLE
SpaceAroundOperator flags violations for the optional array operator `?[`

### ISSUE THREAD

**Issue by aibolit** [CodeNarc/CodeNarc#758]
The SpaceAroundOperator flags violations for `a?[b]` 
There is already an explicit exception for the array operator `[` at https://github.com/CodeNarc/CodeNarc/blob/master/src/main/groovy/org/codenarc/rule/formatting/SpaceAroundOperatorRule.groovy#L167

I am using version `3.3.0-groovy-4.0` for testing

**Comment by chrismair** [comment]
I'm glad you specified the version you were using .. the violation did not occur in Groovy 3.x but did in Groovy 4.x.
