### ISSUE TITLE
Idea for new rule: InvalidMembersOrder

### ISSUE THREAD

**Issue by MaciejZiarko** [CodeNarc/CodeNarc#78]
The rule will check if order of members in a class is valid. For example that constructors should be defined above instance methods and below instance fields etc. 

It will be possible to configure the order of members:
For example:
`static_fields,instance_fields,constructors,instance_methods,static_methods`

If member type (for example static method) is skipped in configuration as here:
`static_fields,instance_fields,constructors,instance_methods`
their order will not be taken into account during code analysis.

`methods` will mean any method (static or instance), for example:
`static_fields,instance_fields,constructors,methods`

What do you think? I'd like to implement it.

**Comment by jlstrater** [comment]
Hi @MaciejZiarko ! Is this rule still needed?  If so, are you working on it or can I help?

**Comment by chrismair** [comment]
Closing. There are a few rules now that  cover some of that validation. Feel free to reopen if appropriate.
