### ISSUE TITLE
MultipleCompilationErrorsException: startup failed on various classes with v.3.5.0-groovy-4.0

### ISSUE THREAD

**Issue by SergeyMormul** [CodeNarc/CodeNarc#783]
There is a lot of warning in console like
```
WARNING: Compilation error for non-default compiler phase (semantic analysis). Consider removing "enhanced" rules from your ruleset.
Compilation failed for [CustomCompilerPhaseSourceDecorator[SourceFile[/project/ToolsUnitTest.groovy]]; phase=4 (semantic analysis)];
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
```
after migration from versions:
Gradle 7.4, Codenarc 3.3.0-groovy-4.0, Groovy 4.0.16
to
Gradle 8.9, Codenarc 3.5.0-groovy-4.0, Groovy 4.0.22

Enhanced rules are commented out in rulesets.

codenarc.gradle looks like the following:
```
apply plugin: 'codenarc'

dependencies {
    codenarc( "org.codenarc:CodeNarc:${codenarcVersion}" ) {
        exclude group: 'org.codehaus.groovy'
    }
    codenarc "org.apache.groovy:groovy-all:${groovyVersion}"
}

codenarc {
    toolVersion = codenarcVersion
    ignoreFailures = false
    reportFormat = 'console'
    codenarcMain {
        enabled = true
        configFile = file( "${rootDir}/gradle/codenarc-rules.groovy" )
    }
    codenarcTest {
        enabled = true
        configFile = file( "${rootDir}/gradle/codenarc-rules-test.groovy" )
    }
}
```
The warnings are shown regardless of `dependencies` block.
Everything is fine with version 3.4.0-groovy-4.0

**Comment by chrismair** [comment]
Hmmm, that's curious.

I assume you are excluding all of the enhanced rules, not just the ones in the "enhanced" ruleset?
[CodeNarc - About the Enhanced Classpath Rules](https://codenarc.org/codenarc-enhanced-classpath-rules.html)

**Comment by SergeyMormul** [comment]
My bad, I did only exclude rules from enhanced ruleset. Thanks for pointing at it.
I only want to add that some rules from the list have different names:
NotAllFieldsOfSerializableClassSerializable -> NonSerializableFieldInSerializableClass
OverridesNotNonCps -> ObjectOverrideOnlyNonCpsMethods

Everything is fine when **all** enhanced rules are disabled.

**Comment by chrismair** [comment]
Glad you got it working. And thanks for pointing out the wrong rule names. I'll get those corrected.
