### ISSUE TITLE
UnnecessaryGString leaves invalid code in data provider of Spock tests

### ISSUE THREAD

**Issue by sdoeringNew** [CodeNarc/CodeNarc#788]
Hi,

I'm using npm-groovy-lint with my Spock tests that have a data provider for several test cases.

    def "Test: #testCaseTitle"() {
        when:
        def result = testedMethod(json)

        then:
        result != null

        where:
        testCaseTitle     | json                                                      || errorMessage
        'missing image'   | """{ "view": "available", "options": ["empty"] }"""       || """JSON is missing image"""
        'missing options' | """{ "view": "available", "image": "${placeholder}" }"""  || """JSON is missing options"""
        'missing view'    | """{ "image": "${placeholder}", "options": ["empty"] }""" || """JSON is missing view"""
        'all missing'     | """{ }"""                                                 || """JSON is missing image, JSON is missing options, JSON is missing view"""
    }

After auto-fixing the code using CodeNarc the source code got uncompilable because of wrongly replaced GString quotes.

    def "Test: #testCaseTitle"() {
        when:
        def result = testedMethod(json)

        then:
        result != null

        where:
        testCaseTitle     | json                                                      || errorMessage
        'missing image'   | '''{ "view": "available", "options": ["empty"] }"""       || ""'JSON is missing image'""
        'missing options' | '''{ "view": "available", "image": "${placeholder}" }"""  || ""'JSON is missing options'""
        'missing view'    | """{ "image": "${placeholder}", "options": ["empty"] }""" || ""'JSON is missing view'""
        'all missing'     | ""'{ }'""                                                 || ""'JSON is missing image, JSON is missing options, JSON is missing view'""
    }

CodeNarc does not detect the end of the GStrings correctly and therefore replaces the the quotes at the wrong place leaving the source code uncompilable.

This:

    """{ "view": "available", "options": ["empty"] }"""

Becomes that:

    '''{ "view": "available", "options": ["empty"] }"""

This:

    """JSON is missing image"""

Becomes that:

    ""'JSON is missing image'""

That behaviour is not good.

Kind regards

**Comment by chrismair** [comment]
CodeNarc does the initial analysis and produces the violation, but the npm-groovy-lint tool handles the auto-fix part. This sounds like an issue with the auto fixing, so please open a ticket on [npm-groovy-lint](https://github.com/nvuillam/npm-groovy-lint).

**Comment by sdoeringNew** [comment]
Thanks. I've created the issue at [npm-groovy-lint](https://github.com/nvuillam/npm-groovy-lint/issues/436).
