### ISSUE TITLE
Provide mechanism for excluding a baseline findings file

### ISSUE THREAD

**Issue by johnrengelman** [CodeNarc/CodeNarc#89]
Similar to Findbugs `-excludeBugs` option, provide a way to run Codenarc on a project and use the resulting findings file as a baseline for subsequent runs.

This would help to mitigate issues when either applying Codenarc to an existing project, or upgrading Codenarc verions, where the number of findings is too large to deal with at the moment. Typically what happens is Codenarc is either removed or disabled on the project.

**Comment by chrismair** [comment]
Good idea. We face similar issues rolling out CodeNarc on existing codebases. I've often wondered about how to support something like that baseline. I'll try to take a look at the Findbugs approach.

**Comment by chrismair** [comment]
Available in CodeNarc 0.24.

Two steps are required:
1. Generate the baseline violations report file.
2. Update CodeNarc Ant Task configuration to specify the "excludeBaseline" property.
